### ISSUE TITLE
FreeBSD 12 

### ISSUE THREAD

**Issue by BuZZukin** [ant-media/Ant-Media-Server#1176]
# Issue

### Environment

* Operating system and version: FreeBSD 12
* Java version: 1.8
* Ant Media Server version: ant-media-server-1.6.2-community-1.6.2-20190323_0616.zip
* Browser name and version: FireFox

test:/usr/local/ant-media-server# ./start.sh
Running on  FreeBSD
Starting Ant Media Server
Root: /usr/local/ant-media-server
Configuation root: /usr/local/ant-media-server/conf
Ant Media Server jar was found
URL list: [file:/usr/local/ant-media-server/ant-media-server.jar]
Selected libraries: (177 items)

### Logs
Bootstrap exception: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.red5.server.Bootstrap.bootStrap(Bootstrap.java:122)
        at org.red5.server.Bootstrap.main(Bootstrap.java:50)
Caused by: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1043)
        at org.bytedeco.javacpp.Loader.load(Loader.java:935)
        at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:994)
        at org.bytedeco.javacpp.Loader.load(Loader.java:935)
        at org.bytedeco.javacpp.avformat.<clinit>(avformat.java:14)
        at org.red5.server.Launcher.launch(Launcher.java:69)
        ... 6 more
Bootstrap exit

Help!

**Comment by mekya** [comment]
FreeBSD is not officially supported.
