### ISSUE TITLE
Streamed like normal, but no file in VOD?

### ISSUE THREAD

**Issue by BackyardVoyager** [ant-media/Ant-Media-Server#1207]
Hello,

I am running the latest Ant-Media-Server build (I had to build it myself from source code as it would not compile and install from the automatic installer.

The VPS I am using Ant-Media solely on is on a fresh Ubuntu 16.04 64Bit build. VPS specs include 6GB of RAM, 6GB of vSwap, and 250GB of HDD. This is an OpenVZ. 

Yesterday when we tried to live stream an application, the stream worked fine then halfway through, it stopped recording. It was really random that it would stop recording to MP4, but it did. Our storage is only 16GB/250GB.

Where is a log I can check to find out what happened?

And also, what is the process of recording? Is it possible there is a raw file somewhere in the server files that I can pull the last half of my stream? It has never happened before...

**Comment by SelimEmre** [comment]
Hi @BackyardVoyager,

Could you please attach your log files( ant-media-server.log & antmedia-error.log )
Default log files location is here: /usr/local/antmedia/log/

Looking forwarding to hearing from you soon.
Selim.

**Comment by BackyardVoyager** [comment]
[antmedia-error.log](https://github.com/ant-media/Ant-Media-Server/files/3142695/antmedia-error.log)
[ant-media-server.log](https://github.com/ant-media/Ant-Media-Server/files/3142696/ant-media-server.log)
Here you go!

**Comment by BackyardVoyager** [comment]
I just had an error get thrown when my stream failed. It failed randomly:

May 06, 2019 10:53:56 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [default] in context with path [/LiveApp] threw exception
java.lang.NullPointerException
	at io.antmedia.filter.TokenFilterManager.getAppSettings(TokenFilterManager.java:107)
	at io.antmedia.filter.TokenFilterManager.doFilter(TokenFilterManager.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.red5.logging.LoggerContextFilter.doFilter(LoggerContextFilter.java:84)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mekya** [comment]
Please try the new versions and let us know if problem exists.
