### ISSUE TITLE
Exception: ConcurrentModificationException

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#1421]
java.util.ConcurrentModificationException: null at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) at java.util.ArrayList$Itr.next(ArrayList.java:859) at io.antmedia.enterprise.webrtc.WebRTCAdaptor.getNumberOfViewers(WebRTCAdaptor.java:224) at io.antmedia.enterprise.cluster.webrtc.EdgeClient.lambda$start$0(EdgeClient.java:92) at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885) at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844) at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748)

**Comment by mekya** [comment]
This error is not reported in 1.8.1 so closing this issue
