### ISSUE TITLE
Crash in Adding ONVIF Camera

### ISSUE THREAD

**Issue by maydin** [ant-media/Ant-Media-Server#1836]
Download https://play.google.com/store/apps/details?id=com.spynet.camon&hl=en in order to turn your phone into an ONVIF camera.
Start the app and get the ip address. 
Run Ant Media Server 1.9.1 Enterprise Edition in your local computer.
Add Ip Camera in WebRTCAppEE with the ip address. Equivalent REST API call is:
<img width="1010" alt="Screen Shot 2020-01-17 at 23 38 46" src="https://user-images.githubusercontent.com/2702247/72671998-88cc2c00-3a53-11ea-888c-78e202fb6b13.png">

Logs:
2020-01-17 23:37:45,333 [http-nio2-0.0.0.0-5080-exec-7] io.antmedia.rest.RestServiceBase - IP: 192.168.0.38
2020-01-17 23:37:45,334 [http-nio2-0.0.0.0-5080-exec-7] io.antmedia.rest.RestServiceBase - type ipCamera
2020-01-17 23:37:45,334 [http-nio2-0.0.0.0-5080-exec-7] io.antmedia.ipcamera.OnvifCamera - IP: 192.168.0.38:8080
Request SOAP Message (GetCapabilities): <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><env:Header><wsse:Security><wsse:UsernameToken><wsse:Username>admin</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">GeViCH3AkSHejALApArR/1KjigQ=</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">NjA5MzE0MDMz</wsse:Nonce><wsu:Created>2020-01-17T22:37:45Z</wsu:Created></wsse:UsernameToken></wsse:Security></env:Header><env:Body><GetCapabilities xmlns="http://www.onvif.org/ver10/device/wsdl"/></env:Body></env:Envelope>
Response SOAP Message (GetCapabilitiesResponse): <?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema"><s:Body><tds:GetCapabilitiesResponse><tds:Capabilities><tt:Analytics><tt:XAddr>http://192.168.0.38:8080/onvif/analytics_service</tt:XAddr><tt:RuleSupport>false</tt:RuleSupport><tt:AnalyticsModuleSupport>false</tt:AnalyticsModuleSupport></tt:Analytics><tt:Device><tt:XAddr>http://192.168.0.38:8080/onvif/device_service</tt:XAddr><tt:Network><tt:IPFilter>false</tt:IPFilter><tt:ZeroConfiguration>false</tt:ZeroConfiguration><tt:IPVersion6>false</tt:IPVersion6><tt:DynDNS>false</tt:DynDNS><tt:Extension><tt:Dot11Configuration>false</tt:Dot11Configuration></tt:Extension></tt:Network><tt:System><tt:DiscoveryResolve>false</tt:DiscoveryResolve><tt:DiscoveryBye>true</tt:DiscoveryBye><tt:RemoteDiscovery>true</tt:RemoteDiscovery><tt:SystemBackup>false</tt:SystemBackup><tt:SystemLogging>false</tt:SystemLogging><tt:FirmwareUpgrade>false</tt:FirmwareUpgrade><tt:SupportedVersions><tt:Major>2</tt:Major><tt:Minor>20</tt:Minor></tt:SupportedVersions><tt:Extension><tt:HttpFirmwareUpgrade>false</tt:HttpFirmwareUpgrade><tt:HttpSystemBackup>false</tt:HttpSystemBackup><tt:HttpSystemLogging>false</tt:HttpSystemLogging><tt:HttpSupportInformation>false</tt:HttpSupportInformation></tt:Extension></tt:System><tt:IO><tt:InputConnectors>0</tt:InputConnectors><tt:RelayOutputs>3</tt:RelayOutputs><tt:Extension><tt:Auxiliary>false</tt:Auxiliary></tt:Extension></tt:IO><tt:Security><tt:TLS1.1>false</tt:TLS1.1><tt:TLS1.2>false</tt:TLS1.2><tt:OnboardKeyGeneration>false</tt:OnboardKeyGeneration><tt:AccessPolicyConfig>false</tt:AccessPolicyConfig><tt:X.509Token>false</tt:X.509Token><tt:SAMLToken>false</tt:SAMLToken><tt:KerberosToken>false</tt:KerberosToken><tt:RELToken>false</tt:RELToken><tt:Extension><tt:TLS1.0>false</tt:TLS1.0><tt:Extension><tt:Dot1X>false</tt:Dot1X><tt:RemoteUserHandling>false</tt:RemoteUserHandling></tt:Extension></tt:Extension></tt:Security></tt:Device><tt:Media><tt:XAddr>http://192.168.0.38:8080/onvif/media_service</tt:XAddr><tt:StreamingCapabilities><tt:RTPMulticast>false</tt:RTPMulticast><tt:RTP_TCP>true</tt:RTP_TCP><tt:RTP_RTSP_TCP>true</tt:RTP_RTSP_TCP></tt:StreamingCapabilities><tt:Extension><tt:ProfileCapabilities><tt:MaximumNumberOfProfiles>1</tt:MaximumNumberOfProfiles></tt:ProfileCapabilities></tt:Extension></tt:Media><tt:Events><tt:XAddr>http://192.168.0.38:8080/onvif/event_service</tt:XAddr><tt:WSSubscriptionPolicySupport>false</tt:WSSubscriptionPolicySupport><tt:WSPullPointSupport>true</tt:WSPullPointSupport><tt:WSPausableSubscriptionManagerInterfaceSupport>false</tt:WSPausableSubscriptionManagerInterfaceSupport></tt:Events><tt:PTZ><tt:XAddr>http://192.168.0.38:8080/onvif/ptz_service</tt:XAddr></tt:PTZ><tt:Imaging><tt:XAddr>http://192.168.0.38:8080/onvif/image_service</tt:XAddr></tt:Imaging><tt:Extension><tt:DeviceIO><tt:XAddr>http://192.168.0.38:8080/onvif/deviceIO_service</tt:XAddr><tt:VideoSources>1</tt:VideoSources><tt:VideoOutputs>0</tt:VideoOutputs><tt:AudioSources>1</tt:AudioSources><tt:AudioOutputs>0</tt:AudioOutputs><tt:RelayOutputs>3</tt:RelayOutputs></tt:DeviceIO></tt:Extension></tds:Capabilities></tds:GetCapabilitiesResponse></s:Body></s:Envelope>
2020-01-17 23:37:47,196 [http-nio2-0.0.0.0-5080-exec-7] io.antmedia.rest.RestServiceBase - rtsp url with auth: rtsp://admin:pass@192.168.0.38:8080/video/h264
SystemUtils: java.lang.reflect.InaccessibleObjectException: Unable to make public double com.sun.management.internal.OperatingSystemImpl.getSystemCpuLoad() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @28348c6
2020-01-17 23:37:49,225 [Thread-13] io.antmedia.streamsource.StreamFetcher - StartStream called, new thread is started for 503137403324526290128639
2020-01-17 23:37:49,225 [Thread-14] io.antmedia.streamsource.StreamFetcher - Preparing the StreamFetcher for rtsp://admin:pass@192.168.0.38:8080/video/h264
2020-01-17 23:37:52,866 [vert.x-eventloop-thread-7] io.antmedia.streamsource.StreamFetcherManager - Stream is not alive and setting quality to poor of stream: 503137403324526290128639 url: rtsp://admin:pass@192.168.0.38:8080/video/h264
SystemUtils: java.lang.reflect.InaccessibleObjectException: Unable to make public double com.sun.management.internal.OperatingSystemImpl.getSystemCpuLoad() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @28348c6
2020-01-17 23:37:54,391 [Thread-14] io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for 503137403324526290128639
2020-01-17 23:37:54,393 [Thread-14] io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2020-01-17 23:37:54,395 [Thread-14] io.antmedia.enterprise.adaptive.EncoderAdaptor - vertx exist io.vertx.core.impl.VertxImpl@72113053
2020-01-17 23:37:54,396 [Thread-14] io.antmedia.enterprise.adaptive.EncoderAdaptor - ServerSettings exist io.antmedia.settings.ServerSettings@3a512337
2020-01-17 23:37:54,396 [Thread-14] io.antmedia.streamsource.StreamFetcher - 503137403324526290128639 stream count in stream rtsp://admin:pass@192.168.0.38:8080/video/h264 is 2
2020-01-17 23:37:54,571 [Thread-14] io.antmedia.enterprise.adaptive.EncoderAdaptor - find decoder for stream: 503137403324526290128639
2020-01-17 23:37:54,606 [Thread-14] io.antmedia.enterprise.adaptive.EncoderAdaptor - decoder name:  h264 for 503137403324526290128639
2020-01-17 23:37:54,627 [Thread-14] io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2020-01-17 23:37:54,630 [Thread-14] io.antmedia.enterprise.adaptive.StreamAdaptor - Stream adaptor scheduled job name 12
2020-01-17 23:37:54,633 [Thread-14] io.antmedia.enterprise.adaptive.StreamAdaptor - Stream adaptor scheduled job name 13
2020-01-17 23:37:54,642 [Thread-14] io.antmedia.enterprise.adaptive.EncoderAdaptor - java.lang.ArithmeticException: / by zero
	at io.antmedia.enterprise.adaptive.H264Encoder.prepareCodecLocal(H264Encoder.java:82)
	at io.antmedia.enterprise.adaptive.base.VideoEncoder.prepareCodec(VideoEncoder.java:73)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareVideoEncoders(EncoderAdaptor.java:624)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareEncoders(EncoderAdaptor.java:569)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareInternal(EncoderAdaptor.java:279)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:235)

2020-01-17 23:37:54,642 [Thread-14] io.antmedia.enterprise.preview.PngEncoder - preparing codec for stream: 503137403324526290128639
2020-01-17 23:37:54,644 [Thread-14] io.antmedia.enterprise.adaptive.EncoderAdaptor - java.lang.ArithmeticException: / by zero
	at io.antmedia.enterprise.preview.PngEncoder.prepareCodecLocal(PngEncoder.java:70)
	at io.antmedia.enterprise.adaptive.base.VideoEncoder.prepareCodec(VideoEncoder.java:73)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareVideoEncoders(EncoderAdaptor.java:624)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareEncoders(EncoderAdaptor.java:569)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareInternal(EncoderAdaptor.java:279)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:235)

2020-01-17 23:37:54,650 [Thread-14] io.antmedia.enterprise.adaptive.AACEncoder - name : aac
2020-01-17 23:37:54,693 [Thread-14] io.antmedia.muxer.HLSMuxer - copy codec parameter from context 0 stream index: 1
2020-01-17 23:37:54,695 [Thread-14] io.antmedia.enterprise.adaptive.OpusEncoder - encoder name libopus source sample rate 48000, channel layout 4
2020-01-17 23:37:54,703 [Thread-14] io.antmedia.enterprise.webrtc.WebRTCAdaptor - registering 503137403324526290128639 muxer with 480p to webrtc adaptor
2020-01-17 23:37:54,703 [Thread-14] io.antmedia.enterprise.webrtc.WebRTCAdaptor - Increasing number of live streams: 1 and stream id:503137403324526290128639
2020-01-17 23:37:54,706 [Thread-14] io.antmedia.AntMediaApplicationAdapter - start publish leaved
2020-01-17 23:37:54,719 [Thread-14] io.antmedia.streamsource.StreamFetcher - dts (0) is bigger than pts(-7440)
2020-01-17 23:37:54,720 [vert.x-worker-thread-15] io.antmedia.AntMediaApplicationAdapter -  Status of stream 503137403324526290128639 is set to Broadcasting with result: true
2020-01-17 23:37:54,723 [Thread-14] io.antmedia.muxer.MuxAdaptor - first packet time 0
2020-01-17 23:37:54,761 [Thread-14] io.antmedia.streamsource.StreamFetcher - dts (1) is bigger than pts(-6416)
2020-01-17 23:37:54,761 [Thread-14] io.antmedia.streamsource.StreamFetcher - dts (2) is bigger than pts(-5392)
2020-01-17 23:37:54,762 [Thread-14] io.antmedia.streamsource.StreamFetcher - dts (3) is bigger than pts(-4385)
2020-01-17 23:37:54,762 [Thread-14] io.antmedia.streamsource.StreamFetcher - dts (4) is bigger than pts(-3361)
2020-01-17 23:37:54,762 [Thread-14] io.antmedia.streamsource.StreamFetcher - dts (5) is bigger than pts(-2337)
2020-01-17 23:37:54,762 [Thread-14] io.antmedia.streamsource.StreamFetcher - dts (6) is bigger than pts(-1313)
2020-01-17 23:37:54,762 [Thread-14] io.antmedia.streamsource.StreamFetcher - dts (7) is bigger than pts(-289)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011ab5e8f6, pid=13729, tid=88323
#
# JRE version: OpenJDK Runtime Environment (11.0.2+9) (build 11.0.2+9)
# Java VM: OpenJDK 64-Bit Server VM (11.0.2+9, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libjniavformat.dylib+0xd8f6]  Java_org_bytedeco_javacpp_avformat_00024AVStream_codecpar__+0x46
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/maydin/Downloads/ant-media-server/hs_err_pid13729.log
Compiled method (nm)   48230 9676     n 0       org.bytedeco.javacpp.avformat$AVStream::codecpar (native)
 total in heap  [0x0000000111228910,0x0000000111228d30] = 1056
 relocation     [0x0000000111228a88,0x0000000111228ac0] = 56
 main code      [0x0000000111228ac0,0x0000000111228d28] = 616
 oops           [0x0000000111228d28,0x0000000111228d30] = 8
Compiled method (nm)   48230 9683     n 0       org.bytedeco.javacpp.avformat$AVStream::time_base (native)
 total in heap  [0x000000011172a710,0x000000011172ab30] = 1056
 relocation     [0x000000011172a888,0x000000011172a8c0] = 56
 main code      [0x000000011172a8c0,0x000000011172ab28] = 616
 oops           [0x000000011172ab28,0x000000011172ab30] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6

**Comment by SelimEmre** [comment]
I tested with local environment. It's working with v2.3.1 SNAPSHOT. So, we can close this issue.
