### ISSUE TITLE
Live stream with Facebook streaming account timeout error.

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2184]
**Describe the bug**
Facebook works for a few days after I connect it, then when I go to stream a few days later all of a sudden it gives me the error I sent you. I then have to delete that FB account and reconnect it to that stream.
All streams on that list have the same issue if I use them with Facebook.

**To Reproduce**
1. Add Facebook Stream account
2. Add Live Stream with Facebook Streaming account
3. Go live with this stream
3. Wait 2-3 day
4. Try to live stream same broadcast.

**Expected behavior**
It should work.

**Additional context**
`2020-05-09 19:31:50,071 [Red5_Scheduler_Worker-6] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/1346672782196709?s_bl=1&s_sc=1346672805530040&s_sw=0&s_vt=api-s&a=AbyggITpQtuJZcZI`

**Comment by jfreak53** [comment]
This is still an issue, except now it won't last a full week, it only lasts a couple of days. I streamed on Sunday night to FB, no issues. I went back Wed night to stream again, didn't connect, had to remove FB from the stream ID, and re-save after checking the box again to get it to connect to FB again.

So now it's not lasting a full week in-between streams to FB and YT.

**Comment by SelimEmre** [comment]
I encountered this issue in customer Instance(v2.1). I will also try this issue in our test environment.

```
2020-08-12 13:53:04,872 [RTMPConnectionExecutor-1] INFO  i.a.e.streamapp.StreamApplication - W3C x-category:session x-event:connect c-ip:37.130.106.68 c-client-id:5
2020-08-12 13:53:05,399 [RTMPConnectionExecutor-1] INFO  i.a.s.AcceptOnlyStreamsInDataStore - AcceptOnlyStreamsInDataStore is not activated. Accepting all streams 526119354983062631631829
2020-08-12 13:53:05,400 [RTMPConnectionExecutor-1] INFO  org.red5.server.scope.BasicScope - ClientBroadcastStream already exists: org.red5.server.stream.ClientBroadcastStream@4d129cec new: org.red5.server.strea$
2020-08-12 13:53:05,400 [RTMPConnectionExecutor-1] INFO  o.r.s.stream.ClientBroadcastStream - Stream start: 526119354983062631631829
2020-08-12 13:53:05,401 [RTMPConnectionExecutor-1] INFO  i.a.AntMediaApplicationAdapter - stream name in streamPublishStart: 526119354983062631631829
2020-08-12 13:53:05,401 [RTMPConnectionExecutor-1] INFO  i.a.AntMediaApplicationAdapter - start publish leaved
2020-08-12 13:53:05,401 [RTMPConnectionExecutor-1] INFO  i.a.e.streamapp.StreamApplication - W3C x-category:stream x-event:publish c-ip:37.130.106.68 x-sname:61ba8c4e-6c92-40df-9a1e-8884820df9bf x-name:52611935$
2020-08-12 13:53:05,472 [vert.x-worker-thread-17] INFO  i.a.AntMediaApplicationAdapter -  Status of stream 526119354983062631631829 is set to Broadcasting with result: true
2020-08-12 13:53:05,472 [RTMPConnectionExecutor-1] INFO  io.antmedia.muxer.MuxAdaptor - vertx exist io.vertx.core.impl.VertxImpl@4957ba
2020-08-12 13:53:05,472 [RTMPConnectionExecutor-1] INFO  io.antmedia.muxer.MuxAdaptor - adding MP4 Muxer, add datetime to file name true
2020-08-12 13:53:05,473 [RTMPConnectionExecutor-1] INFO  io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for 526119354983062631631829
2020-08-12 13:53:05,474 [RTMPConnectionExecutor-1] INFO  io.antmedia.muxer.Muxer - Date time resource name: 526119354983062631631829-2020-08-12_13-53-05 local date time: 2020-08-12_13:53:05
2020-08-12 13:53:05,475 [RTMPConnectionExecutor-1] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2020-08-12 13:53:05,475 [RTMPConnectionExecutor-1] INFO  i.a.e.adaptive.EncoderAdaptor - ServerSettings exist io.antmedia.settings.ServerSettings@4190cc68
2020-08-12 13:53:05,475 [RTMPConnectionExecutor-1] INFO  io.antmedia.muxer.MuxAdaptor - Number of items in the queue while adaptor is being started to prepare is 0
2020-08-12 13:53:05,476 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.MuxAdaptor - before prepare for 526119354983062631631829
2020-08-12 13:53:05,477 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.MuxAdaptor - before avformat_open_input for stream 526119354983062631631829
2020-08-12 13:53:05,478 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.MuxAdaptor - Checking streams for stream: 526119354983062631631829
2020-08-12 13:53:05,848 [vert.x-worker-thread-17] ERROR i.a.AntMediaApplicationAdapter - com.restfb.exception.FacebookGraphException: Received Facebook error response of type GraphMethodException: Unsupported post request. Object with ID '101406631676906' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api (code 100, subcode 33) 'null - null'
        at com.restfb.exception.generator.DefaultFacebookExceptionGenerator$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookExceptionGenerator.java:187)
        at com.restfb.exception.generator.DefaultFacebookExceptionGenerator.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookExceptionGenerator.java:61)
        at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:832)
        at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:754)
        at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:355)
        at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:380)
        at io.antmedia.enterprise.social.endpoint.FacebookEndpoint.publishBroadcast(FacebookEndpoint.java:301)
        at io.antmedia.AntMediaApplicationAdapter.publishSocialEndpoints(AntMediaApplicationAdapter.java:499)
        at io.antmedia.AntMediaApplicationAdapter.lambda$startPublish$8(AntMediaApplicationAdapter.java:469)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2020-08-12 13:53:05,938 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.MuxAdaptor - Video and Audio is detected in the incoming stream for stream: 526119354983062631631829
2020-08-12 13:53:05,939 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.MuxAdaptor - Streams for 526119354983062631631829 enableVideo:true enableAudio:true total spend time: 460 elapsed frame timestamp: 1 $
2020-08-12 13:53:05,939 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.MuxAdaptor - before avformat_find_stream_info for stream: 526119354983062631631829
2020-08-12 13:53:07,280 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.MuxAdaptor - avformat_find_stream_info takes 1341ms for stream:526119354983062631631829
2020-08-12 13:53:07,281 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.RtmpMuxer - preparing rtmp muxer for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406651676904&s_sw=0&s_vt$
2020-08-12 13:53:07,281 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.RtmpMuxer - rtmp muxer opening: rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406651676904&s_sw=0&s_vt=api-$
2020-08-12 13:53:07,594 [vert.x-eventloop-thread-31] ERROR io.antmedia.muxer.RtmpMuxer - Could not open output file for rtmp url rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406651676$
2020-08-12 13:53:07,594 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.RecordMuxer - video codec par extradata size 39 codec id: 27
2020-08-12 13:53:07,596 [vert.x-eventloop-thread-31] INFO  i.a.e.adaptive.EncoderAdaptor - not decoding video for stream: 526119354983062631631829
2020-08-12 13:53:07,597 [vert.x-eventloop-thread-31] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor scheduled job id 150 stream adaptor:407251911 for stream:526119354983062631631829
2020-08-12 13:53:07,597 [vert.x-eventloop-thread-31] INFO  i.a.enterprise.adaptive.OpusEncoder - encoder name libopus source sample rate 44100, channel layout 3
2020-08-12 13:53:07,598 [vert.x-eventloop-thread-31] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - registering 526119354983062631631829 muxer with 1080p and codec::H264 to webrtc adaptor
2020-08-12 13:53:07,598 [vert.x-eventloop-thread-31] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Increasing number of live streams: 1 and stream id:526119354983062631631829
2020-08-12 13:53:07,598 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.MuxAdaptor - after prepare for 526119354983062631631829
2020-08-12 13:53:07,598 [vert.x-eventloop-thread-31] INFO  io.antmedia.muxer.MuxAdaptor - Number of items in the queue while starting: 27 for stream: 526119354983062631631829
2020-08-12 13:53:07,608 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.MuxAdaptor - first packet time 1
2020-08-12 13:53:07,609 [vert.x-worker-thread-4] INFO  i.a.filter.StreamAcceptFilter - Stream FPS value: 30
2020-08-12 13:53:07,609 [vert.x-worker-thread-4] ERROR i.a.filter.StreamAcceptFilter - Stream Resolution value: 1080
2020-08-12 13:53:07,609 [vert.x-worker-thread-4] ERROR i.a.filter.StreamAcceptFilter - Stream Bitrate value: 1024000
2020-08-12 13:53:07,610 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,611 [vert.x-worker-thread-4] WARN  io.antmedia.muxer.RecordMuxer - First key frame received for stream: 526119354983062631631829
2020-08-12 13:53:07,612 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,613 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,613 [vert.x-worker-thread-4] WARN  io.antmedia.muxer.MuxAdaptor - Packet dts(1) queue value does not match with the native dts(33) for stream:526119354983062631631829 try one more attempt
2020-08-12 13:53:07,613 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,613 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,614 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,614 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,614 [vert.x-eventloop-thread-31] INFO  i.a.AntMediaApplicationAdapter - update source quality for stream: 526119354983062631631829 quality:null speed:0.0
2020-08-12 13:53:07,614 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,615 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,615 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,615 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
2020-08-12 13:53:07,615 [vert.x-worker-thread-4] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmps://live-api-s.facebook.com:443/rtmp/101406631676906?s_bl=1&s_sc=101406$
```

**Comment by mekya** [comment]
Just let me give some thoughts about that. 

Facebook, Youtube and Periscope built-in integrations are hard to maintain and there are lots of cases that should be handled. It's likely this problem is something about Facebook side. I don't mean a bug on Facebook side. I mean we're likely missing something to handle something in Facebook side. 

As a result, we think doing these kind of things in application level will be a better design so that we may remove built-in support for platforms Facebook, Youtube, etc. We continue giving support for publishing RTMP endpoints so that Ant Media Server can publish to any RTMP URL from Facebook, Youtube, Instagram or any other platform. 

This is not a clear decision yet on our side. Let us know your thoughts if you want to share @jfreak53

**Comment by jfreak53** [comment]
I can understand the position, however, the whole point of me purchasing your software was the built-in support to simul-stream to Facebook and youtube. So if these features will be removed from the software I will no longer have a use for it and will need to find new software to purchase.

**Comment by mekya** [comment]
Ant Media Server continue to support adding any RTMP endpoint including(youtube, facebook, instagram, vimeo, etc.) But we don't maintain full integration with social media accounts. Because it's hard to maintain. There are somethings changing and they force the developers to take actions. We thinkg that the best way is letting developers develop their social media application and use Ant Media Server as a streaming engine that can push streams to any RTMP endpoint.   

So closing this issue. Sorry.
