### ISSUE TITLE
 [vert.x-eventloop-thread-3] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for XXX ms

### ISSUE THREAD

**Issue by jzvi12** [ant-media/Ant-Media-Server#2220]
Fresh install of Ant Media on my Linux VPS running Ubuntu 18.04.

When I access the web page (remotely), I'm able to see myself on the webcam, then hit the "Publish stream" button and the logs throws the following warnings, errors and stack traces:

Note: I'm new to Ant Media.

```

2020-06-02 17:13:45,683 [http-nio2-0.0.0.0-8055-exec-1] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened
2020-06-02 17:13:46,746 [NioProcessor-6] WARN  o.r.s.net.rtmp.InboundHandshake - Client not compatible
2020-06-02 17:13:46,758 [RTMPConnectionExecutor-3] INFO  i.a.e.streamapp.StreamApplication - W3C x-category:session x-event:connect c-ip:127.0.0.1 c-client-id:4
2020-06-02 17:13:46,925 [RTMPConnectionExecutor-3] INFO  i.a.s.AcceptOnlyStreamsInDataStore - AcceptOnlyStreamsInDataStore is not activated. Accepting all streams stream1
2020-06-02 17:13:46,927 [RTMPConnectionExecutor-3] INFO  org.red5.server.scope.BasicScope - ClientBroadcastStream already exists: org.red5.server.stream.ClientBroadcastStream@210081f8 new: org.red5.server.stream.ClientBroadcastStream@210081f8
2020-06-02 17:13:46,927 [RTMPConnectionExecutor-3] INFO  o.r.s.stream.ClientBroadcastStream - Stream start: stream1
2020-06-02 17:13:46,928 [RTMPConnectionExecutor-3] INFO  i.a.AntMediaApplicationAdapter - stream name in streamPublishStart: stream1
2020-06-02 17:13:46,929 [RTMPConnectionExecutor-3] INFO  i.a.AntMediaApplicationAdapter - start publish leaved
2020-06-02 17:13:46,929 [RTMPConnectionExecutor-3] INFO  i.a.e.streamapp.StreamApplication - W3C x-category:stream x-event:publish c-ip:127.0.0.1 x-sname:dec29e4c-4797-4934-8ea0-c32f02aa9ca2 x-name:stream1
2020-06-02 17:13:46,947 [RTMPConnectionExecutor-3] ERROR io.antmedia.muxer.MuxAdaptor - io.antmedia.enterprise.adaptive.EncoderAdaptor
2020-06-02 17:13:46,956 [pool-24-thread-1] INFO  org.webrtc.Logging - Tag:NativeLibrary - Message:Native library has already been loaded.
2020-06-02 17:13:47,014 [pool-24-thread-1] INFO  org.webrtc.Logging - Tag:PeerConnectionFactory - Message:PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
2020-06-02 17:13:47,014 [pool-24-thread-1] INFO  org.webrtc.Logging - Tag:JavaAudioDeviceModule - Message:createAudioDeviceModule
2020-06-02 17:13:47,014 [pool-24-thread-1] INFO  org.webrtc.Logging - Tag:JavaAudioDeviceModule - Message:HW NS will not be used.
2020-06-02 17:13:47,014 [pool-24-thread-1] INFO  org.webrtc.Logging - Tag:JavaAudioDeviceModule - Message:HW AEC will not be used.
2020-06-02 17:13:47,044 [RTMPConnectionExecutor-3] INFO  io.antmedia.muxer.MuxAdaptor - vertx exist io.vertx.core.impl.VertxImpl@75bb4cfc
2020-06-02 17:13:47,044 [RTMPConnectionExecutor-3] INFO  io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for stream1
2020-06-02 17:13:47,046 [RTMPConnectionExecutor-3] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2020-06-02 17:13:47,046 [RTMPConnectionExecutor-3] INFO  io.antmedia.muxer.MuxAdaptor - Number of items in the queue while adaptor is being started to prepare is 0
2020-06-02 17:13:47,047 [vert.x-eventloop-thread-2] INFO  io.antmedia.muxer.MuxAdaptor - before prepare for stream1
2020-06-02 17:13:47,047 [vert.x-eventloop-thread-2] INFO  io.antmedia.muxer.MuxAdaptor - before avformat_open_input for stream stream1
2020-06-02 17:13:47,049 [vert.x-eventloop-thread-2] INFO  io.antmedia.muxer.MuxAdaptor - Checking streams for stream: stream1
2020-06-02 17:13:47,049 [vert.x-eventloop-thread-2] INFO  io.antmedia.muxer.MuxAdaptor - Video and Audio is detected in the incoming stream for stream: stream1
2020-06-02 17:13:47,049 [vert.x-eventloop-thread-2] INFO  io.antmedia.muxer.MuxAdaptor - Streams for stream1 enableVideo:true enableAudio:true total spend time: 0 elapsed frame timestamp: 0 stop request exists: false
2020-06-02 17:13:47,049 [vert.x-eventloop-thread-2] INFO  io.antmedia.muxer.MuxAdaptor - before avformat_find_stream_info for stream: stream1
2020-06-02 17:13:47,470 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 250 ms
2020-06-02 17:13:47,549 [http-nio2-0.0.0.0-8055-exec-9] INFO  i.a.w.WebSocketCommunityHandler - received sdp type is offer stream1
2020-06-02 17:13:47,553 [network_thread - 20733] WARN  io.antmedia.webrtc.adaptor.Adaptor - onAddStream for stream: stream1
2020-06-02 17:13:47,557 [network_thread - 20733] WARN  io.antmedia.webrtc.adaptor.Adaptor - onCreate Success for stream: stream1
2020-06-02 17:13:47,558 [network_thread - 20733] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:initPlayout(sampleRate=16000, channels=1, bufferSizeFactor=1.0)
2020-06-02 17:13:47,558 [network_thread - 20733] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:byteBuffer.capacity: 320
2020-06-02 17:13:47,559 [network_thread - 20733] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:startPlayout(sampleRate=16000, channels=1)
2020-06-02 17:13:47,575 [network_thread - 20733] INFO  io.antmedia.webrtc.adaptor.Adaptor - set localdescription on set success  for stream1
2020-06-02 17:13:47,577 [network_thread - 20733] WARN  io.antmedia.webrtc.adaptor.Adaptor - onIceCandidate
2020-06-02 17:13:47,614 [network_thread - 20733] WARN  io.antmedia.webrtc.adaptor.Adaptor - onIceCandidate
2020-06-02 17:13:47,676 [network_thread - 20733] WARN  io.antmedia.webrtc.adaptor.Adaptor - onIceCandidate
2020-06-02 17:13:47,779 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 500 ms
2020-06-02 17:13:48,037 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 750 ms
2020-06-02 17:13:48,341 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 1000 ms
2020-06-02 17:13:48,629 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 1250 ms
2020-06-02 17:13:48,884 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 1500 ms
2020-06-02 17:13:49,142 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 1750 ms
2020-06-02 17:13:49,234 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2186 ms, time limit is 2000
2020-06-02 17:13:49,397 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 2000 ms
2020-06-02 17:13:49,577 [http-nio2-0.0.0.0-8055-exec-8] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened
2020-06-02 17:13:49,669 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 2250 ms
2020-06-02 17:13:49,923 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 2500 ms
2020-06-02 17:13:50,177 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 2750 ms
2020-06-02 17:13:50,234 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3186 ms, time limit is 2000
2020-06-02 17:13:50,431 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 3000 ms
2020-06-02 17:13:50,685 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 3250 ms
2020-06-02 17:13:50,943 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 3500 ms
2020-06-02 17:13:51,198 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 3750 ms
2020-06-02 17:13:51,234 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 4185 ms, time limit is 2000
2020-06-02 17:13:51,457 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 4000 ms
2020-06-02 17:13:51,711 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 4250 ms
2020-06-02 17:13:51,967 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 4500 ms
2020-06-02 17:13:52,221 [vert.x-eventloop-thread-2] WARN  io.antmedia.muxer.MuxAdaptor - Stream: stream1 does not get packet for 4750 ms
2020-06-02 17:13:52,234 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 5185 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
        at java.lang.Thread.sleep(Native Method)
        at io.antmedia.muxer.MuxAdaptor$1.call(MuxAdaptor.java:235)
        at org.bytedeco.javacpp.avformat.avformat_find_stream_info(Native Method)
        at io.antmedia.muxer.MuxAdaptor.prepare(MuxAdaptor.java:458)
        at io.antmedia.muxer.MuxAdaptor.lambda$start$6(MuxAdaptor.java:897)
        at io.antmedia.muxer.MuxAdaptor$$Lambda$174/31956345.handle(Unknown Source)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.vertx.core.impl.ContextImpl$$Lambda$15/2035233328.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

More of the above log can be seen here: https://pastebin.com/raw/6yjbDLBR

**Comment by mekya** [comment]
Hey @jzvi12 ,

Welcome aboard. :)

The problem you're seeing is about RTMP publishing. It seems that Ant Media Server cannot get RTMP stream and it complains about not receiving video packets. 

I think you can use OBS for sending RTMP stream. Check this out. 
https://github.com/ant-media/Ant-Media-Server/wiki/Open-Broadcaster-Software-Publishing

**Comment by jzvi12** [comment]
> The problem you're seeing is about RTMP publishing. It seems that Ant Media Server cannot get RTMP stream and it complains about not receiving video packets.
> 

@mekya I see what you're saying.. I was totally confused. I thought I could broadcast the WebRTC (browser) session to an RTMP destination, same as Jitsi or Streamyard which stream directly from the webpage instead of downloading an encoder such as OBS.
