### ISSUE TITLE
Throws io.antmedia.recorder.FrameRecorder$Exception: av_interleaved_write_frame() error -41  in community edition

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2491]
When publishing to community edition with WebRTC, it throws the following exception all the time

2020-09-13 11:24:49,347 [pool-23-thread-1] io.antmedia.webrtc.adaptor.RTMPAdaptor - io.antmedia.recorder.FrameRecorder$Exception: av_interleaved_write_frame() error -41 while writing interleaved audio packet.
	at io.antmedia.recorder.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1290)
	at io.antmedia.recorder.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:1276)
	at io.antmedia.recorder.FFmpegFrameRecorder.writeSamples(FFmpegFrameRecorder.java:1247)
	at io.antmedia.recorder.FFmpegFrameRecorder.recordSamples(FFmpegFrameRecorder.java:1222)
	at io.antmedia.webrtc.adaptor.RTMPAdaptor.lambda$null$2(RTMPAdaptor.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mekya** [comment]
This happens when server does not find stream info in 5 seconds(maxAnalyzeDuration*10) by default. 
You can increase it by setting a higher value than 500 to maxAnalyzeDuration in app configuration.(WEB-INF/red5-web.properties) 

The following value make the maxAnalyzeDuration to 3 seconds and it makes max wait time to 30 seconds.  

```settings.rtmp.maxAnalyzeDurationMS=3000```
