### ISSUE TITLE
S3 incompatible with OVH Object Storage

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2543]
### Short description
I tried to use S3 in OVH Object Storage. But I couldn't succeed. 

### Steps to reproduce
1. I created a new Object Storage with Public type. 
2. I created a user for OpenStack and created EC2 credentials according to below docs:
https://www.youtube.com/watch?v=2OztjH2XU1I
https://docs.ovh.com/gb/en/public-cloud/getting_started_with_the_swift_S3_API/
3. I edited `red5-web.xml` file according to OpenStack access/secret keys. Added endpoint parameter as above doc. 
For example: `<property name="endpoint" value="https://s3.uk.cloud.ovh.net" />` Also added `storageName` as Object Storage name. 
```
<bean id="app.storageClient" class="io.antmedia.storage.AmazonS3StorageClient">
    <property name="accessKey" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" />
    <property name="secretKey" value="yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy" />
    <property name="endpoint" value="https://s3.uk.cloud.ovh.net" />	
    <property name="region" value="uk" />
    <property name="storageName" value="objectBucketName" />
</bean>
```
4. I saw below links, but they couldn't help me.
https://groups.google.com/g/ant-media-server/c/u2KZ77JbRFU/m/WDmI56L3BwAJ
https://github.com/ant-media/Ant-Media-Server/issues/1437

### Expected behavior
It should work properly.

### Actual behavior
It couldn't work.

### Logs
AMS latest SNAPSHOT

If I add `region` parameter like `uk`, I'm getting below error:
```
SEVERE: Unhandled exception
java.lang.IllegalArgumentException: Cannot create enum from uk value!
	at com.amazonaws.regions.Regions.fromName(Regions.java:79)
	at io.antmedia.storage.AmazonS3StorageClient.getAmazonS3(AmazonS3StorageClient.java:50)
	at io.antmedia.storage.AmazonS3StorageClient.fileExist(AmazonS3StorageClient.java:74)
	at io.antmedia.muxer.RecordMuxer.lambda$saveToStorage$2(RecordMuxer.java:423)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2020-09-28 01:23:21,633 [vert.x-eventloop-thread-11] io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalArgumentException: Cannot create enum from uk value!
	at com.amazonaws.regions.Regions.fromName(Regions.java:79)
	at io.antmedia.storage.AmazonS3StorageClient.getAmazonS3(AmazonS3StorageClient.java:50)
	at io.antmedia.storage.AmazonS3StorageClient.fileExist(AmazonS3StorageClient.java:74)
	at io.antmedia.muxer.RecordMuxer.lambda$saveToStorage$2(RecordMuxer.java:423)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

If I remove `region` parameter, I'm getting below error:

```
2020-09-28 01:25:41,673 [vertx-blocked-thread-checker] io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-11,5,main] has been blocked for 6402 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at java.lang.Thread.sleep(Native Method)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:399)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:404)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:404)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:355)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:351)
	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:266)
	at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:48)
	at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:39)
	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
	at com.amazonaws.client.builder.AwsClientBuilder.determineRegionFromRegionProvider(AwsClientBuilder.java:384)
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:367)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:337)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at io.antmedia.storage.AmazonS3StorageClient.getAmazonS3(AmazonS3StorageClient.java:56)
	at io.antmedia.storage.AmazonS3StorageClient.fileExist(AmazonS3StorageClient.java:74)
	at io.antmedia.muxer.RecordMuxer.lambda$saveToStorage$2(RecordMuxer.java:423)
	at io.antmedia.muxer.RecordMuxer$$Lambda$203/935519505.handle(Unknown Source)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.vertx.core.impl.ContextImpl$$Lambda$27/1580959977.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Sep 28, 2020 1:25:42 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:371)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:337)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at io.antmedia.storage.AmazonS3StorageClient.getAmazonS3(AmazonS3StorageClient.java:56)
	at io.antmedia.storage.AmazonS3StorageClient.fileExist(AmazonS3StorageClient.java:74)
	at io.antmedia.muxer.RecordMuxer.lambda$saveToStorage$2(RecordMuxer.java:423)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Also, I tried with `us-west-2` parameter(it means London) as region. It didn't work either.
```
java.lang.IllegalStateException: Only one of Region or EndpointConfiguration may be set.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:359)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:337)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at io.antmedia.storage.AmazonS3StorageClient.getAmazonS3(AmazonS3StorageClient.java:56)
	at io.antmedia.storage.AmazonS3StorageClient.fileExist(AmazonS3StorageClient.java:74)
	at io.antmedia.muxer.RecordMuxer.lambda$saveToStorage$2(RecordMuxer.java:423)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2020-09-28 01:32:59,869 [vert.x-eventloop-thread-11] io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Only one of Region or EndpointConfiguration may be set.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:359)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:337)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at io.antmedia.storage.AmazonS3StorageClient.getAmazonS3(AmazonS3StorageClient.java:56)
	at io.antmedia.storage.AmazonS3StorageClient.fileExist(AmazonS3StorageClient.java:74)
	at io.antmedia.muxer.RecordMuxer.lambda$saveToStorage$2(RecordMuxer.java:423)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-09-28 01:33:36,463 [pool-4-thread-1] org.red5.server.tomcat.WarDeployer - Deploy wars with app start
```
I hope, it's clear.

**Comment by SelimEmre** [comment]
Hi,

I solved this bug. Now it's working with OVH Object Storage and AWS S3. It worked both of them. Here is the PR -> https://github.com/ant-media/Ant-Media-Server-Common/pull/242

The problem is related to [Region](https://github.com/ant-media/Ant-Media-Server-Common/blob/master/src/main/java/io/antmedia/storage/AmazonS3StorageClient.java#L39) and [Endpoint configuration](https://github.com/ant-media/Ant-Media-Server-Common/blob/master/src/main/java/io/antmedia/storage/AmazonS3StorageClient.java#L50) controls. We need to add `getEndpoint` check in `getRegion` control.

Best Regards,
Selim

**Comment by burak-58** [comment]
https://antmedia.io/docs/version-2.11.3/guides/recording-live-streams/s3-recording-and-integration/ovh-object-storage/
