### ISSUE TITLE
Error parsing 'streamIdInUse' message

### ISSUE THREAD

**Issue by luismacb** [ant-media/Ant-Media-Server#2574]
### Short description
When someone tries to publish on a streamId in which some other is already publishing, a message like this is received:

{“definition”:“streamIdInUse”,“command”:“error”}

However, the sdk throws an JSONException trying to parse it and then is ignored and connection kept alive indefinitely.

The message should be parsed in WebSocketHandler, 'onTextMessage' method, where the line "String streamId = json.getString(WebSocketConstants.STREAM_ID);" is the one producing the exception because the 'streamIdInUse' message doesn't return a streamId.

### Steps to reproduce
1. Publish to a streamId
2. Meanwhile, try to publish to the same streamId using another device.

### Expected behavior
Parse the message, return the error and finish the connection.

### Actual behavior
Error parsing the message, and connection kept alive.

**Comment by mekya** [comment]
Thank you for the issue. We've moved it to the backlog and schedule it.

**Comment by eneskuluk** [comment]
You can try to change that line to the below one:
```
           if (json.has(WebSocketConstants.STREAM_ID)) {
                streamId = json.getString(WebSocketConstants.STREAM_ID);
            }
```
I think this line should solve your problem.

**Comment by luismacb** [comment]
I already solved it getting into the SDK code. I just wanted to share with you so you can fix it on future versions of the SDK.

**Comment by Madhukaran** [comment]
Is there any way to publish the user with an userName keyword?

**Comment by mekya** [comment]
Hi @Madhukaran ,

Could you please let us know what you would like to do? Maybe we can recommend some solution for you.

**Comment by Madhukaran** [comment]
Hey Hi,
Thanks for your reply tho, Our Team has developing an WebRTC Application. Currently we are using Community Edition of AntMedia and we are planned to scale up to Enterprise as the Application is ready for full fledged.I have some queries!.

1. If we are changing the track or adding a new track to the MediaStream to peer connection we have to Initiate the negotiating process with **offer** & **answer**. I coudn't fire up the **onnegotiationneeded** event. I need a flow how the peers are negotiated with the antMedia. and I didn't get any documentation covered for that part.

2. [Ant WebSocket Refrence](https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Reference)
I have followed the Ant Websocket refrence I need to send an extra key element and receive back with the same key elements. 

For Example,
`
Client inits peer connections, creates offer sdp and send the sdp configuration to the server with takeConfiguration command
{
   command : "takeConfiguration",
   streamId : "stream1",
   type : "offer",  
   sdp : "${SDP_PARAMETER}"
}

Here on the Command I need to emit with an extra key {"userName":"XYZ"}, so that on the receiving on the other client side It would easy to interpret the user Information for my UseCase.
` 

Thanks in Advance!

**Comment by 7994** [comment]
Whenever I initiate a call on one device and accept it on other device, then while accepting it on the 2nd device I'm getting this exception. 


```
2022-01-25 15:52:33.732 32231-32231/com.roundesk.app E/WSChannelRTCClient: sent websocket message:{"command":"publish","streamId":"a3dt3ffdd-wqhuzkfvodpajiletqst-3579","token":"","video":true,"audio":true}
2022-01-25 15:52:33.913 32231-32231/com.roundesk.app E/WSChannelRTCClient: onTextMessage: **{"definition":"streamIdInUse","command":"error"}**
2022-01-25 15:52:33.914 32231-32231/com.roundesk.app E/WSChannelRTCClient: jsonResponse when connected: {"definition":"streamIdInUse","command":"error"}
2022-01-25 15:52:33.914 32231-32231/com.roundesk.app E/ConferenceManager: streamId : null
2022-01-25 15:52:33.918 32231-32231/com.roundesk.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.roundesk.app, PID: 32231
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
        at io.antmedia.webrtcandroidframework.ConferenceManager.streamIdInUse(ConferenceManager.java:205)
        at io.antmedia.webrtcandroidframework.WebSocketHandler.onTextMessage(WebSocketHandler.java:251)
        at de.tavendo.autobahn.WebSocketConnection.handleMessage(WebSocketConnection.java:351)
        at de.tavendo.autobahn.WebSocketConnection.access$1(WebSocketConnection.java:344)
        at de.tavendo.autobahn.WebSocketConnection$ThreadHandler.handleMessage(WebSocketConnection.java:536)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
