### ISSUE TITLE
An error has occured while running

### ISSUE THREAD

**Issue by andrewhamili** [ant-media/Ant-Media-Server#2592]
Hi. While I was starting to execute start.sh on my server, I have encountered an error:

`Bootstrap exception: null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.red5.server.Bootstrap.bootStrap(Bootstrap.java:122)
        at org.red5.server.Bootstrap.main(Bootstrap.java:50)
Caused by: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path: [/home/pi/Downloads/ant-media-server/lib/native]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1043)
        at org.bytedeco.javacpp.Loader.load(Loader.java:935)
        at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.bytedeco.javacpp.Loader.load(Loader.java:994)
        at org.bytedeco.javacpp.Loader.load(Loader.java:935)
        at org.bytedeco.javacpp.avformat.<clinit>(avformat.java:14)
        at org.red5.server.Launcher.launch(Launcher.java:65)
        ... 6 more
Caused by: java.lang.UnsatisfiedLinkError: no avutil in java.library.path: [/home/pi/Downloads/ant-media-server/lib/native]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1021)
        ... 14 more
Bootstrap exit
`

Is this a dependency error or there is a bug on the Application?

**Comment by mekya** [comment]
Hey @andrewhamili ,

Thank you for your comment.  It seems that you're running the Ant Media Server in Raspberry PI or something similar? 

If yes, arm architecture is not supported in Ant Media Server. Fortunately, we have some intentions to support it.

**Comment by andrewhamili** [comment]
@mekya yes, I am running it on a Raspbian buster on Raspbery Pi 4B.

But I also tried it on Ubuntu 16.04.7 with kernel 4.4.0-1112-aws. Same error has occured.

**Comment by mekya** [comment]
You should try it on x86_64 arch.
