### ISSUE TITLE
Support Instant App module in WebRTC Android SDK

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2667]
Some customers are asking for this feature.

**Comment by tonythanh306** [comment]
Look like this issue relate to UDP socket connection

`2020-11-03 15:12:09.900 30028-30513/io.antmedia.webrtc_android_sample_app W/jsep_transport_controller.cc: (line 360): Not adding candidate because the JsepTransport doesn't exist. Ignore it.
2020-11-03 15:12:09.900 30028-30513/io.antmedia.webrtc_android_sample_app I/basic_port_allocator.cc: (line 799): Allocate ports on 4 networks
2020-11-03 15:12:09.904 30028-30547/io.antmedia.webrtc_android_sample_app I/NetworkMonitorAutoDetect: link properties changed: {InterfaceName: wlan0 LinkAddresses: [fe80::824e:70ff:fe95:84ce/64,192.168.1.7/24,2402:800:63b9:ea7e:824e:70ff:fe95:84ce/64,2402:800:63b9:ea7e:7cc8:786d:6549:2301/64,]  Routes: [fe80::/64 -> :: wlan0,::/0 -> fe80::1 wlan0,2402:800:63b9:ea7e::/64 -> :: wlan0,192.168.1.0/24 -> 0.0.0.0 wlan0,0.0.0.0/0 -> 192.168.1.1 wlan0,] DnsAddresses: [2402:800:20ff:6666::1,2402:800:20ff:8888::1,203.113.188.1,203.113.131.3,] Domains: null MTU: 0 TcpBufferSizes: 524288,1048576,1048576,524288,1048576,4194240}
2020-11-03 15:12:09.905 30028-30513/io.antmedia.webrtc_android_sample_app E/basic_packet_socket_factory.cc: (line 54): UDP bind failed with error 13
2020-11-03 15:12:09.914 30028-30513/io.antmedia.webrtc_android_sample_app E/basic_packet_socket_factory.cc: (line 54): UDP bind failed with error 13
2020-11-03 15:12:09.915 30028-30513/io.antmedia.webrtc_android_sample_app I/chatty: uid=11847(io.antmedia.webrtc_android_sample_app) network_thread identical 1 line
2020-11-03 15:12:09.916 30028-30513/io.antmedia.webrtc_android_sample_app E/basic_packet_socket_factory.cc: (line 54): UDP bind failed with error 13
2020-11-03 15:12:09.916 30028-30513/io.antmedia.webrtc_android_sample_app W/jsep_transport_controller.cc: (line 360): Not adding candidate because the JsepTransport doesn't exist. Ignore it.
2020-11-03 15:12:09.916 30028-30513/io.antmedia.webrtc_android_sample_app I/android_network_monitor.cc: (line 325): Network connected: NetInfo[name wlan0; handle 2770270341854; type 2; address fe80::824e:70ff:fe95:84ce 192.168.1.7 2402:800:63b9:ea7e:824e:70ff:fe95:84ce 2402:800:63b9:ea7e:7cc8:786d:6549:2301]
2020-11-03 15:12:09.916 30028-30513/io.antmedia.webrtc_android_sample_app I/basic_port_allocator.cc: (line 1376): Net[wlan0:2402:800:63b9:x:x:x:x:x/64:Wifi:id=4]: Allocation Phase=Udp
2020-11-03 15:12:09.916 30028-30513/io.antmedia.webrtc_android_sample_app I/port.cc: (line 185): Port[c7029c00::1:0:local:Net[wlan0:2402:800:63b9:x:x:x:x:x/64:Wifi:id=4]]: Port created with network cost 10
2020-11-03 15:12:09.918 30028-30513/io.antmedia.webrtc_android_sample_app E/basic_packet_socket_factory.cc: (line 54): UDP bind failed with error 13
2020-11-03 15:12:09.918 30028-30513/io.antmedia.webrtc_android_sample_app W/stun_port.cc: (line 221): Port[c7029c00::1:0:local:Net[wlan0:2402:800:63b9:x:x:x:x:x/64:Wifi:id=4]]: UDP socket creation failed`

**Comment by SelimEmre** [comment]
Hi @tonythanh306,

Thanks for the details.

**Comment by apinutto** [comment]
Any update for this topic?

**Comment by eneskuluk** [comment]
@apinutto I'm working on this but it seems more related to project developers than our sample application since it requires a bundle. I'll provide more description here soon.

**Comment by eneskuluk** [comment]
Instant app support is needs to be done at the project. Instant app module requires 2 modules in the project and one module is for instant app capability. One has less features, code and the other one is fully featured. There are also limitations about permissions that instant app can get:
* `ACCESS_COARSE_LOCATION`
* `ACCESS_FINE_LOCATION`
* `ACCESS_NETWORK_STATE`
* `BILLING – Deprecated as of Play Billing Library 1.0.`
* `CAMERA`
* `INSTANT_APP_FOREGROUND_SERVICE – Only in Android 8.0 (API level 26) and higher.`
* `INTERNET`
* `READ_PHONE_NUMBERS – Only in Android 8.0 (API level 26) and higher.`
* `RECORD_AUDIO`
* `VIBRATE`
* `WAKE_LOCK`

On the other hand, project needs to be bundled and send to the play store in order to have instant module feature. So, we don't upload our sample application to the play store, so it's quite unnecessary for us since users can't install app bundle directly.

For those who wants to include instant app support with webrtc framework, you can add sample application as module besides your main application.

There are various requirements for that. You need to modify manifest file and add additional lines to manifest file.

Max size of the module needs to be at most 15 mb since it is going to be downloaded.

Sign-in support is required for play store.

You can check here for what is required: https://developer.android.com/topic/google-play-instant/getting-started/instant-enabled-app-bundle

Enes.

**Comment by conio001** [comment]
> Instant app support is needs to be done at the project. Instant app module requires 2 modules in the project and one module is for instant app capability. One has less features, code and the other one is fully featured. There are also limitations about permissions that instant app can get:
> 
> * `ACCESS_COARSE_LOCATION`
> * `ACCESS_FINE_LOCATION`
> * `ACCESS_NETWORK_STATE`
> * `BILLING – Deprecated as of Play Billing Library 1.0.`
> * `CAMERA`
> * `INSTANT_APP_FOREGROUND_SERVICE – Only in Android 8.0 (API level 26) and higher.`
> * `INTERNET`
> * `READ_PHONE_NUMBERS – Only in Android 8.0 (API level 26) and higher.`
> * `RECORD_AUDIO`
> * `VIBRATE`
> * `WAKE_LOCK`
> 
> On the other hand, project needs to be bundled and send to the play store in order to have instant module feature. So, we don't upload our sample application to the play store, so it's quite unnecessary for us since users can't install app bundle directly.
> 
> For those who wants to include instant app support with webrtc framework, you can add sample application as module besides your main application.
> 
> There are various requirements for that. You need to modify manifest file and add additional lines to manifest file.
> 
> Max size of the module needs to be at most 15 mb since it is going to be downloaded.
> 
> Sign-in support is required for play store.
> 
> You can check here for what is required: https://developer.android.com/topic/google-play-instant/getting-started/instant-enabled-app-bundle
> 
> Enes.

Hello, we also have this problem when we use udp in our instant app, have you resolved the problem with this solution? I checked the permissions and the aab output as you said above, but still has the permission problem.
The code below has the permission problem
```
class udpSendThread : Thread() {
            override fun run() {
                try {
                    DatagramSocket()
                } catch (e: Exception) {
                    // TODO Auto-generated catch block
                    e.printStackTrace()
                }
            }
        }

        udpSendThread().start()
```
the manifest is below:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:dist="http://schemas.android.com/apk/distribution"
    package="com.ejoy.ejoysdk_demo"
    platformBuildVersionCode="7"
    platformBuildVersionName="7.0"
    android:compileSdkVersion="28"
    android:compileSdkVersionCodename="9"
    android:targetSandboxVersion="1"
    android:versionCode="7"
    android:versionName="7.0" >

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="29" />

    <dist:module dist:instant="true" >
    </dist:module>

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
        android:allowBackup="true"
        android:appComponentFactory="androidx.core.app.CoreComponentFactory"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme" >
        <meta-data
            android:name="com.google.android.gms.instant.flavor"
            android:value="1337" />

        <activity android:name="com.google.android.instantapps.samples.instantenabledandroidappbundle.MainActivity" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

```

error log :
```
2021-06-09 00:00:18.882 13959-13983/? W/System.err: java.net.BindException: bind failed: EACCES (Permission denied)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at libcore.io.IoBridge.bind(IoBridge.java:108)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at java.net.PlainDatagramSocketImpl.bind0(PlainDatagramSocketImpl.java:104)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:112)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at java.net.DatagramSocket.bind(DatagramSocket.java:412)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at java.net.DatagramSocket.<init>(DatagramSocket.java:262)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at java.net.DatagramSocket.<init>(DatagramSocket.java:216)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at com.google.android.instantapps.samples.instantenabledandroidappbundle.MainActivity$onCreate$udpSendThread.run(MainActivity.kt:48)
2021-06-09 00:00:18.883 13959-13983/? W/System.err: Caused by: android.system.ErrnoException: bind failed: EACCES (Permission denied)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at libcore.io.Linux.bind(Native Method)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at libcore.io.ForwardingOs.bind(ForwardingOs.java:74)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at libcore.io.ForwardingOs.bind(ForwardingOs.java:74)
2021-06-09 00:00:18.883 13959-13983/? W/System.err:     at libcore.io.IoBridge.bind(IoBridge.java:104)
2021-06-09 00:00:18.883 13959-13983/? W/System.err: 	... 6 more
```

but when I change the output from aab to normal installable apk, it all runs well.

**Comment by eneskuluk** [comment]
Hi @conio001,
If you are trying with a port number lower than 1024, can you try higher than 1024 please? As an example, if you are trying to bind 80, try binding 8080. Lower than port number 1024 is only can be assigned by apps with superuser privilege in Linux.

**Comment by mlaux** [comment]
I looked into this as well. To my knowledge, instant apps can't use UDP sockets at all, because Google can't *know* you're using encryption, even if you are. Unfortunately I can't see them ever changing their mind on this...

Now-deleted issue: https://issuetracker.google.com/issues/191070661

> Status: Won't Fix (Intended Behavior) Instant apps are required to protect all network traffic using encryption via something like TLS/HTTP: https://support.google.com/googleplay/android-developer/answer/9900182
> As a result instant apps are not allowed to directly bind sockets (TCP or UDP, enforced via selinux config) because an encryption cannot be verified/enforced. There is no solution at this time for utilizing UDP. A workaround would have to involve utilizing a connection based alternative (ie HTTPS).

Related SO post: https://stackoverflow.com/questions/67890898/avc-denied-error-creating-datagramsocket-for-android-instant-app
