### ISSUE TITLE
APR issue on Ubuntu 18.04. " requires the APR/native library which is not available"

### ISSUE THREAD

**Issue by danrossi** [ant-media/Ant-Media-Server#2818]
Installed correctly via the shell script. Installed SSL correctly via the SSL enable script. The connectors fail to load because of this error. No information out there about this I've installed the tomcat native package and still nothing. The shared libraries are in the native directory. Not sure which is the SSL one. 

```
INFO: The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/local/antmedia/lib/native]
2020-12-25 12:55:29,506 [main] org.apache.catalina.core.AprLifecycleListener - The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/local/antmedia/lib/native]
Dec 25, 2020 12:55:29 PM org.apache.catalina.core.StandardService initInternal
```

```
2020-12-25 12:55:29,536 [main] org.apache.catalina.core.StandardService - Failed to initialize connector [Connector[HTTP/1.1-5443]]
org.apache.catalina.LifecycleException: The configured protocol [org.apache.coyote.http11.Http11AprProtocol] requires the APR/native library which is not available
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:1060)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:552)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:848)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:440)
        at org.red5.server.tomcat.TomcatLoader.start(TomcatLoader.java:454)
 ```

**Comment by danrossi** [comment]
I had to install apr and tomcat native as ubuntu packages then change the library path to this. Shipped library fails. 

 LD_LIBRARY_PATH=$RED5_HOME/lib/native:/usr/lib/x86_64-linux-gnu

**Comment by mekya** [comment]
By default, we uses fresh ubuntu 18.04 for our CI tests in travis.

Do you install the server as instructed in the documentation?
