### ISSUE TITLE
Cant upload VoD - error 

### ISSUE THREAD

**Issue by KH-zzzs** [ant-media/Ant-Media-Server#2845]
Hi, 

we can not upload video to VoD -> WebRTCApp. 

Using: 
- Ubuntu Linux 18.04 
- AntMedia version: Enterprise Edition 2.2.1 20201029_2042 

Behavior: 
When uploading video to VoD, nothing happens. 
Try to upload 1,5 MB test video and that was uploaded... but when trying to upload video bigger than 10MB nothing happens. 
Bellow is error log. 
 
Error log: 
Dec 30, 2020 2:51:54 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-worker-thread-13,5,main]=Thread[vert.x-worker-thread-13,5,main] has been blocked for 2553 ms, time limit is 2000 ms
Dec 30, 2020 2:51:55 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-worker-thread-13,5,main]=Thread[vert.x-worker-thread-13,5,main] has been blocked for 3553 ms, time limit is 2000 ms
Dec 30, 2020 3:31:55 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-worker-thread-1,5,main]=Thread[vert.x-worker-thread-1,5,main] has been blocked for 2883 ms, time limit is 2000 ms
Dec 30, 2020 3:31:56 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-worker-thread-1,5,main]=Thread[vert.x-worker-thread-1,5,main] has been blocked for 3883 ms, time limit is 2000 ms
Dec 30, 2020 3:36:55 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-worker-thread-2,5,main]=Thread[vert.x-worker-thread-2,5,main] has been blocked for 2924 ms, time limit is 2000 ms
Dec 30, 2020 3:36:56 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-worker-thread-2,5,main]=Thread[vert.x-worker-thread-2,5,main] has been blocked for 3924 ms, time limit is 2000 ms
Dec 30, 2020 3:36:57 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-worker-thread-2,5,main]=Thread[vert.x-worker-thread-2,5,main] has been blocked for 4924 ms, time limit is 2000 ms
Dec 30, 2020 8:09:45 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030xcf2V0xa0&'0x84D(0x910x1d0xa7J0xe2A0x810x830x17P0x880xce0x89qC0xf50xa20x8a0xb70x10e0x940x07]. HTTP method names must be tokens
at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:427)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:503)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1620)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1082)
at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:565)
at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:543)
at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:834)

Please help, best regards.

**Comment by mhuisken** [comment]
I have the same issue. Recently moved to version 2.2.1 and now not able to upload files for VoD. Any ideas what could be the issue?

**Comment by broundtree** [comment]
Having same issue. Can upload VoD by HTTP only

**Comment by strelok899** [comment]
have the same issue fresh install ubuntu 18.04

**Comment by KH-zzzs** [comment]
@AntMedia, when new version is expected to realease??

**Comment by mekya** [comment]
Hi @KH-zzzs , we've fixed this issue and fix is available on v2.3 Release Candidate. 

Please check it out if it's working for you.

**Comment by liz2021** [comment]
Can someone help me?
I'm not sure what's the max size of a file to upload as a vod for live stream in loop with ant meadia. Some of my files goes right the way, others I wait for ever and never go, I've different large files, but don't know how large they can be you know...anyone?

**Comment by mekya** [comment]
I've added this issue to the backlog to ask one to help you. 

Thank you @KH-zzzs

**Comment by Mohit-3196** [comment]
Hi @KH-zzzs @liz2021 ,
How are you all?

There's no limit as such for the size of VoDs to be uploaded on the Ant Media Server.
Moreover while uploading the VoDs, you can also track the upload status with the help of a progress bar for AMS v2.5.3 and above #4313 

If you are using an older version of AMS, I would recommend you update to the latest version.
If you have any questions or are facing any issues, please let me know.

Thank you

**Comment by liz2021** [comment]
I see, but when I have a large file it doesn’t upload. Would you send me the link of the latest version? I’m not sure if I’m using the latest one, I’m new to this…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mohit-3196** [comment]
Hi @liz2021 ,
How are you?

Did you have any chance to test this?

Thank you

**Comment by mekya** [comment]
Closing this issue for inactivity. 
Please feel to reopen it if it does not work for you

**Comment by Yalchin403** [comment]
In my case, it didn't work when I started to use my domain. I forgot to include `client_max_body_size`, set it accordingly, and hopefully it will resolve as I see that it is now resolved in my case. Also after setting it, don't forget to restart the nginx.
