### ISSUE TITLE
Customer Report - Android SDK Crash at Samsung J7

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#2883]
Using Android SDK in the Samsung Galaxy J7 2016 (Model no- SM-J710FN) and the android version is Oreo(8.1.0) 

It crashes most of the time during its use. 

Please check!

Error logs

Error Logs

2021-01-15 21:46:00.097 17252-17802/com.pandojo E/System: java.io.FileNotFoundException: File doesn't exist: /data/app/com.pandojo-AYSYkZhqjIUGxm9S4P53Ig==/base.apk
        at java.util.zip.ZipFile.<init>(ZipFile.java:212)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:160)
        at java.util.jar.JarFile.<init>(JarFile.java:97)
        at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
        at dalvik.system.DexPathList$NativeLibraryElement.maybeInit(DexPathList.java:761)
        at dalvik.system.DexPathList$NativeLibraryElement.findNativeLibrary(DexPathList.java:782)
        at dalvik.system.DexPathList.findLibrary(DexPathList.java:528)
        at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:154)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1005)
        at java.lang.System.loadLibrary(System.java:1657)
        at org.webrtc.NativeLibrary$DefaultLoader.load(NativeLibrary.java:21)
        at org.webrtc.NativeLibrary.initialize(NativeLibrary.java:44)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:292)
        at io.antmedia.webrtcandroidframework.apprtc.PeerConnectionClient.lambda$new$2(PeerConnectionClient.java:421)
        at io.antmedia.webrtcandroidframework.apprtc.-$$Lambda$PeerConnectionClient$BsOejwlOA-_yVOw0UUyQCVMO0yQ.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2021-01-15 21:46:00.099 17252-17802/com.pandojo E/org.webrtc.Logging: NativeLibrary: Failed to load native library: jingle_peerconnection_so
2021-01-15 21:46:00.099 17252-17802/com.pandojo E/org.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pandojo-AYSYkZhqjIUGxm9S4P53Ig==/base.apk"],nativeLibraryDirectories=[/data/app/com.pandojo-AYSYkZhqjIUGxm9S4P53Ig==/lib/arm, /data/app/com.pandojo-AYSYkZhqjIUGxm9S4P53Ig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libjingle_peerconnection_so.so"
2021-01-15 21:46:00.101 17252-17802/com.pandojo E/org.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pandojo-AYSYkZhqjIUGxm9S4P53Ig==/base.apk"],nativeLibraryDirectories=[/data/app/com.pandojo-AYSYkZhqjIUGxm9S4P53Ig==/lib/arm, /data/app/com.pandojo-AYSYkZhqjIUGxm9S4P53Ig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libjingle_peerconnection_so.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at org.webrtc.NativeLibrary$DefaultLoader.load(NativeLibrary.java:21)
        at org.webrtc.NativeLibrary.initialize(NativeLibrary.java:44)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:292)
        at io.antmedia.webrtcandroidframework.apprtc.PeerConnectionClient.lambda$new$2(PeerConnectionClient.java:421)
        at io.antmedia.webrtcandroidframework.apprtc.-$$Lambda$PeerConnectionClient$BsOejwlOA-_yVOw0UUyQCVMO0yQ.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2021-01-15 21:46:00.101 17252-17802/com.pandojo E/zygote: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
2021-01-15 21:46:00.103 17252-17805/com.pandojo W/PCRTCClient: External OpenSLES ADM not implemented yet.
2021-01-15 21:46:00.104 17252-17802/com.pandojo E/AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
    Process: com.pandojo, PID: 17252
    java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
        at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:293)
        at io.antmedia.webrtcandroidframework.apprtc.PeerConnectionClient.lambda$new$2(PeerConnectionClient.java:421)
        at io.antmedia.webrtcandroidframework.apprtc.-$$Lambda$PeerConnectionClient$BsOejwlOA-_yVOw0UUyQCVMO0yQ.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by SelimEmre** [comment]
Hi @akiziltoprak,

It gives an error because SDK couldn't find `libjingle_peerconnection_so` file. Could you please make sure these files are in SDK? This file should be under the `webrtc-android-framework`/`src`/`main` folder.

**Comment by hard1k9850** [comment]
Hi @akiziltoprak 
were you able to solve the problem?

**Comment by akiziltoprak** [comment]
have you tried the suggestion provided earlier? 

"It gives an error because SDK couldn't find libjingle_peerconnection_so file. Could you please make sure these files are in SDK? This file should be under the webrtc-android-framework/src/main folder."

**Comment by jantekb** [comment]
Closing due to no activity
