### ISSUE TITLE
Error with specific stream source

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3029]
### Short description
When I added `https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8` source as Stream Source, I'm facing a fatal error.

### Environment
* Ant Media Server version: AMS 2.3

### Steps to reproduce
1.  Add 2 adaptive options(240p and 360p)
2. Add `https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8` as a Stream Source.

### Expected behavior
I'm expecting to play properly

### Actual behavior
I saw a fatal exception.

### Logs
```
2021-03-05 11:56:21,858 [Thread-23] INFO  i.a.streamsource.StreamFetcher - StartStream called, new thread is started for 896430979965387985853607
2021-03-05 11:56:21,859 [Thread-24] INFO  i.a.streamsource.StreamFetcher - Preparing the StreamFetcher for https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
2021-03-05 11:56:23,107 [Thread-24] INFO  io.antmedia.muxer.MuxAdaptor - vertx exist io.vertx.core.impl.VertxImpl@54ebfbe
2021-03-05 11:56:23,107 [Thread-24] INFO  io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for 896430979965387985853607
2021-03-05 11:56:23,108 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2021-03-05 11:56:23,108 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - ServerSettings exist io.antmedia.settings.ServerSettings@12d0cd65
2021-03-05 11:56:23,108 [Thread-24] INFO  i.a.streamsource.StreamFetcher - 896430979965387985853607 stream count in stream https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8 is 7
2021-03-05 11:56:23,108 [Thread-24] INFO  io.antmedia.muxer.MuxAdaptor - Audio format sample rate:48000 bitrate:148500 for stream: 896430979965387985853607
2021-03-05 11:56:23,108 [Thread-24] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:320 height:180 for stream: 896430979965387985853607
2021-03-05 11:56:23,108 [Thread-24] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:480 height:270 for stream: 896430979965387985853607
2021-03-05 11:56:23,109 [Thread-24] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:640 height:360 for stream: 896430979965387985853607
2021-03-05 11:56:23,109 [Thread-24] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:960 height:540 for stream: 896430979965387985853607
2021-03-05 11:56:23,109 [Thread-24] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:1280 height:720 for stream: 896430979965387985853607
2021-03-05 11:56:23,109 [Thread-24] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:1920 height:1080 for stream: 896430979965387985853607
2021-03-05 11:56:23,109 [Thread-24] INFO  i.a.e.adaptive.base.AudioDecoder - audio decoder name:  aac for 896430979965387985853607 sample rate:48000
2021-03-05 11:56:23,110 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - find decoder for stream: 896430979965387985853607
2021-03-05 11:56:23,111 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - video decoder name:  h264 for 896430979965387985853607  video context timebase:0/2
2021-03-05 11:56:23,111 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - find decoder for stream: 896430979965387985853607
2021-03-05 11:56:23,112 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - video decoder name:  h264 for 896430979965387985853607  video context timebase:0/2
2021-03-05 11:56:23,112 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - find decoder for stream: 896430979965387985853607
2021-03-05 11:56:23,113 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - video decoder name:  h264 for 896430979965387985853607  video context timebase:0/2
2021-03-05 11:56:23,113 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - find decoder for stream: 896430979965387985853607
2021-03-05 11:56:23,114 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - video decoder name:  h264 for 896430979965387985853607  video context timebase:0/2
2021-03-05 11:56:23,114 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - find decoder for stream: 896430979965387985853607
2021-03-05 11:56:23,115 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - video decoder name:  h264 for 896430979965387985853607  video context timebase:0/2
2021-03-05 11:56:23,115 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - find decoder for stream: 896430979965387985853607
2021-03-05 11:56:23,116 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - video decoder name:  h264 for 896430979965387985853607  video context timebase:0/2
2021-03-05 11:56:23,124 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2021-03-05 11:56:23,125 [Thread-24] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor scheduled job id 47 stream adaptor:1155039903 for stream:896430979965387985853607
2021-03-05 11:56:23,125 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2021-03-05 11:56:23,125 [Thread-24] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor scheduled job id 48 stream adaptor:64790617 for stream:896430979965387985853607
2021-03-05 11:56:23,126 [Thread-24] INFO  i.a.e.adaptive.EncoderAdaptor - Object detection is NOT enabled for stream:896430979965387985853607
2021-03-05 11:56:23,126 [Thread-24] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor scheduled job id 49 stream adaptor:1634161087 for stream:896430979965387985853607
2021-03-05 11:56:23,126 [Thread-24] INFO  i.a.e.adaptive.audio.OpusEncoder - encoder name libopus source sample rate 48000, channel layout 3
2021-03-05 11:56:23,126 [Thread-24] INFO  i.a.e.adaptive.audio.AACEncoder - name : aac
2021-03-05 11:56:23,128 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - copy codec parameter from context 0 stream index: 0
2021-03-05 11:56:23,129 [Thread-24] INFO  i.a.e.adaptive.audio.OpusEncoder - encoder name libopus source sample rate 48000, channel layout 3
2021-03-05 11:56:23,129 [Thread-24] INFO  i.a.e.adaptive.audio.AACEncoder - name : aac
2021-03-05 11:56:23,130 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - copy codec parameter from context 0 stream index: 0
2021-03-05 11:56:23,130 [Thread-24] INFO  i.a.e.adaptive.video.H264Encoder - incoming widthxheight:1920x1080
2021-03-05 11:56:23,130 [Thread-24] INFO  i.a.e.adaptive.video.H264Encoder - finding encoder for stream:896430979965387985853607 width/height:416/234 timebase:1/20 sampleAspectRatio:1/1 gopSize:40 bitrate:500000
2021-03-05 11:56:23,136 [Thread-24] INFO  i.a.e.adaptive.video.H264Encoder - Video codec opened. Context gop size: 40  keyint mint -1 extradata size: 35 video codec timebase: 1/20  codecName: libx264 for stream: 896430979965387985853607
2021-03-05 11:56:23,136 [Thread-24] INFO  i.a.e.adaptive.video.H264Encoder - encoder name: libx264 for stream:896430979965387985853607
2021-03-05 11:56:23,137 [Thread-24] INFO  i.a.enterprise.webrtc.WebRTCMuxer - extra data 0: 0  extra data 1: 0, 2:0, 3:1, 4:103
2021-03-05 11:56:23,137 [Thread-24] INFO  i.a.e.adaptive.video.H264Encoder - incoming widthxheight:1920x1080
2021-03-05 11:56:23,137 [Thread-24] INFO  i.a.e.adaptive.video.H264Encoder - finding encoder for stream:896430979965387985853607 width/height:640/360 timebase:1/20 sampleAspectRatio:1/1 gopSize:40 bitrate:800000
2021-03-05 11:56:23,143 [Thread-24] INFO  i.a.e.adaptive.video.H264Encoder - Video codec opened. Context gop size: 40  keyint mint -1 extradata size: 37 video codec timebase: 1/20  codecName: libx264 for stream: 896430979965387985853607
2021-03-05 11:56:23,143 [Thread-24] INFO  i.a.e.adaptive.video.H264Encoder - encoder name: libx264 for stream:896430979965387985853607
2021-03-05 11:56:23,144 [Thread-24] INFO  i.a.enterprise.webrtc.WebRTCMuxer - extra data 0: 0  extra data 1: 0, 2:0, 3:1, 4:103
2021-03-05 11:56:23,143 [Thread-24] INFO  i.a.e.adaptive.video.H264Encoder - encoder name: libx264 for stream:896430979965387985853607
2021-03-05 11:56:23,144 [Thread-24] INFO  i.a.enterprise.webrtc.WebRTCMuxer - extra data 0: 0  extra data 1: 0, 2:0, 3:1, 4:103
2021-03-05 11:56:23,144 [Thread-24] INFO  i.a.enterprise.preview.PngEncoder - preparing codec for stream: 896430979965387985853607 source wxh:1920x1080 target wxh:854x480
2021-03-05 11:56:23,144 [Thread-24] INFO  i.a.enterprise.preview.PngEncoder - leaving prepare codec for stream: 896430979965387985853607
2021-03-05 11:56:23,145 [Thread-24] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - registering 896430979965387985853607 muxer with 234p and codec::H264 to webrtc adaptor
2021-03-05 11:56:23,145 [Thread-24] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Increasing number of live streams: 1 and stream id:896430979965387985853607
2021-03-05 11:56:23,145 [Thread-24] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - registering 896430979965387985853607 muxer with 360p and codec::H264 to webrtc adaptor
2021-03-05 11:56:23,146 [Thread-24] INFO  i.a.AntMediaApplicationAdapter - start publish leaved
2021-03-05 11:56:23,152 [vert.x-eventloop-thread-6] INFO  i.a.AntMediaApplicationAdapter - update source quality for stream: 896430979965387985853607 quality:null speed:0.0
2021-03-05 11:56:23,160 [vert.x-worker-thread-8] INFO  i.a.AntMediaApplicationAdapter -  Status of stream 896430979965387985853607 is set to Broadcasting with result: true
2021-03-05 11:56:23,172 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - cannot write video frame to muxer. Error: Invalid argument^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ stream: 896430979965387985853607.m3u8
2021-03-05 11:56:23,182 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - cannot write video frame to muxer. Error: Invalid argument^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ stream: 896430979965387985853607.m3u8
2021-03-05 11:56:23,200 [vert.x-worker-thread-11] ERROR i.a.e.adaptive.StreamAdaptor - java.lang.NullPointerException
        at io.antmedia.muxer.HLSMuxer.writePacket(HLSMuxer.java:397)
        at io.antmedia.enterprise.adaptive.video.H264Encoder.writeFrameInternal(H264Encoder.java:186)
        at io.antmedia.enterprise.adaptive.base.VideoEncoder.writeFrame(VideoEncoder.java:242)
        at io.antmedia.enterprise.adaptive.StreamAdaptor.write2VideoEncoders(StreamAdaptor.java:322)
        at io.antmedia.enterprise.adaptive.StreamAdaptor.execute(StreamAdaptor.java:232)
        at io.antmedia.enterprise.adaptive.StreamAdaptor.lambda$start$0(StreamAdaptor.java:185)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

2021-03-05 11:56:23,204 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - cannot write video frame to muxer. Error: Invalid argument^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ stream: 896430979965387985853607.m3u8
2021-03-05 11:56:23,213 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - cannot write video frame to muxer. Error: Invalid argument^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ stream: 896430979965387985853607.m3u8
2021-03-05 11:56:23,221 [Thread-24] INFO  io.antmedia.muxer.HLSMuxer - cannot write video frame to muxer. Error: Invalid argument^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ stream: 896430979965387985853607.m3u8
2021-03-05 11:56:24,389 [main] INFO  org.red5.server.Launcher - Ant Media Server Enterprise 2.3.0
2021-03-05 11:56:24,391 [main] INFO  org.red5.server.Launcher -
 ```
[hs_err_pid48891.log](https://github.com/ant-media/Ant-Media-Server/files/6090431/hs_err_pid48891.log)

**Comment by jantekb** [comment]
Closed due to no activity
