### ISSUE TITLE
"String index out of range: -13" 500 error on HLS adaptive file for new stream application "live_dev"

### ISSUE THREAD

**Issue by benbowler** [ant-media/Ant-Media-Server#3097]
### Short description

I created a new application, following the instructions, called `live_dev`. I copied the settings from the `live` app including multibitrate HLS. However for the `live_dev` app the adaptive HLS m3u8 file returns the following error:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -13
```

<img width="1439" alt="Screenshot 2021-03-25 at 15 48 42" src="https://user-images.githubusercontent.com/119352/112502761-3fc3e600-8d82-11eb-9539-662086eba066.png">

I managed to work around this by creating a new application called `liveLocal` which works, I don't know if there is some code that relies on splitting via _ which could mean underscores in the application name should not be allowed.

### Environment

* Operating system and version: AWS Marketplace Edition
* Java version: 
* Ant Media Server version: Enterprise Edition 2.2.1 20201029_2042
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

```
undefined5443-exec-10] ERROR o.a.c.c.C.[.[.0.0.0.[.[default] - Servlet.service() for servlet [default] in context with path [/live_dev] threw exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -13
	at java.base/java.lang.String.substring(String.java:1841)
	at io.antmedia.filter.TokenFilterManager.getStreamId(TokenFilterManager.java:148)
	at io.antmedia.filter.TokenFilterManager.doFilter(TokenFilterManager.java:43)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http2.StreamProcessor.service(StreamProcessor.java:358)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:70)
	at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-25 15:51:10,293 [https-openssl-apr-0.0.0.0-5443-exec-9] ERROR o.a.c.c.C.[.[.0.0.0.[.[default] - Servlet.service() for servlet [default] in context with path [/live_dev] threw exception
```

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
hi @benbowler ,

It seems that you enable some kind of tokens but you don't give any token parameter to the request. 

I see that even in this scenario, server should not return this exception
