### ISSUE TITLE
Specific RTSP source error in HIK Media Server v4.30.010

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3189]
### Short description
One of our users reported this issue. When we add stream as an RTSP Source, AMS couldn't achieve to start it.

### Environment
* Ant Media Server version: v2.3.2

### Steps to reproduce
1. Add RTSP Source as an according to these encoder settings.

### Expected behavior
It should work.

### Actual behavior
It couldn't work.

### Logs

![ikyS2KgujVzIdzbO6oPMgX68I6_CdPDIOQ](https://user-images.githubusercontent.com/9084130/115695175-379f9c00-a36a-11eb-844a-7faea12d8268.png)

```
(base) mypc@mypc:~$ ffprobe rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
ffprobe version 4.3.1-8ubuntu1~18.04.sav0 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='8ubuntu1~18.04.sav0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-crystalhd --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x5619e85809c0] UDP timeout, retrying with TCP
[rtsp @ 0x5619e85809c0] method SETUP failed: 454 Session Not Found
[rtsp @ 0x5619e85809c0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[rtsp @ 0x5619e85809c0] Could not find codec parameters for stream 1 (Audio: none, 16000 Hz, 1 channels): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z':
  Metadata:
    title           : HIK Media Server V4.30.010
    comment         : HIK Media Server Session Description : standard
  Duration: -26297:-1:-11.-93, start: 94669271.939867, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: none, 16000 Hz, 1 channels
Unsupported codec with id 0 for input stream 1
(base) mypc@mypc:~$
```

```
2021-04-22 08:46:37,670 [Thread-921] INFO  i.a.streamsource.StreamFetcher - StartStream called, new thread is started for 178285984604366494481624
2021-04-22 08:46:37,670 [Thread-922] INFO  i.a.streamsource.StreamFetcher - Preparing the StreamFetcher for rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
2021-04-22 08:46:37,671 [Thread-922] INFO  i.a.streamsource.StreamFetcher - Setting rtsp transport type to tcp for stream source: rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
2021-04-22 08:46:42,552 [vert.x-eventloop-thread-6] WARN  i.a.s.StreamFetcherManager - Mux adaptor is not initialized for stream fetcher with stream id: 178285984604366494481624 It's likely that stream fetching is not started yet
2021-04-22 08:46:44,839 [Thread-922] INFO  io.antmedia.muxer.MuxAdaptor - vertx exist io.vertx.core.impl.VertxImpl@dc3d088
2021-04-22 08:46:44,840 [Thread-922] INFO  io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for 178285984604366494481624
2021-04-22 08:46:44,840 [Thread-922] INFO  io.antmedia.muxer.MuxAdaptor - adding DASH Muxer for 178285984604366494481624
2021-04-22 08:46:44,841 [Thread-922] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2021-04-22 08:46:44,842 [Thread-922] INFO  i.a.enterprise.muxer.DASHMuxer - DASH Segment Duration: 6, Fragment Duration: 0.5
2021-04-22 08:46:44,842 [Thread-922] INFO  i.a.e.adaptive.EncoderAdaptor - ServerSettings exist io.antmedia.settings.ServerSettings@19648e12
2021-04-22 08:46:44,842 [Thread-922] INFO  i.a.streamsource.StreamFetcher - 178285984604366494481624 stream count in stream rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z is 2
2021-04-22 08:46:44,842 [Thread-922] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:1920 height:1080 for stream: 178285984604366494481624 source index:0 target index:0
2021-04-22 08:46:44,842 [Thread-922] INFO  i.a.enterprise.muxer.DASHMuxer - addStream with parameters and stream index:0 
2021-04-22 08:46:44,842 [Thread-922] INFO  io.antmedia.muxer.MuxAdaptor - Audio format sample rate:16000 bitrate:0 for stream: 178285984604366494481624 source index:1 target index:1
2021-04-22 08:46:44,842 [Thread-922] WARN  io.antmedia.muxer.MuxAdaptor - addStream returns false hls for stream: 178285984604366494481624
2021-04-22 08:46:44,843 [Thread-922] WARN  io.antmedia.muxer.MuxAdaptor - addStream returns false dash for stream: 178285984604366494481624
2021-04-22 08:46:44,843 [Thread-922] INFO  i.a.e.adaptive.EncoderAdaptor - not decoding video for stream: 178285984604366494481624
2021-04-22 08:46:44,843 [Thread-922] ERROR i.a.streamsource.StreamFetcher - java.lang.IllegalArgumentException: avcodec_find_decoder() error: Unsupported video format or codec not found: 0.
	at io.antmedia.enterprise.adaptive.base.AudioDecoder.prepareAudioDecoder(AudioDecoder.java:34)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareDecoders(EncoderAdaptor.java:402)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareInternal(EncoderAdaptor.java:311)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareFromInputFormatContext(EncoderAdaptor.java:340)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:272)

2021-04-22 08:46:44,844 [Thread-922] INFO  i.a.streamsource.StreamFetcher - write all buffered packets for stream: 178285984604366494481624
2021-04-22 08:46:44,844 [Thread-922] INFO  i.a.streamsource.StreamFetcher - Writing trailer in Muxadaptor 178285984604366494481624
2021-04-22 08:46:44,844 [Thread-922] INFO  i.a.e.adaptive.EncoderAdaptor - closing input and number of dropped packets 0
2021-04-22 08:46:44,844 [Thread-922] INFO  i.a.e.adaptive.EncoderAdaptor - Total video encode time 0ms, average video encode time 0ms total audio encode time 0ms total video decode time 0ms , average video decode time 0 ms 
2021-04-22 08:46:44,844 [Thread-922] INFO  i.a.streamsource.StreamFetcher - Stream fetcher will try to fetch source rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z after 3000 ms
2021-04-22 08:46:47,849 [Thread-923] INFO  i.a.streamsource.StreamFetcher - Preparing the StreamFetcher for rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
2021-04-22 08:46:47,849 [Thread-923] INFO  i.a.streamsource.StreamFetcher - Setting rtsp transport type to tcp for stream source: rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
2021-04-22 08:46:52,551 [vert.x-eventloop-thread-6] WARN  i.a.s.StreamFetcherManager - Mux adaptor is not initialized for stream fetcher with stream id: 178285984604366494481624 It's likely that stream fetching is not started yet
2021-04-22 08:46:54,887 [Thread-923] INFO  io.antmedia.muxer.MuxAdaptor - vertx exist io.vertx.core.impl.VertxImpl@dc3d088
2021-04-22 08:46:54,887 [Thread-923] INFO  io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for 178285984604366494481624
2021-04-22 08:46:54,887 [Thread-923] INFO  io.antmedia.muxer.MuxAdaptor - adding DASH Muxer for 178285984604366494481624
2021-04-22 08:46:54,888 [Thread-923] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2021-04-22 08:46:54,889 [Thread-923] INFO  i.a.enterprise.muxer.DASHMuxer - DASH Segment Duration: 6, Fragment Duration: 0.5
2021-04-22 08:46:54,889 [Thread-923] INFO  i.a.e.adaptive.EncoderAdaptor - ServerSettings exist io.antmedia.settings.ServerSettings@19648e12
2021-04-22 08:46:54,889 [Thread-923] INFO  i.a.streamsource.StreamFetcher - 178285984604366494481624 stream count in stream rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z is 2
2021-04-22 08:46:54,890 [Thread-923] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:1920 height:1080 for stream: 178285984604366494481624 source index:0 target index:0
2021-04-22 08:46:54,890 [Thread-923] INFO  i.a.enterprise.muxer.DASHMuxer - addStream with parameters and stream index:0 
2021-04-22 08:46:54,890 [Thread-923] INFO  io.antmedia.muxer.MuxAdaptor - Audio format sample rate:16000 bitrate:0 for stream: 178285984604366494481624 source index:1 target index:1
2021-04-22 08:46:54,890 [Thread-923] WARN  io.antmedia.muxer.MuxAdaptor - addStream returns false hls for stream: 178285984604366494481624
2021-04-22 08:46:54,890 [Thread-923] WARN  io.antmedia.muxer.MuxAdaptor - addStream returns false dash for stream: 178285984604366494481624
2021-04-22 08:46:54,890 [Thread-923] INFO  i.a.e.adaptive.EncoderAdaptor - not decoding video for stream: 178285984604366494481624
2021-04-22 08:46:54,890 [Thread-923] ERROR i.a.streamsource.StreamFetcher - java.lang.IllegalArgumentException: avcodec_find_decoder() error: Unsupported video format or codec not found: 0.
	at io.antmedia.enterprise.adaptive.base.AudioDecoder.prepareAudioDecoder(AudioDecoder.java:34)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareDecoders(EncoderAdaptor.java:402)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareInternal(EncoderAdaptor.java:311)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareFromInputFormatContext(EncoderAdaptor.java:340)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:272)

2021-04-22 08:46:54,891 [Thread-923] INFO  i.a.streamsource.StreamFetcher - write all buffered packets for stream: 178285984604366494481624
2021-04-22 08:46:54,891 [Thread-923] INFO  i.a.streamsource.StreamFetcher - Writing trailer in Muxadaptor 178285984604366494481624
2021-04-22 08:46:54,891 [Thread-923] INFO  i.a.e.adaptive.EncoderAdaptor - closing input and number of dropped packets 0
2021-04-22 08:46:54,891 [Thread-923] INFO  i.a.e.adaptive.EncoderAdaptor - Total video encode time 0ms, average video encode time 0ms total audio encode time 0ms total video decode time 0ms , average video decode time 0 ms 
2021-04-22 08:46:54,892 [Thread-923] INFO  i.a.streamsource.StreamFetcher - Stream fetcher will try to fetch source rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z after 3000 ms
2021-04-22 08:46:55,520 [https-openssl-nio2-0.0.0.0-5443-exec-5] INFO  io.antmedia.rest.RestServiceBase - Version Name 2.3.2 Version Type Enterprise Edition
2021-04-22 08:46:57,897 [Thread-924] INFO  i.a.streamsource.StreamFetcher - Preparing the StreamFetcher for rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
2021-04-22 08:46:57,897 [Thread-924] INFO  i.a.streamsource.StreamFetcher - Setting rtsp transport type to tcp for stream source: rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
2021-04-22 08:47:02,551 [vert.x-eventloop-thread-6] WARN  i.a.s.StreamFetcherManager - Mux adaptor is not initialized for stream fetcher with stream id: 178285984604366494481624 It's likely that stream fetching is not started yet
2021-04-22 08:47:04,998 [Thread-924] INFO  io.antmedia.muxer.MuxAdaptor - vertx exist io.vertx.core.impl.VertxImpl@dc3d088
2021-04-22 08:47:04,999 [Thread-924] INFO  io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for 178285984604366494481624
2021-04-22 08:47:04,999 [Thread-924] INFO  io.antmedia.muxer.MuxAdaptor - adding DASH Muxer for 178285984604366494481624
2021-04-22 08:47:05,000 [Thread-924] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2021-04-22 08:47:05,001 [Thread-924] INFO  i.a.enterprise.muxer.DASHMuxer - DASH Segment Duration: 6, Fragment Duration: 0.5
2021-04-22 08:47:05,001 [Thread-924] INFO  i.a.e.adaptive.EncoderAdaptor - ServerSettings exist io.antmedia.settings.ServerSettings@19648e12
2021-04-22 08:47:05,002 [Thread-924] INFO  i.a.streamsource.StreamFetcher - 178285984604366494481624 stream count in stream rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z is 2
2021-04-22 08:47:05,002 [Thread-924] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:1920 height:1080 for stream: 178285984604366494481624 source index:0 target index:0
2021-04-22 08:47:05,002 [Thread-924] INFO  i.a.enterprise.muxer.DASHMuxer - addStream with parameters and stream index:0 
2021-04-22 08:47:05,002 [Thread-924] INFO  io.antmedia.muxer.MuxAdaptor - Audio format sample rate:16000 bitrate:0 for stream: 178285984604366494481624 source index:1 target index:1
2021-04-22 08:47:05,002 [Thread-924] WARN  io.antmedia.muxer.MuxAdaptor - addStream returns false hls for stream: 178285984604366494481624
2021-04-22 08:47:05,002 [Thread-924] WARN  io.antmedia.muxer.MuxAdaptor - addStream returns false dash for stream: 178285984604366494481624
2021-04-22 08:47:05,002 [Thread-924] INFO  i.a.e.adaptive.EncoderAdaptor - not decoding video for stream: 178285984604366494481624
2021-04-22 08:47:05,003 [Thread-924] ERROR i.a.streamsource.StreamFetcher - java.lang.IllegalArgumentException: avcodec_find_decoder() error: Unsupported video format or codec not found: 0.
	at io.antmedia.enterprise.adaptive.base.AudioDecoder.prepareAudioDecoder(AudioDecoder.java:34)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareDecoders(EncoderAdaptor.java:402)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareInternal(EncoderAdaptor.java:311)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareFromInputFormatContext(EncoderAdaptor.java:340)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:272)

2021-04-22 08:47:05,004 [Thread-924] INFO  i.a.streamsource.StreamFetcher - write all buffered packets for stream: 178285984604366494481624
2021-04-22 08:47:05,004 [Thread-924] INFO  i.a.streamsource.StreamFetcher - Writing trailer in Muxadaptor 178285984604366494481624
2021-04-22 08:47:05,004 [Thread-924] INFO  i.a.e.adaptive.EncoderAdaptor - closing input and number of dropped packets 0
2021-04-22 08:47:05,004 [Thread-924] INFO  i.a.e.adaptive.EncoderAdaptor - Total video encode time 0ms, average video encode time 0ms total audio encode time 0ms total video decode time 0ms , average video decode time 0 ms 
2021-04-22 08:47:05,005 [Thread-924] INFO  i.a.streamsource.StreamFetcher - Stream fetcher will try to fetch source rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z after 3000 ms
2021-04-22 08:47:08,008 [Thread-925] INFO  i.a.streamsource.StreamFetcher - Preparing the StreamFetcher for rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
2021-04-22 08:47:08,008 [Thread-925] INFO  i.a.streamsource.StreamFetcher - Setting rtsp transport type to tcp for stream source: rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
2021-04-22 08:47:12,546 [vert.x-eventloop-thread-6] WARN  i.a.s.StreamFetcherManager - Mux adaptor is not initialized for stream fetcher with stream id: 178285984604366494481624 It's likely that stream fetching is not started yet
2021-04-22 08:47:15,074 [Thread-925] INFO  io.antmedia.muxer.MuxAdaptor - vertx exist io.vertx.core.impl.VertxImpl@dc3d088
2021-04-22 08:47:15,074 [Thread-925] INFO  io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for 178285984604366494481624
2021-04-22 08:47:15,074 [Thread-925] INFO  io.antmedia.muxer.MuxAdaptor - adding DASH Muxer for 178285984604366494481624
2021-04-22 08:47:15,075 [Thread-925] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
2021-04-22 08:47:15,076 [Thread-925] INFO  i.a.enterprise.muxer.DASHMuxer - DASH Segment Duration: 6, Fragment Duration: 0.5
2021-04-22 08:47:15,076 [Thread-925] INFO  i.a.e.adaptive.EncoderAdaptor - ServerSettings exist io.antmedia.settings.ServerSettings@19648e12
2021-04-22 08:47:15,076 [Thread-925] INFO  i.a.streamsource.StreamFetcher - 178285984604366494481624 stream count in stream rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z is 2
2021-04-22 08:47:15,077 [Thread-925] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:1920 height:1080 for stream: 178285984604366494481624 source index:0 target index:0
2021-04-22 08:47:15,077 [Thread-925] INFO  i.a.enterprise.muxer.DASHMuxer - addStream with parameters and stream index:0 
2021-04-22 08:47:15,077 [Thread-925] INFO  io.antmedia.muxer.MuxAdaptor - Audio format sample rate:16000 bitrate:0 for stream: 178285984604366494481624 source index:1 target index:1
2021-04-22 08:47:15,077 [Thread-925] WARN  io.antmedia.muxer.MuxAdaptor - addStream returns false hls for stream: 178285984604366494481624
2021-04-22 08:47:15,077 [Thread-925] WARN  io.antmedia.muxer.MuxAdaptor - addStream returns false dash for stream: 178285984604366494481624
2021-04-22 08:47:15,077 [Thread-925] INFO  i.a.e.adaptive.EncoderAdaptor - not decoding video for stream: 178285984604366494481624
2021-04-22 08:47:15,077 [Thread-925] ERROR i.a.streamsource.StreamFetcher - java.lang.IllegalArgumentException: avcodec_find_decoder() error: Unsupported video format or codec not found: 0.
	at io.antmedia.enterprise.adaptive.base.AudioDecoder.prepareAudioDecoder(AudioDecoder.java:34)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareDecoders(EncoderAdaptor.java:402)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareInternal(EncoderAdaptor.java:311)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareFromInputFormatContext(EncoderAdaptor.java:340)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:272)

2021-04-22 08:47:15,078 [Thread-925] INFO  i.a.streamsource.StreamFetcher - write all buffered packets for stream: 178285984604366494481624
2021-04-22 08:47:15,078 [Thread-925] INFO  i.a.streamsource.StreamFetcher - Writing trailer in Muxadaptor 178285984604366494481624
2021-04-22 08:47:15,078 [Thread-925] INFO  i.a.e.adaptive.EncoderAdaptor - closing input and number of dropped packets 0
2021-04-22 08:47:15,078 [Thread-925] INFO  i.a.e.adaptive.EncoderAdaptor - Total video encode time 0ms, average video encode time 0ms total audio encode time 0ms total video decode time 0ms , average video decode time 0 ms 
2021-04-22 08:47:15,078 [Thread-925] INFO  i.a.streamsource.StreamFetcher - Stream fetcher will try to fetch source rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z after 3000 ms
2021-04-22 08:47:18,082 [Thread-926] INFO  i.a.streamsource.StreamFetcher - Preparing the StreamFetcher for rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
2021-04-22 08:47:18,082 [Thread-926] INFO  i.a.streamsource.StreamFetcher - Setting rtsp transport type to tcp for stream source: rtsp://privateRTSPSource:554/Streaming/tracks/101?starttime=20210420T120226z
```

**Comment by SelimEmre** [comment]
I have sent PR for this issue #3230 It will fix this issue.
