### ISSUE TITLE
S3 integration not working

### ISSUE THREAD

**Issue by bharat-ux** [ant-media/Ant-Media-Server#3198]
App disappears after adding configuration
---------------------------------------------
<bean id="app.storageClient" class="io.antmedia.storage.AmazonS3StorageClient">
    <property name="accessKey" value="sdfsdlfjlsdfjsdlf" />
    <property name="secretKey" value="fsdjlfjsdlfjsdlf" />
    <property name="region" value="ap-south-1" />
    <property name="storageName" value="antmedia-12" />
</bean>

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by SelimEmre** [comment]
Hi @bharat-ux 

It may be related to syntax. Here is the sample `red5-web.xml` file:
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:aop="http://www.springframework.org/schema/aop"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
	http://www.springframework.org/schema/beans/spring-beans-4.3.xsd 
	http://www.springframework.org/schema/context
	http://www.springframework.org/schema/context/spring-context-4.3.xsd
	http://www.springframework.org/schema/aop 
    http://www.springframework.org/schema/aop/spring-aop-4.3.xsd">

	<context:annotation-config />
	<!-- Defines a properties file for dereferencing variables -->
	<context:property-placeholder location="/WEB-INF/red5-web.properties"/>
	
	<bean id="app.settings" class="io.antmedia.AppSettings" />

	<!-- Defines the web context -->
	<bean id="web.context" class="org.red5.server.Context" autowire="byType" />

	<!-- Defines the web scopes -->
	<bean id="web.scope" class="org.red5.server.scope.WebScope">
		<property name="server" ref="red5.server" />
		<property name="parent" ref="global.scope" />
		<property name="context" ref="web.context" />
		<property name="handler" ref="web.handler" />
	</bean>

<bean id="app.storageClient" class="io.antmedia.storage.AmazonS3StorageClient">
    <property name="accessKey" value="Enter your S3_ACCESS_KEY" />
    <property name="secretKey" value="Enter your S3_SECRET_KEY" />
    <property name="region" value="Enter your REGION_NAME e.g. eu-central-1" />
    <property name="storageName" value="Enter your BUCKET_NAME" />
</bean>

	<bean id="dataStoreFactory" class="io.antmedia.datastore.db.DataStoreFactory"/>

	<context:component-scan base-package="io.antmedia.rest" />
	
	<bean id="acceptOnlyStreamsInDataStore" class="io.antmedia.security.AcceptOnlyStreamsInDataStore"/>
		
	<bean id="hls.viewerstats" class="io.antmedia.statistic.HlsViewerStats" />
	
	<bean id="token.service"
		class="#{ T(io.antmedia.rest.RestServiceBase).isEnterprise() ? 'io.antmedia.enterprise.security.TokenService' : 'io.antmedia.security.MockTokenService' }">
	</bean>
	
	<bean id="publishIPFilter"
		class="#{ T(io.antmedia.rest.RestServiceBase).isEnterprise() ? 'io.antmedia.enterprise.security.PublishIPFilter' : 'io.antmedia.security.MockTokenService' }">
    </bean>
    
    <bean id="chunked.cache.manager"
		class="#{ T(io.antmedia.rest.RestServiceBase).isEnterprise() ? 'io.antmedia.enterprise.chunkedTransfer.ChunkedCacheManager' : 'io.antmedia.servlet.MockChunkedCacheManager' }">
    </bean>
    
    <bean id="streamAcceptFilter" class="io.antmedia.filter.StreamAcceptFilter"/>

	<!-- Defines the web handler which acts as an applications endpoint -->
	<bean id="web.handler" class="io.antmedia.enterprise.streamapp.StreamApplication">
		<property name="appSettings" ref="app.settings" />
		<property name="dataStoreFactory" ref="dataStoreFactory" />
		<property name="streamAcceptFilter" ref="streamAcceptFilter"/>
		<property name="streamPublishSecurityList">
			<list>
				<ref bean="acceptOnlyStreamsInDataStore"/>
			  	<ref bean="token.service"/>
				<bean class="io.antmedia.security.ExpireStreamPublishSecurity" >
					<property name="dataStoreFactory"  ref="dataStoreFactory"/>
				</bean>
				<ref bean="publishIPFilter"/>
			</list>
		</property>
	</bean>
	
    <bean id="webrtc.adaptor"  
    	class="#{ T(io.antmedia.rest.RestServiceBase).isEnterprise() ? 'io.antmedia.enterprise.webrtc.WebRTCAdaptor' : 'io.antmedia.webrtc.MockWebRTCAdaptor' }"/>
</beans>
```

**Comment by bharat-ux** [comment]
The data is not going in the s3 bucket and you will have to set it
somewhere else. or in another files

**Comment by bharat-ux** [comment]
thank you sir now aap are appears but The data is not going in the s3 bucket and you will have to set it somewhere else.

**Comment by bharat-ux** [comment]
i means in red5-web.properties or web.xml??

**Comment by bharat-ux** [comment]
021-04-26 04:31:42,289 [vert.x-eventloop-thread-2] INFO  i.a.AntMediaApplicationAdapter - Stream source size: 0
2021-04-26 04:31:42,296 [vert.x-eventloop-thread-2] INFO  i.a.s.StreamFetcherManager - StreamFetcherSchedule job name 10
2021-04-26 04:31:42,296 [vert.x-eventloop-thread-2] INFO  i.a.AntMediaApplicationAdapter - socialEndpoints size: 0
2021-04-26 04:31:50,738 [http-nio2-0.0.0.0-5080-exec-10] WARN  io.antmedia.statistic.GPUUtils - ClassNotFoundException nvml class not found org.bytedeco.cuda.global.nvml
2021-04-26 04:31:50,749 [http-nio2-0.0.0.0-5080-exec-4] INFO  io.antmedia.rest.RestServiceBase - Version Name 2.3.2 Version Type Community Edition
2021-04-26 04:32:36,738 [pool-5-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
2021-04-26 04:36:37,011 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:10 process cpu load:1 available memory: 6787428 KB used memory(RSS): 662868 KB
2021-04-26 04:36:37,012 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2021-04-26 04:41:37,012 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:1 process cpu load:0 available memory: 6780956 KB used memory(RSS): 672220 KB
2021-04-26 04:41:37,012 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2021-04-26 04:42:36,738 [pool-5-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start

**Comment by bharat-ux** [comment]
2021-04-26 04:51:27,711 [main] INFO  o.s.c.s.FileSystemXmlApplicationContext - Refreshing org.springframework.context.support.FileSystemXmlApplicationContext@4082ba93: startup date [Mon Apr 26 04:51:27 UTC 2021]; root of context hierarchy
2021-04-26 04:51:27,738 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [red5.xml]
2021-04-26 04:51:27,863 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [jee-container.xml]
2021-04-26 04:51:28,243 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2021-04-26 04:51:28,301 [main] INFO  o.r.spring.Red5ApplicationContext - setApplicationContext: org.springframework.context.support.FileSystemXmlApplicationContext@4082ba93: startup date [Mon Apr 26 04:51:27 UTC 2021]; root of context hierarchy
2021-04-26 04:51:28,301 [main] INFO  o.r.spring.Red5ApplicationContext - Red5ApplicationContext init
2021-04-26 04:51:28,302 [main] INFO  o.r.spring.Red5ApplicationContext - Refreshing ApplicationContext 'red5.common': startup date [Mon Apr 26 04:51:28 UTC 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@4082ba93
2021-04-26 04:51:28,303 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [red5-common.xml]
2021-04-26 04:51:28,436 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2021-04-26 04:51:28,487 [main] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
2021-04-26 04:51:28,499 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2021-04-26 04:51:28,499 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.3 created.
2021-04-26 04:51:28,500 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
2021-04-26 04:51:28,501 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'Red5_Scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 6 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-04-26 04:51:28,501 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'Red5_Scheduler' initialized from the specified file : '/usr/local/antmedia/conf/quartz.properties'
2021-04-26 04:51:28,501 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.2.3
2021-04-26 04:51:28,502 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler Red5_Scheduler_$_NON_CLUSTERED started.
2021-04-26 04:51:28,881 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler#2f9a01c1'
2021-04-26 04:51:29,294 [main] WARN  i.antmedia.statistic.StatsCollector - Starting heartbeats for the version:2.3.2 and type:Community
2021-04-26 04:51:29,348 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2021-04-26 04:51:29,349 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'schedulingService' has been autodetected for JMX exposure
2021-04-26 04:51:29,350 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'clientBroadcastStream' has been autodetected for JMX exposure
2021-04-26 04:51:29,519 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Located MBean 'schedulingService': registering with JMX server as MBean [org.red5.server:name=schedulingService,type=QuartzSchedulingService]
2021-04-26 04:51:29,537 [main] INFO  o.r.spring.Red5ApplicationContext - setApplicationContext: org.springframework.context.support.FileSystemXmlApplicationContext@4082ba93: startup date [Mon Apr 26 04:51:27 UTC 2021]; root of context hierarchy
2021-04-26 04:51:29,538 [main] INFO  o.r.spring.Red5ApplicationContext - Red5ApplicationContext init
2021-04-26 04:51:29,538 [main] INFO  o.r.spring.Red5ApplicationContext - Refreshing ApplicationContext 'red5.core': startup date [Mon Apr 26 04:51:29 UTC 2021]; parent: ApplicationContext 'red5.common'
2021-04-26 04:51:29,539 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [red5-core.xml]
2021-04-26 04:51:29,647 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'rtmpScheduler'
2021-04-26 04:51:29,664 [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 'messageExecutor'
2021-04-26 04:51:29,664 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'deadlockGuardScheduler'
2021-04-26 04:51:29,692 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - RTMP will be bound to [0.0.0.0:1935]
2021-04-26 04:51:29,694 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - RTMP Mina Transport Settings
Acceptor style: default I/O threads: 16
TCP no-delay: true keep-alive: false
2021-04-26 04:51:29,755 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - Traffic class modification is disabled
2021-04-26 04:51:29,756 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - Send buffer size: 65536 recv buffer size: 65536 so linger: -1 traffic class: 0
2021-04-26 04:51:29,805 [main] INFO  org.red5.server.ContextLoader - ContextLoader init
2021-04-26 04:51:29,812 [main] INFO  org.red5.server.ContextLoader - Loading: default.context = ${red5.root}/webapps/red5-default.xml => /usr/local/antmedia/webapps/red5-default.xml
2021-04-26 04:51:29,813 [main] INFO  o.s.c.s.FileSystemXmlApplicationContext - Refreshing org.springframework.context.support.FileSystemXmlApplicationContext@60e9c3a5: startup date [Mon Apr 26 04:51:29 UTC 2021]; parent: ApplicationContext 'red5.common'
2021-04-26 04:51:29,814 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from URL [file:/usr/local/antmedia/webapps/red5-default.xml]
2021-04-26 04:51:29,937 [main] INFO  org.red5.server.Context - Setting parent bean factory as core
2021-04-26 04:51:29,955 [main] INFO  org.red5.server.tomcat.WarDeployer - War deployer service created
2021-04-26 04:51:29,958 [main] INFO  org.red5.server.tomcat.WarDeployer - Starting WarDeployer
2021-04-26 04:51:29,959 [main] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars without app start
2021-04-26 04:51:30,076 [main] INFO  org.red5.server.tomcat.TomcatLoader - Loading Tomcat
2021-04-26 04:51:30,076 [main] INFO  org.red5.server.tomcat.TomcatLoader - Server root: /usr/local/antmedia
2021-04-26 04:51:30,077 [main] INFO  org.red5.server.tomcat.TomcatLoader - Config root: /usr/local/antmedia/conf
2021-04-26 04:51:30,101 [main] INFO  org.red5.server.tomcat.TomcatLoader - Application root: /usr/local/antmedia/webapps
2021-04-26 04:51:30,232 [main] INFO  org.red5.server.tomcat.TomcatLoader - Starting Tomcat servlet engine
2021-04-26 04:51:30,474 [main] INFO  o.a.c.core.AprLifecycleListener - Loaded Apache Tomcat Native library [1.2.25] using APR version [1.6.3].
2021-04-26 04:51:30,475 [main] INFO  o.a.c.core.AprLifecycleListener - APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2021-04-26 04:51:30,476 [main] INFO  o.a.c.core.AprLifecycleListener - APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2021-04-26 04:51:30,482 [main] INFO  o.a.c.http11.Http11Nio2Protocol - Initializing ProtocolHandler ["http-nio2-0.0.0.0-5080"]
2021-04-26 04:51:30,524 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2021-04-26 04:51:30,525 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.58
2021-04-26 04:51:30,639 [0.0.0.0-startStop-1] INFO  o.a.catalina.startup.ContextConfig - No global web.xml found
2021-04-26 04:51:30,976 [0.0.0.0-startStop-1] INFO  o.a.c.c.C.[.[0.0.0.0].[/] - No Spring WebApplicationInitializer types detected on classpath
2021-04-26 04:51:31,069 [0.0.0.0-startStop-1] INFO  ROOT - Starting up context: root
2021-04-26 04:51:31,927 [0.0.0.0-startStop-1] ERROR o.g.j.s.s.SpringComponentProvider - Spring context lookup failed, skipping spring component provider initialization.
2021-04-26 04:51:32,497 [0.0.0.0-startStop-1] INFO  o.a.c.c.C.[.[0.0.0.0].[/WebRTCApp] - No Spring WebApplicationInitializer types detected on classpath
2021-04-26 04:51:32,613 [0.0.0.0-startStop-1] INFO  o.a.c.c.C.[.[0.0.0.0].[/LiveApp] - No Spring WebApplicationInitializer types detected on classpath
2021-04-26 04:51:32,628 [0.0.0.0-startStop-1] INFO  ROOT - Starting up context: LiveApp
2021-04-26 04:51:32,865 [0.0.0.0-startStop-1] ERROR o.g.j.s.s.SpringComponentProvider - Spring context lookup failed, skipping spring component provider initialization.
2021-04-26 04:51:33,219 [0.0.0.0-startStop-1] INFO  o.a.c.c.C.[.[0.0.0.0].[/bharat] - No Spring WebApplicationInitializer types detected on classpath
2021-04-26 04:51:33,224 [0.0.0.0-startStop-1] INFO  ROOT - Starting up context: bharat
2021-04-26 04:51:33,390 [0.0.0.0-startStop-1] ERROR o.g.j.s.s.SpringComponentProvider - Spring context lookup failed, skipping spring component provider initialization.
2021-04-26 04:51:33,652 [0.0.0.0-startStop-1] INFO  o.a.c.c.C.[.[0.0.0.0].[/mys] - No Spring WebApplicationInitializer types detected on classpath
2021-04-26 04:51:33,656 [0.0.0.0-startStop-1] INFO  ROOT - Starting up context: mys
2021-04-26 04:51:33,792 [0.0.0.0-startStop-1] ERROR o.g.j.s.s.SpringComponentProvider - Spring context lookup failed, skipping spring component provider initialization.
2021-04-26 04:51:34,001 [main] INFO  o.a.c.http11.Http11Nio2Protocol - Starting ProtocolHandler ["http-nio2-0.0.0.0-5080"]
2021-04-26 04:51:34,010 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized:  path: /usr/local/antmedia/webapps/root/
2021-04-26 04:51:34,017 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized: /WebRTCApp path: /usr/local/antmedia/webapps/WebRTCApp/
2021-04-26 04:51:34,018 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized: /LiveApp path: /usr/local/antmedia/webapps/LiveApp/
2021-04-26 04:51:34,019 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized: /bharat path: /usr/local/antmedia/webapps/bharat/
2021-04-26 04:51:34,019 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized: /mys path: /usr/local/antmedia/webapps/mys/
2021-04-26 04:51:34,019 [main] INFO  org.red5.server.tomcat.TomcatLoader - Dedicated RTMPT server configuration was not specified
2021-04-26 04:51:34,025 [main] INFO  o.r.server.service.ShutdownServer - JEE server was found: TomcatLoader [serviceEngineName=red5Engine]
2021-04-26 04:51:34,049 [Loader:] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Mon Apr 26 04:51:34 UTC 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@60e9c3a5
2021-04-26 04:51:34,053 [Loader:] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/red5-web.xml]
2021-04-26 04:51:34,204 [Loader:] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2021-04-26 04:51:34,241 [Loader:] INFO  org.red5.server.Context - Setting parent bean factory as core
2021-04-26 04:51:34,319 [Loader:] INFO  org.red5.server.scope.WebScope - Set server [Server@57feea33map[[empty]]]
2021-04-26 04:51:34,326 [Loader:] INFO  org.red5.server.Server - Add mapping global: default host:  context: root
2021-04-26 04:51:34,329 [Loader:] INFO  org.red5.server.scope.WebScope - Webscope already registered; remove the 'init-method' from your 'web.scope' bean to prevent this message in the future.
2021-04-26 04:51:34,377 [Loader:/WebRTCApp] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Mon Apr 26 04:51:34 UTC 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@60e9c3a5
2021-04-26 04:51:34,380 [Loader:/WebRTCApp] ERROR org.red5.server.tomcat.TomcatLoader - org.springframework.beans.factory.BeanDefinitionStoreException: Could not resolve bean definition resource pattern [/WEB-INF/red5-*.xml]; nested exception is java.io.FileNotFoundException: ServletContext resource [/WEB-INF/] cannot be resolved to URL because it does not exist
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:229)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:126)
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:614)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:514)
        at org.red5.server.tomcat.TomcatLoader$1.run(TomcatLoader.java:521)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.FileNotFoundException: ServletContext resource [/WEB-INF/] cannot be resolved to URL because it does not exist
        at org.springframework.web.context.support.ServletContextResource.getURL(ServletContextResource.java:156)
        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:493)
        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:294)
        at org.springframework.context.support.AbstractApplicationContext.getResources(AbstractApplicationContext.java:1297)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:216)
        ... 12 more

2021-04-26 04:51:34,382 [Loader:/LiveApp] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Mon Apr 26 04:51:34 UTC 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@60e9c3a5
2021-04-26 04:51:34,382 [Loader:/LiveApp] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/red5-web.xml]
2021-04-26 04:51:34,555 [Loader:/LiveApp] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2021-04-26 04:51:34,658 [Loader:/LiveApp] INFO  org.red5.server.Context - Setting parent bean factory as core
2021-04-26 04:51:35,201 [Loader:/LiveApp] INFO  i.a.datastore.db.DataStoreFactory - Used Datastore:mapdb  db name:liveapp
2021-04-26 04:51:35,218 [Loader:/LiveApp] INFO  org.red5.server.scope.WebScope - Set server [Server@57feea33map['/root' -> 'default']]
2021-04-26 04:51:35,219 [Loader:/LiveApp] INFO  org.red5.server.Server - Add mapping global: default host:  context: LiveApp
2021-04-26 04:51:35,222 [Loader:/LiveApp] INFO  i.a.AntMediaApplicationAdapter - Delete the ".closed" file in LiveApp
2021-04-26 04:51:35,228 [Loader:/LiveApp] INFO  i.a.AntMediaApplicationAdapter - LiveApp started
2021-04-26 04:51:35,241 [vert.x-eventloop-thread-2] INFO  i.a.AntMediaApplicationAdapter - Stream source size: 0
2021-04-26 04:51:35,242 [vert.x-eventloop-thread-2] INFO  i.a.s.StreamFetcherManager - StreamFetcherSchedule job name 3
2021-04-26 04:51:35,242 [vert.x-eventloop-thread-2] INFO  i.a.AntMediaApplicationAdapter - socialEndpoints size: 0
2021-04-26 04:51:35,289 [Loader:/bharat] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Mon Apr 26 04:51:35 UTC 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@60e9c3a5
2021-04-26 04:51:35,290 [Loader:/bharat] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/red5-web.xml]
2021-04-26 04:51:35,430 [Loader:/bharat] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2021-04-26 04:51:35,501 [Loader:/bharat] INFO  org.red5.server.Context - Setting parent bean factory as core
2021-04-26 04:51:35,544 [Loader:/bharat] INFO  i.a.datastore.db.DataStoreFactory - Used Datastore:mapdb  db name:bharat
2021-04-26 04:51:35,548 [Loader:/bharat] INFO  org.red5.server.scope.WebScope - Set server [Server@57feea33map['/root' -> 'default', '/LiveApp' -> 'default']]
2021-04-26 04:51:35,549 [Loader:/bharat] INFO  org.red5.server.Server - Add mapping global: default host:  context: bharat
2021-04-26 04:51:35,550 [Loader:/bharat] INFO  i.a.AntMediaApplicationAdapter - Delete the ".closed" file in bharat
2021-04-26 04:51:35,551 [Loader:/bharat] INFO  i.a.AntMediaApplicationAdapter - bharat started
2021-04-26 04:51:35,561 [vert.x-eventloop-thread-0] INFO  i.a.AntMediaApplicationAdapter - Stream source size: 0
2021-04-26 04:51:35,562 [vert.x-eventloop-thread-0] INFO  i.a.s.StreamFetcherManager - StreamFetcherSchedule job name 6
2021-04-26 04:51:35,562 [vert.x-eventloop-thread-0] INFO  i.a.AntMediaApplicationAdapter - socialEndpoints size: 0
2021-04-26 04:51:35,587 [Loader:/mys] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Mon Apr 26 04:51:35 UTC 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@60e9c3a5
2021-04-26 04:51:35,588 [Loader:/mys] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/red5-web.xml]
2021-04-26 04:51:35,720 [Loader:/mys] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2021-04-26 04:51:35,780 [Loader:/mys] INFO  org.red5.server.Context - Setting parent bean factory as core
2021-04-26 04:51:35,815 [Loader:/mys] INFO  i.a.datastore.db.DataStoreFactory - Used Datastore:mapdb  db name:mys
2021-04-26 04:51:35,822 [Loader:/mys] INFO  org.red5.server.scope.WebScope - Set server [Server@57feea33map['/root' -> 'default', '/LiveApp' -> 'default', '/bharat' -> 'default']]
2021-04-26 04:51:35,823 [Loader:/mys] INFO  org.red5.server.Server - Add mapping global: default host:  context: mys
2021-04-26 04:51:35,825 [Loader:/mys] INFO  i.a.AntMediaApplicationAdapter - Delete the ".closed" file in mys
2021-04-26 04:51:35,826 [Loader:/mys] INFO  i.a.AntMediaApplicationAdapter - mys started
2021-04-26 04:51:35,835 [vert.x-eventloop-thread-2] INFO  i.a.AntMediaApplicationAdapter - Stream source size: 0
2021-04-26 04:51:35,836 [vert.x-eventloop-thread-2] INFO  i.a.s.StreamFetcherManager - StreamFetcherSchedule job name 9
2021-04-26 04:51:35,836 [vert.x-eventloop-thread-2] INFO  i.a.AntMediaApplicationAdapter - socialEndpoints size: 0
2021-04-26 04:52:29,959 [pool-5-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start

**Comment by bharat-ux** [comment]
we are working on bharat app
