### ISSUE TITLE
SSL Error 

### ISSUE THREAD

**Issue by guangyi1609** [ant-media/Ant-Media-Server#3351]
After using the enable_ssl.sh , i getting this error when redirect to the page https://xx:5443/

error
This site can’t be reached10.0.13.51 unexpectedly closed the connection. 

when i restart antmedia service, i check the log again it show (privkey.pem is there) :

WARNING: Error initializing SSL context
java.lang.Exception: Unable to load certificate key /usr/local/antmedia/conf/privkey.pem (error:2807106B:UI routines:UI_process:processing error)
	at org.apache.tomcat.jni.SSLContext.setCertificate(Native Method)
	at org.apache.tomcat.util.net.openssl.OpenSSLContext.addCertificate(OpenSSLContext.java:384)
	at org.apache.tomcat.util.net.openssl.OpenSSLContext.init(OpenSSLContext.java:255)
	at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.java:245)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:98)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:72)
	at org.apache.tomcat.util.net.Nio2Endpoint.bind(Nio2Endpoint.java:158)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1118)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:222)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:587)
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:75)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:1075)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:552)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:848)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:440)
	at org.red5.server.tomcat.TomcatLoader.start(TomcatLoader.java:454)
	at org.red5.server.tomcat.TomcatLoader.afterPropertiesSet(TomcatLoader.java:187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1677)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1615)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:220)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1015)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1094)
	at org.red5.server.service.ShutdownServer.afterPropertiesSet(ShutdownServer.java:118)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1677)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1615)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:757)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.red5.server.Launcher.launch(Launcher.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.red5.server.Bootstrap.bootStrap(Bootstrap.java:122)
	at org.red5.server.Bootstrap.main(Bootstrap.java:50)

Jun 16, 2021 11:24:25 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Jun 16, 2021 11:24:25 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.58
Jun 16, 2021 11:24:25 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Jun 16, 2021 11:24:25 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jun 16, 2021 11:24:26 AM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Jun 16, 2021 11:24:26 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jun 16, 2021 11:24:26 AM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Jun 16, 2021 11:24:26 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jun 16, 2021 11:24:27 AM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Jun 16, 2021 11:24:27 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jun 16, 2021 11:24:27 AM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Jun 16, 2021 11:24:27 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jun 16, 2021 11:24:27 AM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Jun 16, 2021 11:24:27 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jun 16, 2021 11:24:27 AM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Jun 16, 2021 11:24:27 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio2-0.0.0.0-5080"]
Jun 16, 2021 11:24:27 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["https-openssl-nio2-0.0.0.0-5443"]
[tcp @ 0x7fef3c003e80] Connection to tcp://10.0.230.21:554?timeout=5000000 failed: Connection timed out
[tcp @ 0x7fef78004e80] Connection to tcp://10.0.230.50:554?timeout=5000000 failed: Connection timed out
tive Method)
	at org.apache.tomcat.util.net.openssl.OpenSSLEngine.<init>(OpenSSLEngine.java:200)
	at org.apache.tomcat.util.net.openssl.OpenSSLContext.createSSLEngine(OpenSSLContext.java:500)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLEngine(AbstractJsseEndpoint.java:120)
	at org.apache.tomcat.util.net.SecureNio2Channel.processSNI(SecureNio2Channel.java:432)
	at org.apache.tomcat.util.net.SecureNio2Channel.handshakeInternal(SecureNio2Channel.java:226)
	at org.apache.tomcat.util.net.SecureNio2Channel.handshake(SecureNio2Channel.java:217)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1082)
	at org.apache.tomcat.util.net.SecureNio2Channel$HandshakeReadCompletionHandler.completed(SecureNio2Channel.java:99)
	at org.apache.tomcat.util.net.SecureNio2Channel$HandshakeReadCompletionHandler.completed(SecureNio2Channel.java:92)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by muratugureminoglu** [comment]
Hi @guangyi1609 

Are you using Let's Encrypt or your own certificate? 

Regards.

**Comment by muratugureminoglu** [comment]
@guangyi1609 Maybe the private key is password protected? Could you please check it ? 

Best.

**Comment by guangyi1609** [comment]
Yes it is. But i already enter valid password when enable ssl using the
enable_ssl.sh script.

**Comment by muratugureminoglu** [comment]
@guangyi1609 Did you solve your issue or is it still ongoing?

**Comment by guangyi1609** [comment]
No, it didn't.

**Comment by muratugureminoglu** [comment]
@guangyi1609 if you want a workaround solution, you can remove the password from the private key as follows. At the same time, I’ll take a look at this issue.
```
openssl rsa -in [original.key] -out [new.key]
```
Regards.

**Comment by muratugureminoglu** [comment]
@guangyi1609  if you want a workaround solution, you can remove the password from the private key as follows. At the same time, I’ll take a look at this issue.
```
openssl rsa -in original.key -out new.key
```
Regards.

**Comment by haizrul** [comment]
I have the same issue. How do i solve this?

**Comment by haizrul** [comment]
I have the same issue. How do i solve this?

**Comment by mekya** [comment]
Hi @haizrul ,

Have you tried the solution below?

> @guangyi1609 if you want a workaround solution, you can remove the password from the private key as follows. At the same time, I’ll take a look at this issue.
> 
> ```
> openssl rsa -in original.key -out new.key
> ```
> 
> Regards.
