### ISSUE TITLE
Fresh Install Antmedia on Ubuntu 18.04 automatically closes

### ISSUE THREAD

**Issue by litzbalane2017** [ant-media/Ant-Media-Server#3433]
I have installed Ant Media Server Community 2.3.3.1 on Ubuntu 18.04. I have completed the installation, but antmedia server automatically closes after installation.

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

I have the following error logs from **/var/log/antmedia-error.log:**

```

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/usr/local/antmedia/lib/spring-core-4.3.28.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jul 08, 2021 1:22:46 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: Loaded Apache Tomcat Native library [1.2.25] using APR version [1.6.3].
Jul 08, 2021 1:22:46 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
Jul 08, 2021 1:22:46 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
Jul 08, 2021 1:22:46 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio2-0.0.0.0-5080"]
Jul 08, 2021 1:22:46 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Jul 08, 2021 1:22:46 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.58
Jul 08, 2021 1:22:46 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Jul 08, 2021 1:22:47 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jul 08, 2021 1:22:48 PM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Jul 08, 2021 1:22:49 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jul 08, 2021 1:22:49 PM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Jul 08, 2021 1:22:50 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jul 08, 2021 1:22:50 PM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Jul 08, 2021 1:22:50 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio2-0.0.0.0-5080"]
```

**/var/log/antmedia/ant-media-server.log**

```
2021-07-08 13:22:43,510 [main] INFO  org.red5.server.Launcher - Ant Media Server Community 2.3.2
2021-07-08 13:22:43,513 [main] INFO  org.red5.server.Launcher - 
                                                             
             `..-:/++oosssyyyyyyyysssoo++/::..`             
        .:+osyyyyysooo++///::::::///++ooosyyyyyso+:.        
     -+syyso/:-.`         ```````          `.-:/osyyy+-     
   .oyyo:.    ``.-:/+oossyyyyyys:`.+o+: `..`      `-+yys.   
   oyy-   `.-:://:::::///++ooo-`-oyo:../sys/`.::.    .yys   
   syy+`                       `.-. -oys/..:oys+:`   :yyy   
   syyyo-`                           `. `+so/.`   `-oyyyy   
   syy+sys+:.`                           ``   `.:+syyoyyy   
   syy``:+syyso`       `..`                 `osyyso:. syy   
   syy`   `.oyy.      :syyso:.`             `yys.`    syy   
   syy`     +yy.      syy:+syys+-`          `yyo      syy   
   syy`     +yy.      yyy  `.:osyso/.`      `yyo      syy   
   syy`     +yy.      yyy      `-/syys+.    `yyo      syy   
   syy`     +yy.      yyy         `./yyy    `yyo      syy   
   syy`     +yy.      yyy       `./oyys/    `yyo      syy   
   syy`     +yy.      yyy    .:+syyo/-`     `yyo      syy   
   syy`     +yy.      yyy`-/syys+:.         `yyo      syy   
   syy`     +yy.      +yyyyyo/.`            `yyo      yyy   
   /yy/     +yy.       -::-`                `yyo     :yy+   
    +yyo:.  +yy.                            `yyo  .-oyy+`   
     .+yyyysyyy.                            `yyysyyyy+-     
        .:/+++/                              :+//:-.        
                                                            


2021-07-08 13:22:43,555 [main] INFO  o.s.c.s.FileSystemXmlApplicationContext - Refreshing org.springframework.context.support.FileSystemXmlApplicationContext@792b749c: startup date [Thu Jul 08 13:22:43 PST 2021]; root of context hierarchy
2021-07-08 13:22:43,595 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [red5.xml]
2021-07-08 13:22:43,741 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [jee-container.xml]
2021-07-08 13:22:44,214 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2021-07-08 13:22:44,314 [main] INFO  o.r.spring.Red5ApplicationContext - setApplicationContext: org.springframework.context.support.FileSystemXmlApplicationContext@792b749c: startup date [Thu Jul 08 13:22:43 PST 2021]; root of context hierarchy
2021-07-08 13:22:44,315 [main] INFO  o.r.spring.Red5ApplicationContext - Red5ApplicationContext init
2021-07-08 13:22:44,317 [main] INFO  o.r.spring.Red5ApplicationContext - Refreshing ApplicationContext 'red5.common': startup date [Thu Jul 08 13:22:44 PST 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@792b749c
2021-07-08 13:22:44,318 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [red5-common.xml]
2021-07-08 13:22:44,546 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2021-07-08 13:22:44,626 [main] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
2021-07-08 13:22:44,642 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2021-07-08 13:22:44,642 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.3 created.
2021-07-08 13:22:44,643 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
2021-07-08 13:22:44,644 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'Red5_Scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 6 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-07-08 13:22:44,644 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'Red5_Scheduler' initialized from the specified file : '/usr/local/antmedia/conf/quartz.properties'
2021-07-08 13:22:44,645 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.2.3
2021-07-08 13:22:44,645 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler Red5_Scheduler_$_NON_CLUSTERED started.
2021-07-08 13:22:45,027 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler#5778826f'
2021-07-08 13:22:45,508 [main] WARN  i.antmedia.statistic.StatsCollector - Starting heartbeats for the version:2.3.2 and type:Community
2021-07-08 13:22:45,577 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2021-07-08 13:22:45,578 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'schedulingService' has been autodetected for JMX exposure
2021-07-08 13:22:45,579 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'clientBroadcastStream' has been autodetected for JMX exposure
2021-07-08 13:22:45,733 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Located MBean 'schedulingService': registering with JMX server as MBean [org.red5.server:name=schedulingService,type=QuartzSchedulingService]
2021-07-08 13:22:45,747 [main] INFO  o.r.spring.Red5ApplicationContext - setApplicationContext: org.springframework.context.support.FileSystemXmlApplicationContext@792b749c: startup date [Thu Jul 08 13:22:43 PST 2021]; root of context hierarchy
2021-07-08 13:22:45,748 [main] INFO  o.r.spring.Red5ApplicationContext - Red5ApplicationContext init
2021-07-08 13:22:45,748 [main] INFO  o.r.spring.Red5ApplicationContext - Refreshing ApplicationContext 'red5.core': startup date [Thu Jul 08 13:22:45 PST 2021]; parent: ApplicationContext 'red5.common'
2021-07-08 13:22:45,748 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [red5-core.xml]
2021-07-08 13:22:45,822 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'rtmpScheduler'
2021-07-08 13:22:45,831 [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 'messageExecutor'
2021-07-08 13:22:45,832 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'deadlockGuardScheduler'
2021-07-08 13:22:45,873 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - RTMP will be bound to [0.0.0.0:1935]
2021-07-08 13:22:45,873 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - RTMP Mina Transport Settings
Acceptor style: default I/O threads: 16
TCP no-delay: true keep-alive: false
2021-07-08 13:22:45,895 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - Traffic class modification is disabled
2021-07-08 13:22:45,896 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - Send buffer size: 65536 recv buffer size: 65536 so linger: -1 traffic class: 0
2021-07-08 13:22:45,935 [main] INFO  org.red5.server.ContextLoader - ContextLoader init
2021-07-08 13:22:45,945 [main] INFO  org.red5.server.ContextLoader - Loading: default.context = ${red5.root}/webapps/red5-default.xml => /usr/local/antmedia/webapps/red5-default.xml
2021-07-08 13:22:45,946 [main] INFO  o.s.c.s.FileSystemXmlApplicationContext - Refreshing org.springframework.context.support.FileSystemXmlApplicationContext@71e4b308: startup date [Thu Jul 08 13:22:45 PST 2021]; parent: ApplicationContext 'red5.common'
2021-07-08 13:22:45,946 [main] INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from URL [file:/usr/local/antmedia/webapps/red5-default.xml]
2021-07-08 13:22:46,098 [main] INFO  org.red5.server.Context - Setting parent bean factory as core
2021-07-08 13:22:46,156 [main] INFO  org.red5.server.tomcat.WarDeployer - War deployer service created
2021-07-08 13:22:46,165 [main] INFO  org.red5.server.tomcat.WarDeployer - Starting WarDeployer
2021-07-08 13:22:46,172 [main] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars without app start
2021-07-08 13:22:46,328 [main] INFO  org.red5.server.tomcat.TomcatLoader - Loading Tomcat
2021-07-08 13:22:46,328 [main] INFO  org.red5.server.tomcat.TomcatLoader - Server root: /usr/local/antmedia
2021-07-08 13:22:46,328 [main] INFO  org.red5.server.tomcat.TomcatLoader - Config root: /usr/local/antmedia/conf
2021-07-08 13:22:46,352 [main] INFO  org.red5.server.tomcat.TomcatLoader - Application root: /usr/local/antmedia/webapps
2021-07-08 13:22:46,445 [main] INFO  org.red5.server.tomcat.TomcatLoader - Starting Tomcat servlet engine
2021-07-08 13:22:46,737 [main] INFO  o.a.c.core.AprLifecycleListener - Loaded Apache Tomcat Native library [1.2.25] using APR version [1.6.3].
2021-07-08 13:22:46,739 [main] INFO  o.a.c.core.AprLifecycleListener - APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2021-07-08 13:22:46,740 [main] INFO  o.a.c.core.AprLifecycleListener - APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2021-07-08 13:22:46,750 [main] INFO  o.a.c.http11.Http11Nio2Protocol - Initializing ProtocolHandler ["http-nio2-0.0.0.0-5080"]
2021-07-08 13:22:46,824 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2021-07-08 13:22:46,825 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.58
2021-07-08 13:22:46,975 [0.0.0.0-startStop-1] INFO  o.a.catalina.startup.ContextConfig - No global web.xml found
2021-07-08 13:22:47,368 [0.0.0.0-startStop-1] INFO  o.a.c.c.C.[.[0.0.0.0].[/] - No Spring WebApplicationInitializer types detected on classpath
2021-07-08 13:22:47,473 [0.0.0.0-startStop-1] INFO  ROOT - Starting up context: root
2021-07-08 13:22:48,642 [0.0.0.0-startStop-1] ERROR o.g.j.s.s.SpringComponentProvider - Spring context lookup failed, skipping spring component provider initialization.
2021-07-08 13:22:49,398 [0.0.0.0-startStop-1] INFO  o.a.c.c.C.[.[0.0.0.0].[/WebRTCApp] - No Spring WebApplicationInitializer types detected on classpath
2021-07-08 13:22:49,426 [0.0.0.0-startStop-1] INFO  ROOT - Starting up context: WebRTCApp
2021-07-08 13:22:49,721 [0.0.0.0-startStop-1] ERROR o.g.j.s.s.SpringComponentProvider - Spring context lookup failed, skipping spring component provider initialization.
2021-07-08 13:22:50,120 [0.0.0.0-startStop-1] INFO  o.a.c.c.C.[.[0.0.0.0].[/LiveApp] - No Spring WebApplicationInitializer types detected on classpath
2021-07-08 13:22:50,123 [0.0.0.0-startStop-1] INFO  ROOT - Starting up context: LiveApp
2021-07-08 13:22:50,283 [0.0.0.0-startStop-1] ERROR o.g.j.s.s.SpringComponentProvider - Spring context lookup failed, skipping spring component provider initialization.
2021-07-08 13:22:50,469 [main] INFO  o.a.c.http11.Http11Nio2Protocol - Starting ProtocolHandler ["http-nio2-0.0.0.0-5080"]
2021-07-08 13:22:50,488 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized:  path: /usr/local/antmedia/webapps/root/
2021-07-08 13:22:50,490 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized: /WebRTCApp path: /usr/local/antmedia/webapps/WebRTCApp/
2021-07-08 13:22:50,490 [main] INFO  org.red5.server.tomcat.TomcatLoader - Context initialized: /LiveApp path: /usr/local/antmedia/webapps/LiveApp/
2021-07-08 13:22:50,491 [main] INFO  org.red5.server.tomcat.TomcatLoader - Dedicated RTMPT server configuration was not specified
2021-07-08 13:22:50,493 [main] INFO  o.r.server.service.ShutdownServer - JEE server was found: TomcatLoader [serviceEngineName=red5Engine]
2021-07-08 13:22:50,508 [pool-6-thread-1] ERROR o.r.server.service.ShutdownServer - Cannot bind to port: 9999, ensure no other instances are bound or choose another port
java.net.BindException: Address already in use (Bind failed)
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:149)
	at org.red5.server.service.ShutdownServer.start(ShutdownServer.java:172)
	at org.red5.server.service.ShutdownServer$1.run(ShutdownServer.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-07-08 13:22:50,527 [pool-6-thread-1] INFO  o.red5.server.plugin.PluginRegistry - Destroying and cleaning up 0 plugins
2021-07-08 13:22:50,533 [pool-6-thread-1] INFO  org.red5.server.ContextLoader - Shutting down
2021-07-08 13:22:50,533 [pool-6-thread-1] INFO  org.red5.server.ContextLoader - Unloading context default.context on shutdown
2021-07-08 13:22:50,543 [pool-6-thread-1] INFO  o.s.c.s.FileSystemXmlApplicationContext - Closing org.springframework.context.support.FileSystemXmlApplicationContext@71e4b308: startup date [Thu Jul 08 13:22:45 PST 2021]; parent: ApplicationContext 'red5.common'
2021-07-08 13:22:50,544 [pool-6-thread-1] INFO  org.red5.server.ContextLoader - Shutdown complete
2021-07-08 13:22:50,546 [Loader:] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Thu Jul 08 13:22:50 PST 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@71e4b308
2021-07-08 13:22:50,550 [Loader:] ERROR org.red5.server.tomcat.TomcatLoader - java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:164)
	at org.springframework.context.support.AbstractApplicationContext.getInternalParentBeanFactory(AbstractApplicationContext.java:1245)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.createBeanFactory(AbstractRefreshableApplicationContext.java:193)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:123)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:614)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:514)
	at org.red5.server.tomcat.TomcatLoader$1.run(TomcatLoader.java:521)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-07-08 13:22:50,554 [Loader:/WebRTCApp] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Thu Jul 08 13:22:50 PST 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@71e4b308
2021-07-08 13:22:50,554 [Loader:/WebRTCApp] ERROR org.red5.server.tomcat.TomcatLoader - java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:164)
	at org.springframework.context.support.AbstractApplicationContext.getInternalParentBeanFactory(AbstractApplicationContext.java:1245)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.createBeanFactory(AbstractRefreshableApplicationContext.java:193)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:123)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:614)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:514)
	at org.red5.server.tomcat.TomcatLoader$1.run(TomcatLoader.java:521)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-07-08 13:22:50,557 [Loader:/LiveApp] INFO  o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Thu Jul 08 13:22:50 PST 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@71e4b308
2021-07-08 13:22:50,557 [Loader:/LiveApp] ERROR org.red5.server.tomcat.TomcatLoader - java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:164)
	at org.springframework.context.support.AbstractApplicationContext.getInternalParentBeanFactory(AbstractApplicationContext.java:1245)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.createBeanFactory(AbstractRefreshableApplicationContext.java:193)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:123)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:614)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:514)
	at org.red5.server.tomcat.TomcatLoader$1.run(TomcatLoader.java:521)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-07-08 13:22:50,560 [Thread-8] INFO  o.r.spring.Red5ApplicationContext - Closing ApplicationContext 'red5.core': startup date [Thu Jul 08 13:22:45 PST 2021]; parent: ApplicationContext 'red5.common'
2021-07-08 13:22:50,574 [Thread-8] INFO  o.r.s.net.rtmp.RTMPMinaTransport - RTMP Mina Transport stop
2021-07-08 13:22:50,574 [Thread-10] INFO  o.s.c.s.FileSystemXmlApplicationContext - Closing org.springframework.context.support.FileSystemXmlApplicationContext@792b749c: startup date [Thu Jul 08 13:22:43 PST 2021]; root of context hierarchy
2021-07-08 13:22:50,576 [Thread-8] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'deadlockGuardScheduler'
2021-07-08 13:22:50,580 [Thread-9] INFO  o.r.spring.Red5ApplicationContext - Closing ApplicationContext 'red5.common': startup date [Thu Jul 08 13:22:44 PST 2021]; parent: org.springframework.context.support.FileSystemXmlApplicationContext@792b749c
2021-07-08 13:22:50,580 [Thread-8] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'messageExecutor'
2021-07-08 13:22:50,581 [Thread-8] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'rtmpScheduler'
2021-07-08 13:22:50,583 [Thread-9] INFO  i.antmedia.statistic.StatsCollector - Shutting down stats collector 
2021-07-08 13:22:50,583 [Thread-9] INFO  i.antmedia.statistic.StatsCollector - Ending analytic session
2021-07-08 13:22:50,584 [Thread-10] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 0
2021-07-08 13:22:50,612 [Thread-10] INFO  o.red5.server.plugin.PluginRegistry - Destroying and cleaning up 0 plugins
2021-07-08 13:22:50,634 [Thread-9] INFO  i.antmedia.statistic.StatsCollector - Closing vertx 
2021-07-08 13:22:50,635 [Thread-9] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler#5778826f'
2021-07-08 13:22:50,636 [Thread-9] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2021-07-08 13:22:50,636 [Thread-9] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans
2021-07-08 13:22:50,636 [Thread-9] INFO  org.quartz.core.QuartzScheduler - Scheduler Red5_Scheduler_$_NON_CLUSTERED shutting down.
2021-07-08 13:22:50,637 [Thread-9] INFO  org.quartz.core.QuartzScheduler - Scheduler Red5_Scheduler_$_NON_CLUSTERED paused.
2021-07-08 13:22:50,637 [Thread-9] INFO  org.quartz.core.QuartzScheduler - Scheduler Red5_Scheduler_$_NON_CLUSTERED shutdown complete.
2021-07-08 13:22:55,569 [pool-6-thread-1] INFO  o.r.server.service.ShutdownServer - One or more contexts didn't close in the allotted time

```

**Comment by litzbalane2017** [comment]
I got the issue. I have a nodeJS listening to port 9999. Made the correction its now working. Thank you.

**Comment by justinkuhn** [comment]
I don't have a nodejs on that port and am experiencing the same issue.  How did you fix this?

**Comment by justinkuhn** [comment]
![image](https://user-images.githubusercontent.com/23298724/133648177-fb2d045a-4210-4efb-b0c5-813efcb448c3.png)

**Comment by mekya** [comment]
You're likely having some other problem @justinkuhn .

You can ask your questions to the Ant Media Server Google Group as well. 
https://groups.google.com/g/ant-media-server
