### ISSUE TITLE
AWS not working 

### ISSUE THREAD

**Issue by Nemra1** [ant-media/Ant-Media-Server#3506]
### Short description
its looks like AWS not getting my bucket information correctly
### Steps to reproduce
1. bucket endpoint= https://live-stream.s3.ap-southeast-1.amazonaws.com/
2. accessKey = Aw3ke6gwj4Qgxxxxxxxxxxxxxxxxxxx
3. Access Key =AKIAXVxxxxxxxxxxxxxxxxxxxx
4. bucket permission = READ/WRITE
5. bucket  access test = https://live-stream.s3.ap-southeast-1.amazonaws.com/21.wmv
6. setting  image = https://ibb.co/CPGbx6M
7. last version of antmedia  https://github.com/ant-media/Ant-Media-Server/releases/tag/ams-v2.3.3.1
8. I have no idea why i got bucket name is not exist when the same bucket working with same other tools
### Expected behavior
__Put as much detail here as possible__
### Actual behavior
__Put as much detail here as possible__ 
Same log for different aws buckets
### Logs
`
2021-08-06 09:48:47,425 [vert.x-eventloop-thread-2] io.antmedia.storage.AmazonS3StorageClient - Mp4 703282261328580_3.mp4 upload has started with key: streams/703282261328580_3.mp4
2021-08-06 09:48:47,662 [java-sdk-progress-listener-callback-thread] io.antmedia.storage.AmazonS3StorageClient - S3 - Error: Upload failed for 703282261328580_3.mp4 with key streams/703282261328580_3.mp4
2021-08-06 09:48:47,663 [vert.x-eventloop-thread-2] io.antmedia.storage.AmazonS3StorageClient - com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: Z31GFR4RWC99XV5Y; S3 Extended Request ID: ImN/zsB5U/CoDnB0L9ilyqs4CfnoO/0arTnt6IzNKymYCBQ8J9YkOojDHksomuj22b/tggMexZs=; Proxy: null), S3 Extended Request ID: ImN/zsB5U/CoDnB0L9ilyqs4CfnoO/0arTnt6IzNKymYCBQ8J9YkOojDHksomuj22b/tggMexZs=
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
        at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:394)
        at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5950)
        at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1812)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1772)
        at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:168)
        at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:148)
        at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:115)
        at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:45)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2021-08-06 09:48:55,479 [vert.x-eventloop-thread-2] io.antmedia.muxer.HLSMuxer - Deleting HLS files on exit
`
Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by yashtandon113** [comment]
Hi @Nemra1 
As per logs it seems that bucket name is not correct

2021-08-06 09:48:47,663 [vert.x-eventloop-thread-2] io.antmedia.storage.AmazonS3StorageClient - com.amazonaws.services.s3.model.AmazonS3Exception: **The specified bucket does not exist** (Service: Amazon S3; Status Code: 404; **Error Code: NoSuchBucket**; Request ID: Z31GFR4RWC99XV5Y; S3 Extended Request ID:

Could you please cross check once at your end?

**Comment by Nemra1** [comment]
@yashtandon113 my end is. Working good
https://live-stream.s3.ap-southeast-1.amazonaws.com/
Bucket name and the full end point is working and accessible...

**Comment by yashtandon113** [comment]
@Nemra1 
could you please share your AMS dashboard credentials on my e-email Id yash.tandon@antmedia.io so that we can look into your issue.

**Comment by Nemra1** [comment]
Problem is solved by replace 
bucket endpoint= https://live-stream.s3.ap-southeast-1.amazonaws.com/ = this wrong
bucket endpoint= https://s3.amazonaws.com/ = right one
and pls update the wiki page 
https://github.com/ant-media/Ant-Media-Server/wiki/Amazon-(AWS)-S3-Integration

**Comment by mekya** [comment]
Thank you @Nemra1 ,

Could you please review this doc?
https://github.com/ant-media/Ant-Media-Server/wiki/Record-Streams-to-S3-Compatible-Systems

Let me know if it's ok. After that I'm going to replace the doc

**Comment by Nemra1** [comment]
@mekya i guess you didn't seen my last reply i follow the aws wiki page and is wrong... I solve it by myself

**Comment by mekya** [comment]
Hi @Nemra1 , yes you're right. I see your last reply. We'll update the current wiki page(https://github.com/ant-media/Ant-Media-Server/wiki/Amazon-(AWS)-S3-Integration) with this new one (
https://github.com/ant-media/Ant-Media-Server/wiki/Record-Streams-to-S3-Compatible-Systems).

So I just would like to get some review/feedback from you if possible.
