### ISSUE TITLE
In Cluster when both H.264 and VP8 codecs are enabled, edge server cannot play the stream.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#3820]
### Short description
When AMS is running in cluster mode and if both H.264 and VP8 codecs are enabled in setting, the edge nodes cannot play the stream.

### Environment

* Ant Media Server version: 2.4.1
* Browser name and version: Chrome 

### Steps to reproduce
1. Setup AMS cluster with Origin and edge nodes.
2. Enabled H.264 and VP8 codec.
3. Play stream from edge node.

### Expected behavior
Edge node should be able to play the stream.

### Actual behavior
Edge node cannot play the stream.

 

### Logs
[vert.x-worker-thread-13] io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor - java.nio.BufferUnderflowException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at io.antmedia.enterprise.webrtc.WebRTCMuxer.sendAudioPacketInternal(WebRTCMuxer.java:359)
	at io.antmedia.enterprise.webrtc.WebRTCMuxer.sendAudioPacket(WebRTCMuxer.java:348)
	at io.antmedia.enterprise.webrtc.WebRTCMuxer.writePacket(WebRTCMuxer.java:534)
	at io.antmedia.enterprise.adaptive.audio.OpusEncoder.encode(OpusEncoder.java:137)
	at io.antmedia.enterprise.adaptive.base.AudioEncoder.resampleAndEncode(AudioEncoder.java:244)
	at io.antmedia.enterprise.adaptive.base.AudioEncoder.writeFrame(AudioEncoder.java:315)
	at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.writeRawAudio(WebRTCEncoderAdaptor.java:560)
	at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.encodeAudioRunner(WebRTCEncoderAdaptor.java:1548)
	at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.lambda$initAudioTrackExecutor$5(WebRTCEncoderAdaptor.java:1438)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.BufferUnderflowException
	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:294)
	at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:762)
	at io.antmedia.enterprise.cluster.webrtc.OriginServer.sendAudioPacket(OriginServer.java:134)
	at io.antmedia.enterprise.webrtc.WebRTCMuxer.lambda$sendAudioPacketInternal$2(WebRTCMuxer.java:360)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by golgetahir** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/449
