### ISSUE TITLE
Android SDK Conference Activity Exception after Disabling Audio/Video

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#3875]
**Reproduce Scenario:**
1) Creating the call Using ConferenceManager
2) Wait for the stream to be published
3) Now try to mute the audio/video

**Exception**:
021-12-31 11:50:22.711 22366-22366/com.roundesk_stee_sdk E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.roundesk_stee_sdk, PID: 22366
    java.lang.IllegalStateException: publish_view_renderer Already initialized
        at org.webrtc.EglRenderer.init(EglRenderer.java:212)
        at org.webrtc.EglRenderer.init(EglRenderer.java:259)
        at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:88)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
        at io.antmedia.webrtcandroidframework.WebRTCClient.init(WebRTCClient.java:240)
        at io.antmedia.webrtcandroidframework.ConferenceManager.createPeer(ConferenceManager.java:133)
        at io.antmedia.webrtcandroidframework.ConferenceManager.publishStream(ConferenceManager.java:221)
        at io.antmedia.webrtcandroidframework.ConferenceManager.onRoomInformation(ConferenceManager.java:289)
        at io.antmedia.webrtcandroidframework.WebSocketHandler.onTextMessage(WebSocketHandler.java:155)
        at de.tavendo.autobahn.WebSocketConnection.handleMessage(WebSocketConnection.java:351)
        at de.tavendo.autobahn.WebSocketConnection.access$1(WebSocketConnection.java:344)
        at de.tavendo.autobahn.WebSocketConnection$ThreadHandler.handleMessage(WebSocketConnection.java:536)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by prabhatsdp** [comment]
Facing the same issue on Android when joining conference after a few seconds or when someone else joins the same conference room.
