### ISSUE TITLE
Not able to RTMP broadcasting on ARM64 

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#4258]
### Short description

RTMP streaming is not working on ARM64-based operating systems.

### Environment

* Operating system and version: Ubuntu 20.04 arm64
* Java version: Java11
* Ant Media Server version: Community 2.4.3
* Browser name and version: Chrome

### Steps to reproduce
1. Install Ant Media Server 2.4.3 Community edition on ARM64.
2. Broadcast with RTMP by using FFmpeg or OBS

### Logs
```
2022-06-24 07:02:24,661 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.UnsatisfiedLinkError: 'long org.bytedeco.javacpp.Pointer.availablePhysicalBytes()'
	at org.bytedeco.javacpp.Pointer.availablePhysicalBytes(Native Method)
	at io.antmedia.SystemUtils.osAvailableMemory(SystemUtils.java:276)
	at io.antmedia.statistic.StatsCollector.lambda$start$0(StatsCollector.java:313)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:889)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:860)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:883)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by mekya** [comment]
It's fixed in the snapshot. I've tested and it's working for me. 
You can download the latest snapshot and test it.

Snapshot is available in [sonatype](https://oss.sonatype.org/#nexus-search;gav~io.antmedia~ant-media-server~~~~kw,versionexpand)
