### ISSUE TITLE
Logs packed with error: Text may not be null

### ISSUE THREAD

**Issue by lucas-mdiniz** [ant-media/Ant-Media-Server#4330]
When I see my server logs, there are a lot of errors like this:

2022-08-03 09:15:28,619 [Thread-6996607] ERROR i.a.console.rest.CommonRestService - java.lang.IllegalArgumentException: Text may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.entity.mime.content.StringBody.<init>(StringBody.java:156)
	at org.apache.http.entity.mime.MultipartEntityBuilder.addTextBody(MultipartEntityBuilder.java:121)
	at org.apache.http.entity.mime.MultipartEntityBuilder.addTextBody(MultipartEntityBuilder.java:126)
	at io.antmedia.console.rest.CommonRestService.sendUserInfo(CommonRestService.java:267)
	at io.antmedia.console.rest.CommonRestService$2.run(CommonRestService.java:238)

### Environment

* Operating system and version: Linux/UNIX
* Ant Media Server version: Enterprise Edition 2.4.3 20220418_2241

Is there a way to prevent these errors from happening?

**Comment by yashtandon113** [comment]
@lucas-mdiniz 
Thanks for reporting this issue. 
Could you please provide more details about this issue? Are these errors generated on a single standalone instance or in cluster mode? If it is in cluster mode, then how did you deploy the cluster?

**Comment by lucas-mdiniz** [comment]
Hello [yashtandon113](https://github.com/yashtandon113), thanks for answering.

Those errors are generated in cluster mode. 
To deploy we used a CloudFormation yaml based on this one:

https://github.com/ant-media/Scripts/blob/76aea1d155968cb58c5f40d5dea4a4fef0adbbb9/cloudformation/antmedia-aws-autoscale-template.yaml

**Comment by mekya** [comment]
Hi @lucas-mdiniz ,
Thank you for the issue. I know the cause of this problem. It's not a problem that may effect the streaming. 
But for sure, let us fix it. 

Regards,
A. Oguz
