### ISSUE TITLE
Unable to add Stream Source in cluster mode

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#4381]
### Short description
When a stream source is added as RTSP in a cluster structure, it cannot be added if it is not connected to the same server over LB.

### Environment

* Operating system and version: Ubuntu 20.04
* Java version:  11
* Ant Media Server version: 2.4.3 Enterprise
* Browser name and version: Chrome

### Steps to reproduce
1. Go to the Dashboard > WebRTCAppEE > Live Streams > New Live Streams > Stream Source
2. Try to add RTSP source

**ant-media-server.log**
```
2022-08-31 12:10:31,237 [Thread-238120] INFO  io.antmedia.rest.RestServiceBase - Version Name 2.4.3 Version Type Enterprise Edition
2022-08-31 12:10:31,237 [Thread-238120] ERROR i.a.console.rest.CommonRestService - java.lang.IllegalArgumentException: Text may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.entity.mime.content.StringBody.<init>(StringBody.java:156)
	at org.apache.http.entity.mime.MultipartEntityBuilder.addTextBody(MultipartEntityBuilder.java:121)
	at org.apache.http.entity.mime.MultipartEntityBuilder.addTextBody(MultipartEntityBuilder.java:126)
	at io.antmedia.console.rest.CommonRestService.sendUserInfo(CommonRestService.java:267)
	at io.antmedia.console.rest.CommonRestService$2.run(CommonRestService.java:238)
```
**Google Chrome Console Logs:**

 ```
 polyfills.a70767534e774649983f.js:1 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at Object.onLoad (scripts.b792d3abb262ccabf83e.js:1:108652)
    at scripts.b792d3abb262ccabf83e.js:1:109546
    at Array.forEach (<anonymous>)
    at new e (scripts.b792d3abb262ccabf83e.js:1:109499)
    at i.show (scripts.b792d3abb262ccabf83e.js:1:131056)
    at i.toggle (scripts.b792d3abb262ccabf83e.js:1:130350)
    at HTMLSelectElement.<anonymous> (scripts.b792d3abb262ccabf83e.js:1:133764)
    at Function.each (scripts.b792d3abb262ccabf83e.js:1:2977)
    at w.fn.init.each (scripts.b792d3abb262ccabf83e.js:1:1451)
    at e._jQueryInterface [as dropdown] (scripts.b792d3abb262ccabf83e.js:1:133547)
```

**Comment by mustafaboleken** [comment]
This issue fixed and merged in https://github.com/ant-media/Ant-Media-Server/pull/4347

**Comment by yashtandon113** [comment]
@mustafaboleken
As checked, this problem is still present in v2.5.0.

**Comment by mustafaboleken** [comment]
@mekya at that time, the problem is cors error

**Comment by mekya** [comment]
I think the CORS or similar problem happens when the cluster nodes has not internal IP addresses. If you reproduce the problem and need help, we can discuss together.
