### ISSUE TITLE
Error: Unhandled exception java.lang.NoSuchMethodError: 'void io.antmedia.muxer.HLSMuxer.

### ISSUE THREAD

**Issue by martinjack** [ant-media/Ant-Media-Server#4399]
### Short description
When enable Adaptive Streaming in WebRTCApp **H.264, vp8 encoder** , get exception error. What problem ? 

When use **H.265 encoder,** working success adaptive streaming .

### Environment

* Operating system and version: Ubuntu 20.04
* Java version:  openjdk 11.0.16 2022-07-19
* Ant Media Server version: 2.4.3
* Browser name and version: Chrome 104.0.0

### Steps to reproduce
1. Adaptive Streaming in WebRTCApp 
2. 360,800000,64000 or any other
3. Launch stream and i get an exception error

### Logs
[vert.x-eventloop-thread-2] io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NoSuchMethodError: 'void io.antmedia.muxer.HLSMuxer.<init>(io.vertx.core.Vertx, io.antmedia.storage.StorageClient, java.lang.String, int)'
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.initHLSMuxer(EncoderAdaptor.java:625)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.buildEncoders(EncoderAdaptor.java:510)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareEncoders(EncoderAdaptor.java:786)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareInternal(EncoderAdaptor.java:317)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepare(EncoderAdaptor.java:288)
	at io.antmedia.muxer.MuxAdaptor.prepareParameters(MuxAdaptor.java:1126)
	at io.antmedia.muxer.MuxAdaptor.execute(MuxAdaptor.java:970)
	at io.antmedia.muxer.MuxAdaptor.lambda$start$0(MuxAdaptor.java:1303)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
[RTMPConnectionExecutor-3] org.red5.server.net.rtmp.RTMPHandler - Not connected, closing connection

**Comment by martinjack** [comment]
Helped repackage ant-media-server.jar
