### ISSUE TITLE
Stream is overwriting previous Live Stream recording files

### ISSUE THREAD

**Issue by ashishkumar-07** [ant-media/Ant-Media-Server#4413]
We have use case where same stream channel will be re-used to stream the videos at multiple times. Recording of each stream should be uniquely identified. We have enabled property "append timestamp to recording". 
Issue is that timestamp is getting appended to only MP4 files however HLS chunks are getting overwritten as no timestamp is getting appended to them. This is causing issues. We are recording files in S3. While recording it should append timestamp to each file.
Better solution would be to save recording as <configured S3 bucket path>/<timestamp>/

**Comment by mekya** [comment]
Hi @ashishkumar-07 

Thank you for the issue. 

I'm not sure that timestamps will be appended to the HLS files because it breaks the live HLS playback.  

Alternatively, you can append ts files to the m3u8 file for the same stream id and you can have program datetime in the m3u8 file. Does that work for you?

Regards,
A.Oguz

**Comment by ashishkumar-07** [comment]
Please see below. Stream was stopped and started again. We can clearly see that files are overwritten. This situation can arise due to some network interruption also. 
![image]((https://user-images.githubusercontent.com/52857452/192427748-6d96d54f-02aa-490f-8d38-e4786b94bc4b.png))

We are thinking to implement a solution based on events. Whenever there is a record complete event we will move the files to some other bucket. But this does not look reliable. We are not sure when we are going to get events. Moreover there is no event for HLS upload complete. There are event only for MP4 upload complete. So what if MP4 record complete arrives before HLS file uploads.
Recording HLS files to S3 with some timestamp prefix or suffix is supported by every AWS media service(e.g. IVS). This is a must have feature.

**Comment by mekya** [comment]
Let us think that about the implementation. 

As a workaround solution. 
If the old ts files are not overwritten and new ts files are recorded consecutively and appended to current m3u8 file, does that work for you?

In short, you'll have the following files in the your scenario and demo.m3u8 will have all ts files listed below

- demo.m3u8
- demo0000.ts
- demo0001.ts
- demo0002.ts
- demo0003.ts
- demo0004.ts
- demo0005.ts
- demo0006.ts
- demo0007.ts
- demo0008.ts

**Comment by ashishkumar-07** [comment]
Yes, this solution will work.

**Comment by Mohit-3196** [comment]
Hi @ashishkumar-07 ,
The .ts files can be appended to the same .m3u8 file with the same streamId.

To do so, edit and add the following hlsflag setting to the red5-web.properties file in the /usr/local/antmedia/webapps/app-name/WEB-INF/ folder.
`settings.hlsflags=+append_list`

Also, make the below settings
`settings.hlsPlayListType=event`
`settings.deleteHLSFilesOnEnded=false`

Then, restart the AMS with
`sudo service antmedia restart`

Let me know if this works for you.

Thank you

**Comment by mekya** [comment]
Thank you @Mohit-3196 for being responsive. 

Let us know if this works for you @ashishkumar-07

**Comment by ashishkumar-07** [comment]
No it did not work. After enabling above settings we are not able to play any stream. Stream is stuck in Preparing stage.

**Comment by ashishkumar-07** [comment]
Also I did not understand the point for setting.
settings.deleteHLSFilesOnEnded=false
Doing this fill up the disk space. We are already uploading the files on S3 then why we have to keep these files.

**Comment by Mohit-3196** [comment]
Hi @ashishkumar-07 ,
These settings have not much to do with the live streams playback. So if it's happening for you then we can check it together.
Also you can keep `settings.deleteHLSFilesOnEnded=true` for HLS uploads.

Thank you

**Comment by mekya** [comment]
Thank you guys @ashishkumar-07 @Mohit-3196 .
Let's continue to resolve the issue completely.

**Comment by ashishkumar-07** [comment]
Hi @Mohit-3196 ,

Please below snapshot and log files.

Server Log :
2022-10-17 07:11:07,510 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2022-10-17 07:12:06,970 [pool-4-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
2022-10-17 07:12:59,240 [https-jsse-nio2-0.0.0.0-5443-exec-8] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened session:0 user-agent:[Mozilla/5.0 (Windows NT 10.0; Wi
n64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36]
2022-10-17 07:13:09,032 [https-jsse-nio2-0.0.0.0-5443-exec-7] INFO  i.a.e.w.c.VirtualVideoEncoderFactory - Adding H264 Encoder to the supported codecs
2022-10-17 07:13:09,044 [https-jsse-nio2-0.0.0.0-5443-exec-7] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: java.lang.RuntimeException: Could not initialize class org.b
ytedeco.ffmpeg.global.avcodec
        at org.apache.tomcat.websocket.pojo.PojoMessageHandlerBase.handlePojoMethodException(PojoMessageHandlerBase.java:119)
        at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:106)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:414)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1638)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2022-10-17 07:11:07,510 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2022-10-17 07:12:06,970 [pool-4-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
2022-10-17 07:12:59,240 [https-jsse-nio2-0.0.0.0-5443-exec-8] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened session:0 user-agent:[Mozilla/5.0 (Windows NT 10.0; Wi
n64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36]
2022-10-17 07:13:09,032 [https-jsse-nio2-0.0.0.0-5443-exec-7] INFO  i.a.e.w.c.VirtualVideoEncoderFactory - Adding H264 Encoder to the supported codecs
2022-10-17 07:13:09,044 [https-jsse-nio2-0.0.0.0-5443-exec-7] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: java.lang.RuntimeException: Could not initialize class org.b
ytedeco.ffmpeg.global.avcodec
        at org.apache.tomcat.websocket.pojo.PojoMessageHandlerBase.handlePojoMethodException(PojoMessageHandlerBase.java:119)
        at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:106)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:414)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1638)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avcodec
        at io.antmedia.plugin.PacketFeeder.<init>(PacketFeeder.java:27)
        at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.init(WebRTCEncoderAdaptor.java:1070)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.processPublishCommand(WebSocketEnterpriseHandler.java:1342)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.onMessage(WebSocketEnterpriseHandler.java:311)
        at io.antmedia.enterprise.streamapp.WebSocketLocalHandler.onMessage(WebSocketLocalHandler.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:104)
        ... 26 more

2022-10-17 07:13:09,046 [https-jsse-nio2-0.0.0.0-5443-exec-7] INFO  i.a.e.adaptive.WebRTCEncoderAdaptor - entering stop() for null stopCompetely:false
2022-10-17 07:13:09,047 [https-jsse-nio2-0.0.0.0-5443-exec-7] ERROR o.a.t.w.pojo.PojoEndpointBase - Failed to call onClose method of POJO end point for POJO of type [io.ant
media.enterprise.streamapp.WebSocketLocalHandler]
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.websocket.pojo.PojoEndpointBase.onClose(PojoEndpointBase.java:107)
        at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:759)
        at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:740)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.close(WsHttpUpgradeHandler.java:250)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:159)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)

        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.addPublisherToBeStopped(WebSocketEnterpriseHandler.java:1534)
        at io.antmedia.enterprise.webrtc.WebRTCPublishStreamInfoListener.streamingBeingStop(WebRTCPublishStreamInfoListener.java:38)
        at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.stop(WebRTCEncoderAdaptor.java:1918)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.stopPublisherOperations(WebSocketEnterpriseHandler.java:1463)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.processStopEverything(WebSocketEnterpriseHandler.java:1434)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.onClose(WebSocketEnterpriseHandler.java:127)
        at io.antmedia.enterprise.streamapp.WebSocketLocalHandler.onClose(WebSocketLocalHandler.java:52)
        ... 26 common frames omitted
2022-10-17 07:13:09,047 [https-jsse-nio2-0.0.0.0-5443-exec-7] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.addPublisherToBeStopped(WebSocketEnterpriseHandler.java:1534)
        at io.antmedia.enterprise.webrtc.WebRTCPublishStreamInfoListener.streamingBeingStop(WebRTCPublishStreamInfoListener.java:38)
        at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.stop(WebRTCEncoderAdaptor.java:1918)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.stopPublisherOperations(WebSocketEnterpriseHandler.java:1463)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.processStopEverything(WebSocketEnterpriseHandler.java:1434)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.onClose(WebSocketEnterpriseHandler.java:127)
        at io.antmedia.enterprise.streamapp.WebSocketLocalHandler.onClose(WebSocketLocalHandler.java:52)
        ... 26 more

2022-10-17 07:14:19,325 [https-jsse-nio2-0.0.0.0-5443-exec-4] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened session:1 user-agent:[Mozilla/5.0 (Windows NT 10.0; Wi
n64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36]
2022-10-17 07:14:19,640 [https-jsse-nio2-0.0.0.0-5443-exec-6] INFO  i.a.e.w.c.VirtualVideoEncoderFactory - Adding H264 Encoder to the supported codecs
2022-10-17 07:14:19,640 [https-jsse-nio2-0.0.0.0-5443-exec-6] ERROR i.a.e.w.WebSocketEnterpriseHandler - Sending str




**Error Log:**

`Oct 17, 2022 7:13:09 AM org.apache.tomcat.websocket.pojo.PojoEndpointBase onClose
SEVERE: Failed to call onClose method of POJO end point for POJO of type [io.antmedia.enterprise.streamapp.WebSocketLocalHandler]
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.websocket.pojo.PojoEndpointBase.onClose(PojoEndpointBase.java:107)
        at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:759)
        at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:740)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.close(WsHttpUpgradeHandler.java:250)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:159)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1638)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1125)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:587)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:565)
        at org.apache.tomcat.util.net.SecureNio2Channel$1.completed(SecureNio2Channel.java:1010)
        at org.apache.tomcat.util.net.SecureNio2Channel$1.completed(SecureNio2Channel.java:938)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.addPublisherToBeStopped(WebSocketEnterpriseHandler.java:1534)
        at io.antmedia.enterprise.webrtc.WebRTCPublishStreamInfoListener.streamingBeingStop(WebRTCPublishStreamInfoListener.java:38)
        at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.stop(WebRTCEncoderAdaptor.java:1918)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.stopPublisherOperations(WebSocketEnterpriseHandler.java:1463)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.processStopEverything(WebSocketEnterpriseHandler.java:1434)
        at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.onClose(WebSocketEnterpriseHandler.java:127)
        at io.antmedia.enterprise.streamapp.WebSocketLocalHandler.onClose(WebSocketLocalHandler.java:52)
        ... 26 more`

**Comment by Mohit-3196** [comment]
Hi @ashishkumar-07 ,
It seems that these logs are not about this streamId. Also it will be more helpful if you can provide the entire ant-media-server.log file.
Also as I requested earlier, let's meet on a google meet call and we can check these settings together and we can make it to work. So please let me know about your availability.

Thank you again

**Comment by Mohit-3196** [comment]
Hi @ashishkumar-07 ,
How are you?

Please let me know if you had any opportunity to check. And we can always check it together as well.

Thank you

**Comment by oleul05** [comment]
I am using Cluster mode with MongDB and set hlsflags=+append_list in Appsetting. It is working only when settings.deleteHLSFilesOnEnded=false
But when I make the value true it is not working.
As I am already uploading those files into Wasabi in real time so I don't need to keep all the .ts files in Server. Also I just want to keep only last 5 file in stream directory and want to delete the others file. How we can achieve this.

**Comment by mekya** [comment]
Hi @oleul05 ,

I think you can keep
```
settings.hlsflags=+append_list+delete_segments
settings.hlsListSize=5
settings.deleteHLSFilesOnEnded=false
``` 

Don't set anything to `settings.hlsPlayListType`

It will delete the ts files automatically that is out of the list in the m3u8 file.

If it does not work for you, we can schedule a meeting to investigate 

Regards,
A. Oguz

**Comment by oleul05** [comment]
Hello A. Oguz,
I have set all the above configuration but in that case m3u8 file doesn't contain all the .ts media files.
Regards,
Ole

**Comment by mekya** [comment]
Hi @oleul05 ,

Let me try to confirm what I understand. 

You want m3u8 file contains all the .ts media files and keep only last 5 file in stream directory. 
Then m3u8 file does not play on the server side. 

> As I am already uploading those files into Wasabi in real time.
How are you uploading in real-time?  If you have some custom script, then the files can be deleted there as well. 

Maybe I should ask, What would you like to achieve? If I know your goal, I may recommend some other things as well.

**Comment by ashishkumar-07** [comment]
These settings did not work me properly. I will try again on new version. However I have further question.
Suppose, I enable below settings.
- HLS append
- upload to S3
- delete from local disk

Videos is streamed for 2 hours and then stopped. Everything will get recorded in S3(including the master file) and will be deleted from Local. After some time video streaming started again. Now will it create a new master HLS file or will it append to existing master file which was already uploaded to S3 or will it overwrite the files?

**Comment by Mohit-3196** [comment]
Hi @ashishkumar-07 ,

> Videos is streamed for 2 hours and then stopped. Everything will get recorded in S3(including the master file) and will be deleted from Local. After some time video streaming started again. Now will it create a new master HLS file or will it append to existing master file which was already uploaded to S3 or will it overwrite the files?

With the append list property set, `settings.hlsflags=+append_list`
It will append the .ts files in the existing master file without overwriting the existing .ts files.

Like the MP4 files, date and time can be added to the HLS files as well with this property https://antmedia.io/javadoc/io/antmedia/AppSettings.html#addDateTimeToHlsFileName
We have discussed this here as well #4549 FYI, please.

If they do not work for you then we can also make a call and go through it together.

Thank you

**Comment by mekya** [comment]
Hi @Mohit-3196 ,

Just a point. If the files are recorded to S3 and there is no file on local disk,  `settings.hlsflags=+append_list` will still work?

**Comment by Mohit-3196** [comment]
Hi,
No, if there are no files on the local disk, the append list will not work and the files will get HLS files will get overwritten. 
I think for uploading to S3, one possible solution is to make:
`settings.addDateTimeToHlsFileName=true`
`settings.hlsPlayListType=event`
and set,
`settings.deleteHLSFilesOnEnded=true` as well
Now when the stream ends, the HLS files will get uploaded to S3 and deleted from local storage, and when another stream is started with the same streamId, since the time will be different it will create a different .m3u8 file without overwriting the existing master file content.

The S3 fuse is another option to mount the S3 bucket as a file system directly.

**Comment by mekya** [comment]
Hey @ashishkumar-07,

Is the solution provided by @Mohit-3196 above work for you?

**Comment by Mohit-3196** [comment]
Hi everyone,
I'm closing this ticket for inactivity.
Please feel free to reopen it as needed.

Thank you.
