### ISSUE TITLE
How to run unit test in terminal?

### ISSUE THREAD

**Issue by ducminhgd** [ant-media/Ant-Media-Server#4440]
I open project with IntelliJ IDEA and I can run unit test on the IDE. But in terminal I always get this result:

```shell
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ ant-media-server ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

What I tried:
1. `mvn test`
2. `mvn -Dtest="io.antmedia.test.*" test`
3. `mvn clean build test`

More info:

```shell
java --version
java 19 2022-09-20
Java(TM) SE Runtime Environment (build 19+36-2238)
Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)
```

## Update on 2022-10-05

I check `surefire` logs, I found this `Error: could not open '{argLine}'`. I surf the Internet and found that the `@{argLine}`, which is defined in `pom.xml` file will be late-replaced with `javaagent` when `jacoco` prepare agent.

```xml
...
        <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useSystemClassLoader>false</useSystemClassLoader>
                    <argLine>@{argLine} --illegal-access=permit -Xmx750M -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -Djava.library.path=${project.basedir}/src/main/server/lib/native-linux-x86_64</argLine>
                	<skipAfterFailureCount>1</skipAfterFailureCount>
                </configuration>
            </plugin>
...
```

I tried to run `mvn jacoco:prepare-agent` before `mvn test` but it was not help

Read more:

1. https://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html
2. https://stackoverflow.com/questions/49529614/maven-surefire-plugin-is-not-using-argline-property-provided-by-jacoco
3. https://asbnotebook.com/using-jacoco-and-surefire-maven-plugins-with-spring-boot/
4. https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#argLine
5. https://stackoverflow.com/questions/46489455/append-the-value-of-argline-param-in-maven-surefire-plugin

**Comment by Mohit-3196** [comment]
Hi @ducminhgd ,
How are you?

Thank you for writing this issue.

Can you please run below command and try
`mvn org.jacoco:jacoco-maven-plugin:prepare-agent test`
We are using jacoco for java code coverage

Please let me know if it works.

Thank you

**Comment by ducminhgd** [comment]
> Hi @ducminhgd , How are you?
> 
> Thank you for writing this issue.
> 
> Can you please run below command and try `mvn org.jacoco:jacoco-maven-plugin:prepare-agent test` We are using jacoco for java code coverage
> 
> Please let me know if it works.
> 
> Thank you

I ran the command above and get this result

```
[ERROR] Tests run: 84, Failures: 2, Errors: 1, Skipped: 60
```
-> Just 147 test cases

But when I use VSCode Tests Discovery, there are 556 test cases.

I have no idea why they are difference, which is the true number of test cases?

Thank for your supporting!

**Comment by ducminhgd** [comment]
Hi @Mohit-3196 , I'm running Ant Media Server Community Edition. I searched "@Test" and there are 480 occurrences and some of them are `//@Test` or `//    @Test`

**Comment by burak-58** [comment]
Hi @ducminhgd,
Thanks for your interest.
Please send whole report and let us check. 
Also let me remind that some of the tests are integration tests which require a running AMS instance on the same machine. Also this running server should be installed fresh.

**Comment by ducminhgd** [comment]
@burak-58 , please take look at this link https://pastebin.com/D36K6twp

**Comment by burak-58** [comment]
Hi @ducminhgd ,
The line you sent was only for the test in the RestServiceV2Test class. In the report, there are some other line similar to one you sent.

**Comment by ducminhgd** [comment]
Hi @burak-58,

Thank you for your reply.

I ran the command `mvn org.jacoco:jacoco-maven-plugin:prepare-agent test` at the root directory of project and it is all the log lines that I got.

Does the command above run all test cases in source code? Or should I declare a specific package to test in each test run?

**Comment by Mohit-3196** [comment]
Hi @ducminhgd ,
Can we check this together in call?
If you are available tomorrow at 14:00(GMT+3) , please let me know and I'll schedule a meeting and check this together.

Thank you

**Comment by ducminhgd** [comment]
> Hi @ducminhgd , Can we check this together in call? If you are available tomorrow at 14:00(GMT+3) , please let me know and I'll schedule a meeting and check this together.
> 
> Thank you

Hi @Mohit-3196 ,

My apology, I'm not available at that moment. Please take a look at this [screen recorder](https://drive.google.com/file/d/1r7G_AFtHq3aNLTglmA2vNFFK-uAZKnzv/view?usp=sharing).

**Comment by burak-58** [comment]
Hi @ducminhgd,
I saw such logs in the video:
unsupported class file major version 63
Problem may be related with the java version.

Let's book a free consultancy meeting from this link and check it together.
https://calendly.com/antmedia

**Comment by mekya** [comment]
Hi Terry,

Thank you for the meeting. In the meeting, we find out that the library cannot be loaded. 

One of my colleague has experienced the same issue in Apple M1 Pro. He has resolved the issue by using Rosetta and installing Java x86_64. I hope it helps.  If it is not resolved, we can schedule another meeting to continue. 

Regards
Oguz

**Comment by ducminhgd** [comment]
Hi @mekya ,

Here is my environment

```shell
➜ mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven-3.8.6
Java version: 11.0.16.1, vendor: Microsoft, runtime: /Users/ducminhgd/.sdkman/candidates/java/11.0.16.1-ms
Default locale: en_VN, platform encoding: UTF-8
OS name: "mac os x", version: "13.0", arch: "aarch64", family: "mac"
```

And this is the result

```shell
➜ mvn org.jacoco:jacoco-maven-plugin:prepare-agent test
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.antmedia:ant-media-server:jar:2.6.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ io.antmedia:ant-media-server:${project.parent.version}, /Users/ducminhgd/projects/ant-media/Ant-Media-Server/pom.xml, line 13, column 14
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] --------------------< io.antmedia:ant-media-server >--------------------
[INFO] Building Ant Media Server 2.6.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (default-cli) @ ant-media-server ---
[INFO] argLine set to -javaagent:/Users/ducminhgd/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/Users/ducminhgd/projects/ant-media/Ant-Media-Server/target/jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ant-media-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ ant-media-server ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (base-compile) @ ant-media-server ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ant-media-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 40 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ ant-media-server ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ ant-media-server ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.170 s
[INFO] Finished at: 2022-11-23T13:46:51+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project ant-media-server: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/ducminhgd/projects/ant-media/Ant-Media-Server/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] ExecutionException
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] ExecutionException
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:657)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by mekya** [comment]
hi @ducminhgd ,

It seems that architecture is `arch: "aarch64"`.  Could you please install java and maven after opening the rosetta terminal?  

```
➜ mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven-3.8.6
Java version: 11.0.16.1, vendor: Microsoft, runtime: /Users/ducminhgd/.sdkman/candidates/java/11.0.16.1-ms
Default locale: en_VN, platform encoding: UTF-8
OS name: "mac os x", version: "13.0", arch: "aarch64", family: "mac"
```

Regards,
Oguz

**Comment by ducminhgd** [comment]
I have just run with Rosetta

```bash
➜ mvn --version                                        
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven-3.8.6
Java version: 11.0.16, vendor: Amazon.com Inc., runtime: /Users/ducminhgd/.sdkman/candidates/java/11.0.16-amzn
Default locale: en_VN, platform encoding: UTF-8
OS name: "mac os x", version: "13.0.1", arch: "x86_64", family: "mac"
```

And here is the result

```bash
[WARN] [SpringContextShutdownHook] org.springframework.beans.factory.support.DisposableBeanAdapter - Invocation of destroy method failed on bean with name 'web.scope': java.lang.RuntimeException: org.quartz.SchedulerException: The Scheduler has been shutdown.
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ConsoleAppRestServiceTest.beforeClass:148 Connect to 127.0.0.1:5080 [/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR] Errors: 
[ERROR]   RestServiceV2Test.beforeClass:141 NullPointer
[ERROR]   StreamSchedularUnitTest.testBandwidth:852 » ConditionTimeout Condition with la...
[INFO] 
[ERROR] Tests run: 84, Failures: 1, Errors: 2, Skipped: 59
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.099 s
[INFO] Finished at: 2022-11-29T09:54:00+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project ant-media-server: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/ducminhgd/projects/ant-media/Ant-Media-Server/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Here is the log file of surefire

```log
# Created at 2022-11-29T09:25:46.864
Error: could not open `{argLine}`
```

The same issue with Windows 11 WSL2

**Comment by mekya** [comment]
Then there is a progress.  It tries to run the test and it fails. It may have two reasons Ant Media Server is not running locally,  some tests can only run in CI environment and definitely `prepare-agent` is not supplied 

Please try to run with the following command to run a simple unit test. 

```
mvn org.jacoco:jacoco-maven-plugin:prepare-agent clean test -Dtest=AMSShutdownManagerUnitTest
```

**Comment by ducminhgd** [comment]
I try to run a simple unit test and it's OK. I started a docker container as local AMS before running unit test.

The problem I get stuck is number of test cases between running terminal and running in IDEs are different.

**Comment by mekya** [comment]
Hi @ducminhgd,

The correct method is running the tests in the terminal. IDE likely just tests some subset of the tests. 
You can take a look at following file how CI runs the command 
https://github.com/ant-media/Ant-Media-Server/blob/master/.travis.yml#L129
