### ISSUE TITLE
Ticket 73478 - the audio stops and lost communication with our listeners.

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#4499]
seHandler - Error: EOFException: 
2022-10-22 23:09:52,869 [pool-4-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
2022-10-22 23:10:27,352 [http-nio2-0.0.0.0-5080-exec-7] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: IOException: Broken pipe
2022-10-22 23:10:27,353 [http-nio2-0.0.0.0-5080-exec-7] ERROR i.a.w.WebSocketCommunityHandler - java.io.IOException: java.io.IOException: Broken pipe
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:327)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:254)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:195)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
	at io.antmedia.websocket.WebSocketCommunityHandler.sendMessage(WebSocketCommunityHandler.java:300)
	at io.antmedia.websocket.WebSocketCommunityHandler.sendPongMessage(WebSocketCommunityHandler.java:254)
	at io.antmedia.enterprise.webrtc.WebSocketEnterpriseHandler.onMessage(WebSocketEnterpriseHandler.java:205)
	at io.antmedia.enterprise.streamapp.WebSocketLocalHandler.onMessage(WebSocketLocalHandler.java:84)
	at jdk.internal.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:104)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:414)
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1638)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1125)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:587)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:565)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implWrite(UnixAsynchronousSocketChannelImpl.java:701)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:383)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:388)
	at org.apache.tomcat.util.net.Nio2Channel.write(Nio2Channel.java:166)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper.doWrite(Nio2Endpoint.java:1196)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:718)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:671)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper.flushBlocking(Nio2Endpoint.java:1239)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:661)
	at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:98)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:512)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:314)
	... 35 more

2022-10-22 23:10:27,354 [http-nio2-0.0.0.0-5080-exec-7] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: java.io.IOException: The transformer has been closed and may no longer be used
	at org.apache.tomcat.websocket.PerMessageDeflate.getMoreData(PerMessageDeflate.java:208)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:427)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1638)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1125)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:587)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:565)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: Inflater has been closed
	at java.base/java.util.zip.Inflater.ensureOpen(Inflater.java:740)
	at java.base/java.util.zip.Inflater.inflate(Inflater.java:377)
	at org.apache.tomcat.websocket.PerMessageDeflate.getMoreData(PerMessageDeflate.java:203)
	... 22 more

2022-10-22 23:11:51,110 [http-nio2-0.0.0.0-5080-exec-10] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: EOFException: 
2022-10-22 23:12:02,696 [http-nio2-0.0.0.0-5080-exec-13] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: EOFException: 
2022-10-22 23:13:53,110 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:0 process cpu load:1 available memory: 1883628 KB used memory(RSS): 1683628 KB
2022-10-22 23:13:53,110 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2022-10-22 23:15:16,306 [http-nio2-0.0.0.0-5080-exec-2] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: EOFException: 
2022-10-22 23:18:33,161 [http-nio2-0.0.0.0-5080-exec-9] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: EOFException: 
2022-10-22 23:18:35,887 [http-nio2-0.0.0.0-5080-exec-12] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: EOFException: 
2022-10-22 23:18:53,110 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:1 process cpu load:0 available memory: 1876652 KB used memory(RSS): 1691268 KB
2022-10-22 23:18:53,111 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
2022-10-22 23:19:06,380 [http-nio2-0.0.0.0-5080-exec-14] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: EOFException: 
2022-10-22 23:19:44,674 [http-nio2-0.0.0.0-5080-exec-11] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:7, serverValue:224198}] to [media-server-db-lb.zecfl.mongodb.net:27017](http://media-server-db-lb.zecfl.mongodb.net:27017/)
2022-10-22 23:19:52,869 [pool-4-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
2022-10-22 23:20:26,504 [http-nio2-0.0.0.0-5080-exec-6] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: EOFException: 
2022-10-22 23:20:53,963 [http-nio2-0.0.0.0-5080-exec-7] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened session:719 user-agent:[Mozilla/5.0 (Linux; Android 12; SM-G975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[106.0.0.0](http://106.0.0.0/) Mobile Safari/537.36]
2022-10-22 23:21:27,944 [http-nio2-0.0.0.0-5080-exec-8] ERROR i.a.e.w.WebSocketEnterpriseHandler - Error: EOFException: 

This is the resources consumption on the servers in last 6h:

Edge (4 vcpu, 8GB)

image.png
image.png
image.png

Origin (2 vcpu, 4GB)

image.png
image.png
image.png

Nginx (4 vcpu, 8GB)

image.png
image.png
image.png

I don't know what could happen because I'm not seeing stress in the machines.

**Comment by SelimEmre** [comment]
Hi @akiziltoprak,

Have a good day. This was related to the high load on the server side. There was an issue with Nginx configurations as well. All publishers/viewers were going origin instance. When we figured out and fixed it, we didn't encounter this kind of issue.

Best Regards,
Selim
