### ISSUE TITLE
Update ffmpeg, link errors with libva >=2.15

### ISSUE THREAD

**Issue by vigilyn** [ant-media/Ant-Media-Server#4520]
Please update ffmpeg, it has bindings to libva that no longer exist.

Using the new libva, ant media server fails to start.

`Caused by: java.lang.UnsatisfiedLinkError: /usr/local/antmedia/.javacpp/cache/ffmpeg-4.3.2-1.5.5-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: /lib/x86_64-linux-gnu/libva-x11.so.2: undefined symbol: va_fool_postp
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1668)
`

https://github.com/intel/libva/releases/tag/2.15.0 ->  `Deprecation: remove the va_fool support`, July 2022

**Comment by mekya** [comment]
Yes, you're right. It's also in our pipeline but let's make it faster

**Comment by mekya** [comment]
Hi @vigilyn ,

I'm closing this issue because all PRs related to FFmpeg update is merged to the master branches. 
The recent ffmpeg version is 5.1.2

Please let me know if you have a question or any issue 

Regards,
Oguz
