### ISSUE TITLE
Unable to re-publish stream multiple times

### ISSUE THREAD

**Issue by tomyates** [ant-media/Ant-Media-Server#4771]
### Short description
We're using React Native app with @antmedia/react-native-ant-media 1.0.4 to connect to our Ant Media Server.
If we publish a stream once everything works fine.
However, if we publish, stop and re-publish several times, the stream will stop streaming and it's impossible to re-stream without force closing the entire app. It normally happens after 3rd or 4th time, but it's not consistent.

The error we get in AntMedia is:

```
2023-01-25 14:55:38,697 [vert.x-worker-thread-57] ERROR i.a.e.adaptive.audio.OpusEncoder - Cannot send audio frame to encoder for stream index 0 error is End of file for stream:00363dc5-ae67-4767-83af-f418943edab8_AUDIO
2023-01-25 14:55:44,918 [vert.x-worker-thread-10] ERROR i.a.e.adaptive.WebRTCEncoderAdaptor - java.lang.NullPointerException: This pointer address is NULL.
	at org.bytedeco.ffmpeg.avutil.AVFrame.format(Native Method)
	at io.antmedia.enterprise.adaptive.base.AudioEncoder.writeFrame(AudioEncoder.java:276)
	at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.writeRawAudio(WebRTCEncoderAdaptor.java:563)
	at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.encodeAudioRunner(WebRTCEncoderAdaptor.java:1552)
	at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.lambda$initAudioTrackExecutor$5(WebRTCEncoderAdaptor.java:1442)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

2023-01-25 14:55:44,924 [vert.x-worker-thread-5] ERROR i.a.e.adaptive.audio.OpusEncoder - Cannot send audio frame to encoder for stream index 0 error is End of file for stream:00363dc5-ae67-4767-83af-f418943edab8_AUDIO
````

### Environment

* Operating system and version: React Native running in iOS device @antmedia/react-native-ant-media 1.0.4
* Ant Media Server version:  AntMedia Server Enterprise Edition 2.4.3 20220418_2241

### Steps to reproduce
1. Publish stream from react native, stop stream. Wait a few seconds. Publish stream, Stop stream. Repeat until failure.

### Expected behavior
I'd expect that we could publish and stop as many times as we like without failure. 

### Actual behavior
Stream stops publishing and dissapears from list of streams in AntMedia. The UI in ReactNative becomes unresponsive.

**Comment by mekya** [comment]
Hi @tomyates ,

Thank you for the issue. It's moved to the backlog to schedule.

**Comment by lastpeony** [comment]
I tested this with this PR which includes updates to react-native webrtc sdk. I could not reproduce on my real android device.
I spammed start/stop and behaviour was expected. app did not crash and no errors on server side.

https://github.com/ant-media/WebRTC-React-Native-SDK/pull/11

**Comment by mustafaboleken** [comment]
After this issue was created, we just updated our React Native SDK and it looks like it is solved. If you're having it again, please feel free to open this ticket.
