### ISSUE TITLE
Error running load test tool

### ISSUE THREAD

**Issue by unicornsoftwareinc** [ant-media/Ant-Media-Server#4781]
### Short description
Hi there, I'm running into an issue when trying to publish a test stream using the load test tool. 

Command I'm running: ./run.sh -f test.mp4 -m publisher -p 80 -n 1 -s REDACTED

Error message pasted below:

```
- webSockAdr:REDACTED
- is sequre:false
- logLevel:LS_ERROR
- stream id:myStream
- stream source:test.mp4
- mode:PUBLISHER
- use ui:true
- port:80
- verbose:false
- load:1
- loop:false
- codec:H264
- main track:null
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/me/Desktop/webrtctest/libs/logback-classic-1.2.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/me/Desktop/webrtctest/libs/slf4j-jdk14-1.7.28.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path: libs/native
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
	at java.base/java.lang.System.loadLibrary(System.java:2047)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1718)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1328)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:495)
	at java.base/java.lang.Class.forName(Class.java:474)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1200)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at org.bytedeco.ffmpeg.avformat.AVFormatContext.<clinit>(AVFormatContext.java:36)
	at io.antmedia.webrtctest.FileReader.<init>(FileReader.java:19)
	at io.antmedia.Starter.<init>(Starter.java:36)
	at io.antmedia.Starter.main(Starter.java:89)
Caused by: java.lang.UnsatisfiedLinkError: no avutil in java.library.path: libs/native
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
	at java.base/java.lang.System.loadLibrary(System.java:2047)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1718)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1239)
	... 11 more
```

### Environment
* Operating system and version: macOS Ventura 13.0
* Java version: 19.0.2
* Ant Media Server version: 2.5.3

### Steps to reproduce
1. Downloaded load test tool on to my mac
2. Ran the command mentioned above
3. 

### Expected behavior
Load test tool should work.

### Actual behavior
Load test tool immediately shows error message and terminates

**Comment by muratugureminoglu** [comment]
Hi @unicornsoftwareinc 

It 's not working because you are using the latest Java version. Please install Java 11 then try it again.

https://resources.antmedia.io/docs/load-testing

**Comment by unicornsoftwareinc** [comment]
Hi @muratugureminoglu , I'm unable to get this working on my Mac even with Java 11 installed. I ended up installing on a brand new AWS ubuntu instance and it doesn't seem to be working there either. These are the messages I'm seeing when trying to publish:

```
[-f, test.mp4, -i, stream1, -m, publisher, -p, 80, -n, 1, -s, 54.146.132.192]
~~~~~~~~ Start (1915910607) ~~~~~~~~
Settings:

- webSockAdr:54.146.132.192
- is sequre:false
- logLevel:LS_ERROR
- stream id:stream1
- stream source:test.mp4
- mode:PUBLISHER
- use ui:true
- port:80
- verbose:false
- load:1
- loop:false
- codec:H264
- main track:null
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/webinarkit/webrtctest/libs/logback-classic-1.2.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/webinarkit/webrtctest/libs/slf4j-jdk14-1.7.28.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:02:26.41, start: 0.000000, bitrate: 876 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 777 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 90 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
04:54:37.782 [pool-3-thread-1] INFO org.webrtc.Logging - Tag:NativeLibrary - Message:Loading native library: jingle_peerconnection_so
04:54:37.799 [pool-3-thread-1] INFO org.webrtc.Logging - Tag:NativeLibrary - Message:Loading library: jingle_peerconnection_so
04:54:37.801 [pool-3-thread-1] INFO org.webrtc.Logging - Tag:PeerConnectionFactory - Message:PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
04:54:37.808 [pool-3-thread-1] INFO org.webrtc.Logging - Tag:JavaAudioDeviceModule - Message:createAudioDeviceModule
04:54:37.808 [pool-3-thread-1] INFO org.webrtc.Logging - Tag:JavaAudioDeviceModule - Message:HW NS will not be used.
04:54:37.808 [pool-3-thread-1] INFO org.webrtc.Logging - Tag:JavaAudioDeviceModule - Message:HW AEC will not be used.
04:54:37.818 [pool-3-thread-1] INFO io.antmedia.webrtctest.WebRTCManager - Creating peerconnection hascode:1381866548 time:1675054477818
04:54:37.822 [network_thread - 7999] INFO io.antmedia.webrtctest.WebRTCManager - onRenegotiationNeeded for stream Id stream1
04:54:37.823 [network_thread - 7999] INFO io.antmedia.webrtctest.WebRTCManager - onRenegotiationNeeded for stream Id stream1
Leaving main method
04:54:47.775 [pool-2-thread-1] INFO io.antmedia.webrtctest.StatManager - stats :        Number of Clients:0 Active Connections:0 Dropped Connections:0 Received Min frame period:2147483647ms, Max frame period: -2147483648ms, Mean frame period:0ms, cpu load: %-1 time: 1675054487 hash: 1290148677
04:54:47.775 [pool-2-thread-1] INFO io.antmedia.webrtctest.StatManager - Seems all streams are stopped and breaking the stats loop hash: 1290148677
```

Not sure what I'm missing?

**Comment by unicornsoftwareinc** [comment]
I figured it out. I was using the AWS IP address of my origin instance and not the domain name I set up. Using that fixed it and it is now working.

**Comment by mekya** [comment]
Thank you @unicornsoftwareinc for the update. Your domain name `REDACTED` is defined in your environment? I mean it should support that if the domain name is resolved in the OS level.
