### ISSUE TITLE
Stream does not play locally when signaling server is not reachable and local server restarts

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4828]
### Short description
When using cloud server as a signaling server and local server to ingest IP camera RTSP streams. If the cloud server is not reachable and if local server restarts in that duration then stream also does not play on local server and stuck into broadcast status.

### Environment
* Ant Media Server version: v2.5.3

### Steps to reproduce
1. Setup the architecture following the blog post--> https://antmedia.io/publish-and-play-streams-behind-nat/
2. After the setup, stop the AMS running in cloud running as a signaling server to reproduce the issue
3. Try to publish the stream and play locally (playback works at that time)
4. Restart the local server

### Expected behavior
Streams should work fine locally that was working before.

### Actual behavior
Streams are not working anymore and stuck into broadcasting status after starting the RTSP streams again (auto fetching is disabled by default). Below are the exceptions occurred at the time of issue:

2023-02-20 00:01:19,009 [vert.x-worker-thread-16] INFO  i.a.AntMediaApplicationAdapter -  Status of stream test is set to Broadcasting with result: true
2023-02-20 00:01:19,010 [Thread-11] ERROR i.a.streamsource.StreamFetcher - java.lang.NullPointerException
	at io.antmedia.enterprise.webrtc.WebSocketClientEndpoint.sendMessage(WebSocketClientEndpoint.java:53)
	at io.antmedia.enterprise.webrtc.WebSocketClientEndpoint.registerBroadcast(WebSocketClientEndpoint.java:72)
	at io.antmedia.enterprise.webrtc.WebRTCApplication.startPublish(WebRTCApplication.java:442)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.packetRead(StreamFetcher.java:354)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.readMore(StreamFetcher.java:260)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:241)

**Comment by yashtandon113** [comment]
As tested with @lastpeony, this issue seems fixed now.

**Comment by lastpeony** [comment]
PR raised for this issue on enterprise side. 
Feel free to re-open
