### ISSUE TITLE
IOS - Socket::OPT_DSCP not supported.

### ISSUE THREAD

**Issue by rafabarros** [ant-media/Ant-Media-Server#5065]
### Short description
React ( "@antmedia/react-native-ant-media": "^1.0.4" )
Expo 

### Environment
IOS over 5G 

* Operating system and version: IOS / IPHONE 12 / ios 15.2
* Ant Media Server version: Enterprise Edition 2.4.3 20220418_2241

### Steps to reproduce
1.  it seems connected over 5G and WIFI
2. With WIFI we can connect and use microphone
3. change to 5G 
4. Restart app because it cannot handle network changes ( issue opened )
5. Connected again into Room and cannot use microphone but it seems like connected 
6. my application is only audio / don't know about video

### Logs
(physical_socket_server.cc:557): Socket::OPT_DSCP not supported.

2023-05-02 15:27:28,502 [network_thread - 1126497] INFO  i.a.enterprise.webrtc.WebRTCClient - Starting streaming for dWK3cuFZlmR6fy5oAADp
2023-05-02 15:27:28,502 [vert.x-eventloop-thread-52] INFO  i.a.enterprise.webrtc.WebRTCClient - registering webrtc client 1483416648 with codec NoCodec to webrtc adaptor for streamId dWK3cuFZlmR6fy5oAADp
2023-05-02 15:27:28,502 [vert.x-eventloop-thread-52] INFO  i.a.enterprise.webrtc.WebRTCMuxer - register webrtc client(1483416648) to webrtc muxer(0p - codec:NoCodec) for stream: dWK3cuFZlmR6fy5oAADp current viewer count:1

(physical_socket_server.cc:557): Socket::OPT_DSCP not supported.
(sctp_transport.cc:512): SctpTransport->OpenStream(...): Not adding data stream with sid=1 because stream is already open.
(sctp_transport.cc:512): SctpTransport->OpenStream(...): Not adding data stream with sid=1 because stream is already open.
(sctp_transport.cc:894): SctpTransport->SendQueuedStreamResets(): Failed to send a stream reset for 1 streams : [0x00000009] Bad file descriptor
[mp4 @ 0x7efccc3ac240] Starting second pass: moving the moov atom to the beginning of the file

**Comment by rafabarros** [comment]
You can hear about ~2-3 seconds than its over. 
Seems like microphone works / but you not hear from IOS / 5G 
Wifi seems like / perfect . 

May 02, 2023 3:45:40 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jersey-serlvet] in context with path [/BedotApp] threw exception [java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at io.antmedia.datastore.db.DataStore$1.compare(DataStore.java:720)
	at io.antmedia.datastore.db.DataStore$1.compare(DataStore.java:711)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at io.antmedia.datastore.db.DataStore.sortAndCropBroadcastList(DataStore.java:711)
	at io.antmedia.datastore.db.MapDBStore.getBroadcastList(MapDBStore.java:426)
	at io.antmedia.rest.BroadcastRestService.getBroadcastList(BroadcastRestService.java:273)
	at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1230)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.antmedia.filter.IPFilter.doFilter(IPFilter.java:24)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.antmedia.filter.JWTFilter.doFilter(JWTFilter.java:44)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:368)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.antmedia.filter.RestProxyFilter.doFilter(RestProxyFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1638)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1125)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:587)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:565)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by rafabarros** [comment]
Solved! 

https://mediasoup.discourse.group/t/ios-iphone-cant-connect-under-4g-5g-network/4732

1. Some mobile networks will force the connections through ipv4/ipv6 NATs which don’t always work well with WebRTC.
2. You must create a turn/stun server by own with TLS. 

Antmedia will handle the rest.

**Comment by mekya** [comment]
Thank you @rafabarros for the update
