### ISSUE TITLE
Failing to save JWT filter

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5240]
### Short description
when generating JWT filter token from the dashboard and try to save the app settings it does not get saved 

### Environment

* Operating system and version: 
* Java version: 
* Ant Media Server version: 2.6.1
* Browser name and version: Chrome

### Steps to reproduce
1. Go to app settings 
2. Check out Enable JWT Filter for RESTful API
3. Click on generate
4. save the settings
https://antmedia.freshdesk.com/helpdesk/attachments/47223382895

### Expected behavior
Settings should be saved 

### Actual behavior
settings failed to save with error
 
### Logs

in.5dfab330c4ac165e1444.js:1 ERROR TypeError: Right-hand side of 'instanceof' is not an object
    at JWdw.t.exports [as sign] (main.5dfab330c4ac165e1444.js:1:319750)
    at t.changeSettings (main.5dfab330c4ac165e1444.js:1:1155347)
    at main.5dfab330c4ac165e1444.js:1:1115227
    at Lo (main.5dfab330c4ac165e1444.js:1:863029)
    at r (main.5dfab330c4ac165e1444.js:1:863191)
    at n.o [as _next] (main.5dfab330c4ac165e1444.js:1:907383)
    at n.value (main.5dfab330c4ac165e1444.js:1:192787)
    at n.value (main.5dfab330c4ac165e1444.js:1:191926)
    at n.value (main.5dfab330c4ac165e1444.js:1:190814)
    at n.value (main.5dfab330c4ac165e1444.js:1:190444)

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Yes that's the issue. Thank you for reporting @USAMAWIZARD.

It's an issue from jsowebtoken. Fix is coming and it will be in release 2.6.2 likely next week
