### ISSUE TITLE
Unable to delete streams

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#5385]
### Short description

Unable to delete streams under loads.

### Environment

* Operating system and version: Ubuntu 20.04
* Java version: 11
* Ant Media Server version: 2.6.2
* Browser name and version: Chrome

### Steps to reproduce
1. Create a cluster
2. Add 4 adaptive bitrate (1080p, 720p, 480p, 360p).
3. Send the stream until the server reaches 80% capacity.
4. Then attempt to delete the stream.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
**Browser logs:**

```
main.34ce630d4e6d5dc470a8.js:1 ERROR TypeError: Cannot read properties of null (reading 'success')
    at n._next (main.34ce630d4e6d5dc470a8.js:1:1044054)
    at n.value (main.34ce630d4e6d5dc470a8.js:1:186531)
    at n.value (main.34ce630d4e6d5dc470a8.js:1:185670)
    at n.value (main.34ce630d4e6d5dc470a8.js:1:184558)
    at n.value (main.34ce630d4e6d5dc470a8.js:1:184188)
    at n.value (main.34ce630d4e6d5dc470a8.js:1:1231526)
    at n.value (main.34ce630d4e6d5dc470a8.js:1:184188)
    at n.value (main.34ce630d4e6d5dc470a8.js:1:1291877)
    at n.value (main.34ce630d4e6d5dc470a8.js:1:184188)
    at n.value (main.34ce630d4e6d5dc470a8.js:1:170666)
```

**Server Logs:**

```
2023-07-20 10:22:49,159 [http-nio2-0.0.0.0-5080-exec-10] ERROR i.a.rest.servlet.EndpointProxy - Can't execute the request to forward in cluster
2023-07-20 10:22:49,159 [http-nio2-0.0.0.0-5080-exec-10] WARN  i.a.rest.servlet.EndpointProxy - ProxyResponse is null for request:org.apache.catalina.connector.RequestFacade@e4de547
2023-07-20 10:22:51,617 [http-nio2-0.0.0.0-5080-exec-11] INFO  io.antmedia.filter.RestProxyFilter - Redirecting request to origin http://162.19.223.144:5080/WebRTCAppEE/rest
2023-07-20 10:22:51,618 [http-nio2-0.0.0.0-5080-exec-11] ERROR i.a.rest.servlet.EndpointProxy - Can't execute the request to forward in cluster
2023-07-20 10:22:51,618 [http-nio2-0.0.0.0-5080-exec-11] WARN  i.a.rest.servlet.EndpointProxy - ProxyResponse is null for request:org.apache.catalina.connector.RequestFacade@6edb0ae8
```

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Duplicate https://github.com/ant-media/Ant-Media-Server/issues/5413
