### ISSUE TITLE
Unable to stream to the Samsung galaxy A8 android tablet

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5391]
### Short description
WebRTC Video Streaming Issue on Samsung Android A8 Tablet - The video display screen remains black 

Affected Device:
------------------------------------------
Device: Samsung Android A8 Tablet
Android Version Android 13
OneUI 5.1
architecture-> arm64-v8a

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
Steps to replicate: 

1. clone the repo
2. go to sample project. 
3. go to the below path: 

`java/io/antmedia/webrtc_android_sample_app/MainActivity.java
`
Modify the below code as per your need: 
     

```
webRTCClient.setVideoRenderers(pipViewRenderer, cameraViewRenderer);
        String token = "Add YOUR TOKEN";
   
        webRTCClient.init("wss://sample-link:5443/WebRTCAppEE/websocket", streamId, IWebRTCClient.MODE_PLAY, token, this.getIntent());
        webRTCClient.setDataChannelObserver(this);


```

run the app and navigate to MainActivity.java when you play the file on A8 it will not play. 

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
The video display screen remains black 

### Logs
![image](https://github.com/ant-media/Ant-Media-Server/assets/47350008/bfdb379f-33c9-4bb6-b217-779fef7e312b)

Exception in the AndroidVideoDecoder.java class:

File path-> java/org/webrtc/AndroidVideoDecoder.java
Attaching screenshot for your reference

at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:364)
2023-07-14 16:16:05.768 20557-22099 AndroidVideoDecoder     com.lrt.morganSTG                    E  deliverDecodedFrame failed
2023-07-14 16:16:05.768 20557-22099 AndroidVideoDecoder     com.lrt.morganSTG                    
E  java.lang.IllegalStateException
2023-07-14 16:16:05.768 20557-22099 AndroidVideoDecoder     com.lrt.morganSTG                    
E  java.lang.IllegalStateException
                                                                                                    at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                                    at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3573)
                                                                                                    at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:72)
                                                                                                    at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:380)
                                                                                                    at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:364)
2023-07-14 16:16:05.769 20557-22099 AndroidVideoDecoder     com.lrt.morganSTG                    E  deliverDecodedFrame failed
2023-07-14 16:16:05.769 20557-22099 AndroidVideoDecoder     com.lrt.morganSTG                    E  java.lang.IllegalStateException
2023-07-14 16:16:05.769 20557-22099 AndroidVideoDecoder     com.lrt.morganSTG                    E  java.lang.IllegalStateException
                                                                                                    at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                                    at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3573)
                                                                                                    at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:72)
                                                                                                    at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:380)
                                                                                                    at org.webrtc.AndroidVid

__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by githubashutoshsoni** [comment]
Steps to replicate: 

1. clone the repo
2. go to sample project. 
3. go to the below path: 

`java/io/antmedia/webrtc_android_sample_app/MainActivity.java
`
Modify the below code as per your need: 
     

```
webRTCClient.setVideoRenderers(pipViewRenderer, cameraViewRenderer);
        String token = "Add YOUR TOKEN";
   
        webRTCClient.init("wss://sample-link:5443/WebRTCAppEE/websocket", streamId, IWebRTCClient.MODE_PLAY, token, this.getIntent());
        webRTCClient.setDataChannelObserver(this);


```

run the app and navigate to MainActivity.java when you play the file on A8 it will not play.

**Comment by githubashutoshsoni** [comment]
sure, i can help. let me know what to do?

**Comment by USAMAWIZARD** [comment]
@githubashutoshsoni informed us the issue was resolved by decreasing the bit-rate of the video

**Comment by githubashutoshsoni** [comment]
No there’s been misunderstanding. I did not provide any such information. I said I can help replicating the issue.

**Comment by USAMAWIZARD** [comment]
Hi @githubashutoshsoni  , Sorry for the misunderstanding , is Ted from your team ? we were informed about this by him on email tickets side that the issue was resolved by decreasing the bit-rate

**Comment by githubashutoshsoni** [comment]
Okay, yes. Let me check with him.

**Comment by USAMAWIZARD** [comment]
please let me know if there is any update ?

**Comment by githubashutoshsoni** [comment]
Sure, you can close the ticket if ted says so.

**Comment by USAMAWIZARD** [comment]
Thank you for the update.
