### ISSUE TITLE
i.a.streamsource.StreamFetcher - java.lang.OutOfMemoryError: Physical memory usage is too high

### ISSUE THREAD

**Issue by alfred-stokespace** [ant-media/Ant-Media-Server#5478]
### Short description
HLS Transcoding starts to produce in `ant-media-server.log`

```
2023-08-18 22:22:15,140 [Thread-53582] ERROR i.a.streamsource.StreamFetcher - java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (61452M) > maxPh
ysicalBytes (61376M)
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:700)
        at org.bytedeco.javacpp.Pointer.init(Pointer.java:126)
        at org.bytedeco.ffmpeg.avutil.AVRational.allocate(Native Method)
        at org.bytedeco.ffmpeg.avutil.AVRational.<init>(AVRational.java:40)
        at io.antmedia.enterprise.webrtc.WebRTCMuxer.<init>(WebRTCMuxer.java:167)
        at io.antmedia.enterprise.adaptive.EncoderAdaptor.getWebRTCMuxer(EncoderAdaptor.java:759)
        at io.antmedia.enterprise.adaptive.EncoderAdaptor.buildEncoders(EncoderAdaptor.java:523)
        at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareEncoders(EncoderAdaptor.java:786)
        at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareEncoders(EncoderAdaptor.java:844)
        at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareInternal(EncoderAdaptor.java:311)
        at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareFromInputFormatContext(EncoderAdaptor.java:334)
        at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:278)
```

### Environment

* Operating system and version: ` Ubuntu 20.04.6 LTS 5.15.0-1040-aws #45~20.04.1-Ubuntu SMP Tue Jul 11 19:08:13 UTC 2023 x86_64`
* Java version: `openjdk 11.0.20 2023-07-18`
* Ant Media Server version:  2.4.3 20220418_2241
* Browser name and version: Edge 

### Steps to reproduce
1. g4dn.8xlarge (32 vcpu, 128GB ram)
2. 27 streamSource IP cams. 1920x1080 <10mbs per cam.
3. run for a while

### Expected behavior
no drops and smoothing viewing, no error messages about out of memory.

### Actual behavior
some cameras are failing to stream to users at all. Some are fine. Logs show OOM errors over an over again.

**Comment by alfred-stokespace** [comment]
dropped stream count from 27 to 21 and memory errors stopped. Stability regained.

**Comment by alfred-stokespace** [comment]
Update...
we upgraded the ec2 instance type to a 4 gpu instance `g4dn.12xlarge`
and we are able to transcode 28 streams (2 renditions per stream) without any OOM messages.

**Comment by mekya** [comment]
hi @alfred-stokespace,

Thank you for issue and updates. We plan to have an update to improve the transcoding performance in GPU so that you can have more streams on your end. 

Just referencing this issue https://github.com/ant-media/Ant-Media-Server/issues/5433

**Comment by alfred-stokespace** [comment]
No, we been very stable since adjusting up the ec2 instance. We've had as many as 30 streams on this ec2 instance (AMS 2.4.3)
We aren't yet in a position to upgrade again to 2.6.x on the larger EC2 instance but I'll try that once we have a moment.

**Comment by mekya** [comment]
Thank you for the update @alfred-stokespace. I appreciate that. 

Then I'm closing this issue and let us know if we can help further. 

Have a great weekend
 
Cheers
Oguz
