### ISSUE TITLE
Optimize the vod_transcode.sh script

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5508]
The `vod_transcode.sh` script needs some optimizations like:

- Executing the script consumes a lot of CPU resources. A typical 4 cores CPU optimized instance C5.xlarge of AWS runs out of CPU in executing the script even for very short files and the CPU almost maxes out to 99% or so therefore there are lots of thread-blocking warnings on the server.
`
2023-08-25 06:58:28,485 [vert.x-worker-thread-12] INFO  i.a.AntMediaApplicationAdapter - running muxer finish script: /usr/local/antmedia/vod_transcode.sh  /usr/local/antmedia/webapps/WebRTCAppEE/streams/434919346399364511095908.mp4
2023-08-25 06:58:38,966 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-worker-thread-12,5,main] has been blocked for 10474 ms, time limit is 10000 ms
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.20/java.lang.Object.wait(Native Method)
	at java.base@11.0.20/java.lang.Object.wait(Object.java:328)
	at java.base@11.0.20/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
	at io.antmedia.AntMediaApplicationAdapter.lambda$runScript$10(AntMediaApplicationAdapter.java:759)
	at io.antmedia.AntMediaApplicationAdapter$$Lambda$504/0x000000010079c440.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.ContextImpl$$Lambda$415/0x0000000100610040.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.ContextImpl$$Lambda$408/0x00000001005dd840.run(Unknown Source)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.vertx.core.impl.TaskQueue$$Lambda$407/0x00000001005de040.run(Unknown Source)
	at java.base@11.0.20/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.20/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.20/java.lang.Thread.run(Thread.java:829)
2023-08-25 06:58:39,961 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-worker-thread-12,5,main] has been blocked for 11475 ms, time limit is 10000 ms
`

- When the script is called and until it finishes, there are no messages on the server/log showing the current status of the script until it finishes and therefore for long files, it is not feasible to find the current status of the script execution.

- Adding support for uploading these files to the S3 buckets after conversion.

**Comment by ducquynhnguyeninfo** [comment]
Hello, 

What is the progress of this improvement ticket so far?

Thanks

**Comment by mekya** [comment]
Hi @ducquynhnguyeninfo,

We have some improvements for this issue. What exactly you're encountering on your side and would like to resolve?

If there is a too much resource usage, there are following solutions
1. Use a GPU or a more powerful CPU 
2. Use some kind of video encoding service in GCP, AWS, etc.

Let me know your expectation and we'll do our best to address it for you ;)

Cheers

**Comment by Mohit-3196** [comment]
Hi @ducquynhnguyeninfo,
How are you?
Have you had a chance to check the comments above?

In case I do not hear from you, I will be closing this issue for inactivity.

Thank you.

**Comment by Mohit-3196** [comment]
I'm closing this issue now for inactivity.
Please feel free to reopen the issue if you have any comments.


Thank you,
Mohit
