### ISSUE TITLE
Thread blocks while accessing the MapDB

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#5702]
2023-10-10 11:13:14,985 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-worker-thread-2,5,main] has been blocked for 120354 ms, time limit is 10000 ms
io.vertx.core.VertxException: Thread blocked
	at io.antmedia.datastore.db.MapDBStore.lambda$new$0(MapDBStore.java:82)
	at io.antmedia.datastore.db.MapDBStore$$Lambda$484/0x00000007c075c440.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.ContextImpl$$Lambda$413/0x00000007c05fc840.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.ContextImpl$$Lambda$410/0x00000007c05fd840.run(Unknown Source)
	at java.base@11.0.20.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.20.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.20.1/java.lang.Thread.run(Thread.java:829)
2023-10-10 11:13:14,986 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 233456 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at io.antmedia.datastore.db.DataStore.get(DataStore.java:83)
	at io.antmedia.datastore.db.MapBasedDataStore.get(MapBasedDataStore.java:81)
	at io.antmedia.AntMediaApplicationAdapter.lambda$setQualityParameters$11(AntMediaApplicationAdapter.java:1034)
	at io.antmedia.AntMediaApplicationAdapter$$Lambda$540/0x00000007c080a040.handle(Unknown Source)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:893)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:860)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:883)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.20.1/java.lang.Thread.run(Thread.java:829)

**Comment by lastpeony** [comment]
Looks like a concurrency issue. Fix concurrency on current structure or switching to BTreeMap might be useful.  It is based on lock-free concurrent B-Linked-Tree

**Comment by burak-58** [comment]
Never encountered with new releases. We can reopen if encounter again.
