### ISSUE TITLE
IllegalArgumentException on Login

### ISSUE THREAD

**Issue by hoos** [ant-media/Ant-Media-Server#572]
# Issue

### Short description
When I login via the Web Management console I notice the following exception in the antmedia-error.log file

 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:421)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

There is no obvious problem and the I can login without issue, however I do tend to get logged out regularly for no apparent reason.  

### Environment

* Operating system and version: Ubuntu 18.04.1 LTS \n \l
* Java version: openjdk version "1.8.0_181
* Ant Media Server version: Ant Media Server Community 1.5.1.1 (Oct 11, 2018)
* Browser name and version: Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)

### Expected behavior
Ideally there should be no errors in the logs as a result of login.

### Actual behavior
As stated the above error always occurs twice when I log in. 

### Steps to reproduce
1. Tail the antmedia-error.log file
2. Login via the Web Management Console (credentials stored in Chrome)

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

https://pastebin.com/MxSr9Y9z

**Comment by burak-58** [comment]
Did you encounter this problem in localhost or not? If in localhost did you access server with https://localhost:5080 or not?

**Comment by hoos** [comment]
The errors in the log file are present when accessing the media server remotely via it's host name.

**Comment by burak-58** [comment]
I followed the steps to reproduce the issue but I didn't encounter with it.

However when I tried to access as https://<server>:5080 I saw the same exception.
Might you (or anybody from anywhere) have done so when the exception occured?
