### ISSUE TITLE
Android SDK Multitrack Conference Join-Rejoin Does Not Work Correctly

### ISSUE THREAD

**Issue by lastpeony** [ant-media/Ant-Media-Server#5737]
In the Android SDK multitrack conference, when a participant joins and then subsequently leaves the conference, their video feed is not properly cleared; instead, it becomes frozen. Furthermore, when they rejoin the conference, their video feed does not appear correctly; it remains frozen.

The expected behavior in this scenario is as follows: When a user leaves the conference, their video feed should be cleared, and upon rejoining, their video feed should be added correctly, without remaining frozen.

This issue is being observed in AMS 2.7.0

**Comment by KavyashreeBasavesh** [comment]
Please update.. Any progress?

**Comment by mekya** [comment]
hi @KavyashreeBasavesh,

We generally schedule issues according to priority, importance, and urgency. The pipeline is visible here
https://github.com/orgs/ant-media/projects/3

We'll discuss whether this issue is scheduled for this week or not. If you want us to increase priority of any issue,  you can reach out to contact@antmedia.io or support@antmedia.io  

Regards
Oguz

**Comment by KavyashreeBasavesh** [comment]
@mekya Please update the status

**Comment by mekya** [comment]
Hi @KavyashreeBasavesh,

There is no update. We have not space available to schedule this issue. It's going on priority basis and availability as you probably already know. 

If you want some issues to be resolved with some time limitation, please reach out contact@antmedia.io


Regards
Oguz

**Comment by arjeshvadadoriya4052** [comment]
same issue is happening in WebRTC Android SDK when,
- playing stream with `webRTCClient.startStream(STREAM_ID)`
- stoping using `webRTCClient.stopStream(STREAM_ID)`
- again starting stream.

when stoping the stream the frame gets stuck, starting again stream stays stuck at that frame while logs shows that stream is successfully started.

**Comment by KavyashreeBasavesh** [comment]
Hi,

Didn't hear anything from your end. It's been 6days. Is there any progress?

**Comment by USAMAWIZARD** [comment]
Still working on it I will update by the end of the this week.

**Comment by USAMAWIZARD** [comment]
Issues Reported :

**Comment by USAMAWIZARD** [comment]
Issues Reported : video feed is not properly cleared; instead, it becomes frozen

**Comment by USAMAWIZARD** [comment]
@KavyashreeBasavesh  I wanted to update you regarding the reported issues.
Issues Reported : 
1. video feed is not properly cleared; instead, it becomes frozen : **Fix**  
2. When rejoin the conference, their video feed does not appear correctly; it remains frozen. **Fix**

I will be writing some test code for this and send a PR. 
Fix on this Branch : https://github.com/ant-media/WebRTC-Android-SDK/tree/fix-Renderer

**Comment by KavyashreeBasavesh** [comment]
Hi Usma,

Thanks for the update. Please do confirm, whether it will work foe iOS as
well.

Regards,
Kavya

**Comment by KavyashreeBasavesh** [comment]
Hi Usma,

We have downloaded the same repository which you have shared with us. But,
after using it, we are getting below error and the application is crashing.

FATAL EXCEPTION: Timer-0

                        Process: com.app.kiakandid, PID: 25858

                        java.lang.IllegalStateException: MediaStreamTrack
has been disposed.

                        at
org.webrtc.MediaStreamTrack.checkMediaStreamTrackExists(MediaStreamTrack.java:120)

                        at org.webrtc.MediaStreamTrack.id
(MediaStreamTrack.java:83)

                        at
io.antmedia.webrtcandroidframework.WebRTCClient$TrackCheckTask.run(WebRTCClient.java:477)

                        at java.util.TimerThread.mainLoop(Timer.java:563)

                        at java.util.TimerThread.run(Timer.java:513)

*Critical error: An error occurred when sending the message via Data
Channel Attempt to invoke virtual method 'boolean
org.webrtc.DataChannel.send(org.webrtc.DataChannel$Buffer)' on a null
object reference.*

Regards,
Kavya
