### ISSUE TITLE
Null Pointer Exception at RequestInfo

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5762]
Issue: reqURI parameter gets Null Pointer Exception in RequestInfo class at line 24

Ant Media Server Version: v2.7.0 Enterprise Edition
Ant Media Server Mode: Cluster

Note: It's collected from the log management system.

Stack Trace:

```
java.lang.NullPointerException: null
	at io.antmedia.enterprise.cluster.RequestInfo.<init>(RequestInfo.java:24)
	at io.antmedia.enterprise.cluster.HttpLiveStreamValve.invoke(HttpLiveStreamValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:768)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1720)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1274)
	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:342)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:482)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:418)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mekya** [comment]
hi @mustafaboleken,

Thank you for creating the issue.

To resolve the issue easily, could you please give the stack trace?

Cheers

**Comment by mustafaboleken** [comment]
Hi @mekya 

Sure, I'm editing the first comment

**Comment by mustafaboleken** [comment]
Pull Request: https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/638

**Comment by mustafaboleken** [comment]
It's merged by @mekya
