### ISSUE TITLE
After enabling SSL, the Ant Media Server is not reachable over HTTPS in AMS EE v2.8.0 Snapshot

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5892]
Ant Media Server Version: ant-media-server-enterprise-2.8.0-SNAPSHOT-20231203_1742

1. Enable SSL and try accessing the web panel over HTTPS and port 5443
2. The server is not accessible.
3. It can be reached on port 5080 with the domain as well as over port 5443 with HTTP

**Server Logs**:
2023-12-04 15:16:16,286 [main] INFO  o.r.spring.Red5ApplicationContext - setApplicationContext: org.springframework.context.support.FileSystemXmlApplicationContext@781f10f2, started on Mon Dec 04 15:16:15 UTC 2023
2023-12-04 15:16:16,292 [main] INFO  o.r.spring.Red5ApplicationContext - Red5ApplicationContext init
2023-12-04 15:16:16,455 [main] INFO  o.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
2023-12-04 15:16:16,470 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2023-12-04 15:16:16,472 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v2.5.0-rc1 created.
2023-12-04 15:16:16,473 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
2023-12-04 15:16:16,474 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.5.0-rc1) 'Red5_Scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 6 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2023-12-04 15:16:16,474 [main] INFO  o.quartz.impl.StdSchedulerFactory - Quartz scheduler 'Red5_Scheduler' initialized from the specified file : '/usr/local/antmedia/conf/quartz.properties'
2023-12-04 15:16:16,474 [main] INFO  o.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.5.0-rc1
2023-12-04 15:16:16,475 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler Red5_Scheduler_$_NON_CLUSTERED started.
2023-12-04 15:16:17,044 [main] INFO  i.antmedia.settings.ServerSettings - Using local host address is 172.31.5.93
2023-12-04 15:16:17,048 [main] INFO  org.red5.server.ContextLoader - ContextLoader init
2023-12-04 15:16:17,051 [main] INFO  org.red5.server.ContextLoader - Loading: default.context = ${red5.root}/webapps/red5-default.xml => /usr/local/antmedia/webapps/red5-default.xml
2023-12-04 15:16:17,182 [main] INFO  org.red5.server.scope.Scope - Scope:default is  running
2023-12-04 15:16:17,194 [main] INFO  org.red5.server.Context - Deployment type: bootstrap
2023-12-04 15:16:17,208 [main] INFO  org.red5.server.tomcat.WarDeployer - War deployer service created
2023-12-04 15:16:17,212 [main] INFO  org.red5.server.tomcat.WarDeployer - Starting WarDeployer
2023-12-04 15:16:17,216 [main] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars without app start
2023-12-04 15:16:17,337 [main] INFO  o.red5.server.tomcat.TomcatLoader - Loading Tomcat
2023-12-04 15:16:17,338 [main] INFO  o.red5.server.tomcat.TomcatLoader - Server root: /usr/local/antmedia
2023-12-04 15:16:17,339 [main] INFO  o.red5.server.tomcat.TomcatLoader - Config root: /usr/local/antmedia/conf
2023-12-04 15:16:17,361 [main] INFO  o.red5.server.tomcat.TomcatLoader - Application root: /usr/local/antmedia/webapps
2023-12-04 15:16:17,385 [main] INFO  org.red5.server.LoaderBase - Set application context - path: 0.0.0.0/WebRTCAppEE context: org.red5.server.tomcat.TomcatApplicationContext@65bb6275
2023-12-04 15:16:17,397 [main] INFO  org.red5.server.LoaderBase - Set application context - path: 0.0.0.0/LiveApp context: org.red5.server.tomcat.TomcatApplicationContext@2d119405
2023-12-04 15:16:17,401 [main] INFO  org.red5.server.LoaderBase - Set application context - path: 0.0.0.0 context: org.red5.server.tomcat.TomcatApplicationContext@57e388c3
2023-12-04 15:16:17,449 [main] INFO  o.r.server.tomcat.TomcatConnector - sslEnabledProtocols:TLSv1.2 and ciphers: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_CCM_8,TLS_DHE_RSA_WITH_AES_256_CCM
2023-12-04 15:16:17,475 [main] INFO  o.red5.server.tomcat.TomcatLoader - Starting Tomcat servlet engine
2023-12-04 15:16:20,030 [main] INFO  o.red5.server.tomcat.TomcatLoader - Context initialized:  path: /usr/local/antmedia/webapps/root/
2023-12-04 15:16:20,031 [main] INFO  o.red5.server.tomcat.TomcatLoader - Spring parent context key: default.context
2023-12-04 15:16:20,032 [main] INFO  o.red5.server.tomcat.TomcatLoader - Context initialized: /LiveApp path: /usr/local/antmedia/webapps/LiveApp/
2023-12-04 15:16:20,032 [main] INFO  o.red5.server.tomcat.TomcatLoader - Spring parent context key: default.context
2023-12-04 15:16:20,032 [main] INFO  o.red5.server.tomcat.TomcatLoader - Context initialized: /WebRTCAppEE path: /usr/local/antmedia/webapps/WebRTCAppEE/
2023-12-04 15:16:20,032 [main] INFO  o.red5.server.tomcat.TomcatLoader - Spring parent context key: default.context
2023-12-04 15:16:20,083 [main] WARN  i.antmedia.statistic.StatsCollector - Starting heartbeats for the version:2.8.0-SNAPSHOT and type:Enterprise
2023-12-04 15:16:20,138 [main] INFO  i.a.enterprise.srt.SRTAdaptor - SRT server is starting for port 4200
2023-12-04 15:16:20,142 [main] INFO  i.a.enterprise.srt.SRTAdaptor - SRT server starts listening for port 4200
2023-12-04 15:16:20,142 [main] INFO  i.a.enterprise.srt.SRTAdaptor - SRT epoll is created
2023-12-04 15:16:20,143 [main] INFO  i.a.enterprise.srt.SRTAdaptor - SRT epoll thread is starting
2023-12-04 15:16:20,293 [Loader:] INFO  org.red5.server.Context - Deployment type: bootstrap
2023-12-04 15:16:20,330 [Loader:] INFO  org.red5.server.scope.WebScope - Set server [Server@2c26470amap[[empty]]]
2023-12-04 15:16:20,361 [Loader:] INFO  org.red5.server.Server - Add mapping global: default host:  context: root
2023-12-04 15:16:20,369 [Loader:] INFO  org.red5.server.scope.Scope - Scope:root is  running
2023-12-04 15:16:20,369 [Loader:] INFO  org.red5.server.scope.WebScope - Webscope already registered; remove the 'init-method' from your 'web.scope' bean to prevent this message in the future.
2023-12-04 15:16:20,456 [main] INFO  o.r.spring.Red5ApplicationContext - setApplicationContext: org.springframework.context.support.FileSystemXmlApplicationContext@781f10f2, started on Mon Dec 04 15:16:15 UTC 2023
2023-12-04 15:16:20,462 [main] INFO  o.r.spring.Red5ApplicationContext - Red5ApplicationContext init
2023-12-04 15:16:20,572 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - RTMP will be bound to [0.0.0.0:1935]
2023-12-04 15:16:20,581 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - RTMP Mina Transport Settings
Acceptor style: default I/O threads: 16
TCP no-delay: true keep-alive: false
2023-12-04 15:16:20,597 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - Traffic class modification is disabled
2023-12-04 15:16:20,598 [main] INFO  o.r.s.net.rtmp.RTMPMinaTransport - Send buffer size: 65536 recv buffer size: 65536 so linger: -1 traffic class: 0
2023-12-04 15:16:20,803 [Loader:/LiveApp] INFO  org.red5.server.Context - Deployment type: bootstrap
2023-12-04 15:16:21,144 [Loader:/LiveApp] INFO  i.a.datastore.db.DataStoreFactory - Used Datastore:mapdb  db name:liveapp
2023-12-04 15:16:21,151 [Loader:/LiveApp] INFO  org.red5.server.scope.WebScope - Set server [Server@2c26470amap['/root' -> 'default']]
2023-12-04 15:16:21,152 [Loader:/LiveApp] INFO  org.red5.server.Server - Add mapping global: default host:  context: LiveApp
2023-12-04 15:16:21,153 [Loader:/LiveApp] INFO  i.a.AntMediaApplicationAdapter - Delete the ".closed" file in LiveApp
2023-12-04 15:16:21,157 [Loader:/LiveApp] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - setting excessive bandwidth algorithm enabled:false
2023-12-04 15:16:21,157 [Loader:/LiveApp] INFO  i.a.AntMediaApplicationAdapter - LiveApp started
2023-12-04 15:16:21,159 [Loader:/LiveApp] INFO  org.red5.server.scope.Scope - Scope:LiveApp is  running
2023-12-04 15:16:21,478 [Loader:/WebRTCAppEE] INFO  org.red5.server.Context - Deployment type: bootstrap
2023-12-04 15:16:21,493 [Loader:/WebRTCAppEE] INFO  i.a.datastore.db.DataStoreFactory - Used Datastore:mapdb  db name:webrtcappee
2023-12-04 15:16:21,496 [Loader:/WebRTCAppEE] INFO  org.red5.server.scope.WebScope - Set server [Server@2c26470amap['/root' -> 'default', '/LiveApp' -> 'default']]
2023-12-04 15:16:21,500 [Loader:/WebRTCAppEE] INFO  org.red5.server.Server - Add mapping global: default host:  context: WebRTCAppEE
2023-12-04 15:16:21,501 [Loader:/WebRTCAppEE] INFO  i.a.AntMediaApplicationAdapter - Delete the ".closed" file in WebRTCAppEE
2023-12-04 15:16:21,504 [Loader:/WebRTCAppEE] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - setting excessive bandwidth algorithm enabled:false
2023-12-04 15:16:21,504 [Loader:/WebRTCAppEE] INFO  i.a.AntMediaApplicationAdapter - WebRTCAppEE started
2023-12-04 15:16:21,504 [Loader:/WebRTCAppEE] INFO  org.red5.server.scope.Scope - Scope:WebRTCAppEE is  running
2023-12-04 15:17:17,216 [pool-2-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start

**Error Logs**:

Dec 04, 2023 3:16:17 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Dec 04, 2023 3:16:17 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/10.1.16]
Dec 04, 2023 3:16:17 PM org.apache.catalina.loader.WebappLoader buildClassPath
INFO: Unknown class loader [jdk.internal.loader.ClassLoaders$AppClassLoader@2aae9190] of class [class jdk.internal.loader.ClassLoaders$AppClassLoader]
Dec 04, 2023 3:16:17 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Dec 04, 2023 3:16:17 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Dec 04, 2023 3:16:18 PM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Dec 04, 2023 3:16:19 PM org.apache.catalina.loader.WebappLoader buildClassPath
INFO: Unknown class loader [jdk.internal.loader.ClassLoaders$AppClassLoader@2aae9190] of class [class jdk.internal.loader.ClassLoaders$AppClassLoader]
Dec 04, 2023 3:16:19 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Dec 04, 2023 3:16:19 PM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Dec 04, 2023 3:16:19 PM org.apache.catalina.loader.WebappLoader buildClassPath
INFO: Unknown class loader [jdk.internal.loader.ClassLoaders$AppClassLoader@2aae9190] of class [class jdk.internal.loader.ClassLoaders$AppClassLoader]
Dec 04, 2023 3:16:19 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Dec 04, 2023 3:16:19 PM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Dec 04, 2023 3:16:20 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio2-0.0.0.0-5080"]
Dec 04, 2023 3:16:20 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio2-0.0.0.0-5443"]
Dec 04, 2023 3:16:20 PM org.webrtc.Logging log
INFO: NativeLibrary: Loading native library: jingle_peerconnection_so
Dec 04, 2023 3:16:20 PM org.webrtc.Logging log
INFO: NativeLibrary: Loading library: jingle_peerconnection_so
Dec 04, 2023 3:16:20 PM org.webrtc.Logging log
INFO: PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
Dec 04, 2023 3:16:21 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x170x010x000x020x130x030x03w0xfah0xd7!0x93r0x0b`0xa9ml0xa9^0xc60xa20xe40x90,0x7f/'0x1f"0x030x1bA{F0xaa<: ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1683)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1243)
        at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:328)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:468)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:404)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)

Dec 04, 2023 3:16:21 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03D0x1d0xa10x9c0xa010x190xfd[./0xc60xd80xf3W0x87(0xdct0x940xea0x8eS0x0a0xc10xe10xd6hO0xc90xa50x7f ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1683)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1243)
        at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:328)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:468)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:404)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)

Dec 04, 2023 3:16:21 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03)50x9f0xd10xccu0x010xe3|0xb60x1c&0xd1<Yf0xd10x17B0x85;o0xb8B0x120xf80x140x100xbc0xa6yt ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1683)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1243)
        at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:328)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:468)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:404)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)

Dec 04, 2023 3:20:07 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x170x010x000x020x130x030x030x8a0xbc0xffco0xc90xa8D0xee0xe60x0e0xc30xf90xde0x850xaa0xe10x020xb80xb50xa3/0x9e0xf3J0x1d0x150x100x080xb8A0 ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1683)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1243)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:632)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:608)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)

Dec 04, 2023 3:21:57 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x170x010x000x020x130x030x030x970xcb0xb2O0xf8V0x880x880xea<0xf50x12K0x9dW0x070xb40xdd0x15#0x9e~0xa1S@0xf90xae0xa7_Q0xad0xfc ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1683)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1243)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:632)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:608)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)

Dec 04, 2023 3:22:04 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x170x010x000x020x130x030x03K0x020xfb0xa60x0dD_y~0xc5~0x02!.0x070x990xcf0xcb0x8480xc40xa1@G<)0x870xae80xc30xa70xad ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1683)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1243)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:632)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:608)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Mohit-3196** [comment]
Thank you @muratugureminoglu abi,
It works.
