### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by bredfern** [ant-media/Ant-Media-Server#6]
# Issue

### Short description
The maven build failed when I checked out from git and ran the maven command from the readme.md.

### Environment

[] Operating system and version: Centos 7
[] Java version: openjdk version "1.8.0_144"
[] Red5 version: red5 included with the binary version of ant media server

### Expected behavior
Should give me a set of jar files of the new build from source.

### Actual behavior
I get this error message instead:
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.472s
[INFO] Finished at: Thu Oct 05 11:10:42 MST 2017
[INFO] Final Memory: 17M/154M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ant-media-server: Could not resolve dependencies for project io.antmedia:ant-media-server:jar:1.0.9-M2: The following artifacts could not be resolved: io.antmedia:ant-media-server-service:jar:1.0.9-M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antmedia.plugins:PeriscopeAPI:jar:1.0.0: Failure to find io.antmedia:ant-media-server-service:jar:1.0.9-M2 in http://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project ant-media-server: Could not resolve dependencies for project io.antmedia:ant-media-server:jar:1.0.9-M2: The following artifacts could not be resolved: io.antmedia:ant-media-server-service:jar:1.0.9-M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antmedia.plugins:PeriscopeAPI:jar:1.0.0: Failure to find io.antmedia:ant-media-server-service:jar:1.0.9-M2 in http://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project io.antmedia:ant-media-server:jar:1.0.9-M2: The following artifacts could not be resolved: io.antmedia:ant-media-server-service:jar:1.0.9-M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antmedia.plugins:PeriscopeAPI:jar:1.0.0: Failure to find io.antmedia:ant-media-server-service:jar:1.0.9-M2 in http://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:189)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
        ... 22 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: io.antmedia:ant-media-server-service:jar:1.0.9-M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antmedia.plugins:PeriscopeAPI:jar:1.0.0: Failure to find io.antmedia:ant-media-server-service:jar:1.0.9-M2 in http://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:183)
        ... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: io.antmedia:ant-media-server-service:jar:1.0.9-M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antmedia.plugins:PeriscopeAPI:jar:1.0.0: Failure to find io.antmedia:ant-media-server-service:jar:1.0.9-M2 in http://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
        ... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Failure to find io.antmedia:ant-media-server-service:jar:1.0.9-M2 in http://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced
        at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:230)
        at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:204)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:427)
        ... 26 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

### Steps to reproduce
1. clone project from git
2. cd to project directory
3. run  mvn -e -Dmaven.test.skip=true install

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by bredfern** [comment]
I was able to replicate the error attempting to build from source with maven on windows10 (my local client rather than in my data center), this is the same build error on windows10, running the same commands as the centos 7 error message above:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 54:35 min
[INFO] Finished at: 2017-10-05T16:35:55-07:00
[INFO] Final Memory: 17M/175M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ant-media-server: Could not resolve dependencies for project io.antmedia:ant-m
edia-server:jar:1.0.9-M2: The following artifacts could not be resolved: io.antmedia:ant-media-server-service:jar:1.0.9-
M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antmedia.plugins:PeriscopeAPI:jar:1.0.0: Could not f
ind artifact io.antmedia:ant-media-server-service:jar:1.0.9-M2 in sonatype-snapshots (http://oss.sonatype.org/content/re
positories/snapshots) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project ant-media-server: Could not re
solve dependencies for project io.antmedia:ant-media-server:jar:1.0.9-M2: The following artifacts could not be resolved:
 io.antmedia:ant-media-server-service:jar:1.0.9-M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antm
edia.plugins:PeriscopeAPI:jar:1.0.0: Could not find artifact io.antmedia:ant-media-server-service:jar:1.0.9-M2 in sonaty
pe-snapshots (http://oss.sonatype.org/content/repositories/snapshots)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.j
ava:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependenc
yResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:246)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project io.antmedi
a:ant-media-server:jar:1.0.9-M2: The following artifacts could not be resolved: io.antmedia:ant-media-server-service:jar
:1.0.9-M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antmedia.plugins:PeriscopeAPI:jar:1.0.0: Coul
d not find artifact io.antmedia:ant-media-server-service:jar:1.0.9-M2 in sonatype-snapshots (http://oss.sonatype.org/con
tent/repositories/snapshots)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:2
08)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.j
ava:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: i
o.antmedia:ant-media-server-service:jar:1.0.9-M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antmed
ia.plugins:PeriscopeAPI:jar:1.0.0: Could not find artifact io.antmedia:ant-media-server-service:jar:1.0.9-M2 in sonatype
-snapshots (http://oss.sonatype.org/content/repositories/snapshots)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:393
)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:2
02)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: io.
antmedia:ant-media-server-service:jar:1.0.9-M2, io.antmedia:ant-media-server-service:tar.gz:daemon:1.0.9-M2, io.antmedia
.plugins:PeriscopeAPI:jar:1.0.0: Could not find artifact io.antmedia:ant-media-server-service:jar:1.0.9-M2 in sonatype-s
napshots (http://oss.sonatype.org/content/repositories/snapshots)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:376
)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.antmedia:ant-media-server-s
ervice:jar:1.0.9-M2 in sonatype-snapshots (http://oss.sonatype.org/content/repositories/snapshots)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48
)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
PS C:\Users\bredfern\Documents\Ant-Media-Server>

**Comment by mekya** [comment]
Hi @bredfern ,

Sorry for late reply.  :(

Some projects does not in maven repo yet, so that you need to download and install them with mvn.

Here are the repos you need to download and install 
https://github.com/ant-media/Periscope-Producer-API
https://github.com/ant-media/Ant-Media-Server-Common
https://github.com/ant-media/Ant-Media-Server-Service
https://github.com/ant-media/Ant-Media-Server

Pleaset let me know if you have problem. 

Regards,

**Comment by bredfern** [comment]
Thank you for the info your project is so awesome great work!

**Comment by mekya** [comment]
I've added a documentation for this as well.  Please check this out. 

https://github.com/ant-media/Ant-Media-Server/blob/master/doc/Getting_Started.md


Btw, closing this issue. Please reopen it if you have some problems
