### ISSUE TITLE
OnVIF camera Audio Codec Issue

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6178]
Ticket URL: https://antmedia.freshdesk.com/a/tickets/123022

StackTrace: 

`2024-03-12 14:40:44,404 [Thread-11] ERROR i.a.e.adaptive.EncoderAdaptor - java.lang.IllegalStateException: Could not allocate codec context: AV_CODEC_ID_AAC. Error is 부적절한 인수
	at io.antmedia.enterprise.adaptive.audio.AACEncoder.prepareCodecLocal(AACEncoder.java:85)
	at io.antmedia.enterprise.adaptive.base.AudioEncoder.prepareCodec(AudioEncoder.java:100)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareAudioEncoders(EncoderAdaptor.java:855)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareEncoders(EncoderAdaptor.java:798)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareEncoders(EncoderAdaptor.java:846)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareInternal(EncoderAdaptor.java:317)
	at io.antmedia.enterprise.adaptive.EncoderAdaptor.prepareFromInputFormatContext(EncoderAdaptor.java:339)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.prepareInputContext(StreamFetcher.java:377)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:266)`

**Comment by mekya** [comment]
Hi @mustafaboleken ,

It's not something to fix directly because the exception does not give me a clear idea of what the problem is. 

Then I'm putting this issue to Icebox. 

If you have an update, please let me know. 

Cheers
Oguz
