### ISSUE TITLE
ERROR BUG , memory also 

### ISSUE THREAD

**Issue by brixxnatt** [ant-media/Ant-Media-Server#6338]
2024-05-17 10:13:03,176 [Thread-60] ERROR i.a.streamsource.StreamFetcher - java.lang.NullPointerException: Pointer address of argument 1 is NULL.
	at org.bytedeco.ffmpeg.global.avutil.av_rescale_q(Native Method)
	at io.antmedia.muxer.Muxer.writePacket(Muxer.java:1075)
	at io.antmedia.muxer.HLSMuxer.writePacket(HLSMuxer.java:208)
	at io.antmedia.muxer.Muxer.writePacket(Muxer.java:516)
	at io.antmedia.muxer.MuxAdaptor.writePacket(MuxAdaptor.java:1332)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.writePacket(StreamFetcher.java:795)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.packetRead(StreamFetcher.java:644)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.readMore(StreamFetcher.java:343)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:311)

2024-05-17 10:13:03,197 [Thread-60] ERROR i.a.streamsource.StreamFetcher - java.lang.NullPointerException: Pointer address of argument 1 is NULL.
	at org.bytedeco.ffmpeg.global.avutil.av_rescale_q(Native Method)
	at io.antmedia.muxer.Muxer.writePacket(Muxer.java:1075)
	at io.antmedia.muxer.HLSMuxer.writePacket(HLSMuxer.java:208)
	at io.antmedia.muxer.Muxer.writePacket(Muxer.java:516)
	at io.antmedia.muxer.MuxAdaptor.writePacket(MuxAdaptor.java:1332)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.writePacket(StreamFetcher.java:795)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.packetRead(StreamFetcher.java:644)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.readMore(StreamFetcher.java:343)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:311)

2024-05-17 10:13:03,205 [Thread-60] ERROR i.a.streamsource.StreamFetcher - java.lang.NullPointerException: Pointer address of argument 1 is NULL.
	at org.bytedeco.ffmpeg.global.avutil.av_rescale_q(Native Method)
	at io.antmedia.muxer.Muxer.checkToDropPacket(Muxer.java:1008)
	at io.antmedia.muxer.Muxer.writePacket(Muxer.java:499)
	at io.antmedia.muxer.MuxAdaptor.writePacket(MuxAdaptor.java:1332)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.writePacket(StreamFetcher.java:795)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.packetRead(StreamFetcher.java:644)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.readMore(StreamFetcher.java:343)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:311)

2024-05-17 10:13:03,218 [Thread-60] ERROR i.a.streamsource.StreamFetcher - java.lang.NullPointerException: Pointer address of argument 1 is NULL.
	at org.bytedeco.ffmpeg.global.avutil.av_rescale_q(Native Method)
	at io.antmedia.muxer.Muxer.writePacket(Muxer.java:1075)
	at io.antmedia.muxer.HLSMuxer.writePacket(HLSMuxer.java:208)
	at io.antmedia.muxer.Muxer.writePacket(Muxer.java:516)
	at io.antmedia.muxer.MuxAdaptor.writePacket(MuxAdaptor.java:1332)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.writePacket(StreamFetcher.java:795)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.packetRead(StreamFetcher.java:644)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.readMore(StreamFetcher.java:343)
	at io.antmedia.streamsource.StreamFetcher$WorkerThread.run(StreamFetcher.java:311)

this is adding lot of CPU on my server , the CPU is acumalating eachtime this message comes  , please

**Comment by burak-58** [comment]
Hi @brixxnatt,
Thank you for the report. Please provide us a step by step scenario to reproduce it. If it is not private, please also share the stream source with us.

**Comment by mekya** [comment]
Hi @brixxnatt @burak-58 

I'm closing this issue for the inactivity. @brixxnatt you can provide step by step reproduce scenario and re-open the issue. 

Cheers
Oz
