### ISSUE TITLE
Assign Stream Sources to Specific Node

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#6712]

**Comment by muratugureminoglu** [comment]
<div>Agent Murat Ugur linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/134982">134982</a> for this issue.</div><br/>

**Comment by lastpeony** [comment]
Hello @alfred-stokespace 
Thank you for your explanation. This issue was actually a bug. When a user tries to watch a stopped stream with auto start/stop enabled, the request is sent to the edge node, edge node then fetches the stream from the source and performs the transcoding, which causes the problem.

With the new pull request, the edge node now checks the originAddress field in the broadcast and forwards the request to the origin node. The origin node then fetches the stream from the source and handles the transcoding as expected.

This fix is expected to be merged next week, but if you'd like, I can send you a snapshot for early testing.

**Comment by mekya** [comment]
Hi @burak-58 ,
I've refactored the code and merged it into the master.  This issue is closeable. 

FYI

**Comment by alfred-stokespace** [comment]
I'm sad to report that I'm still seeing this problem in my environment.

On-Prem "edge" instance: `Enterprise Edition 2.13.2 20250207_1708`
Cloud Instance: `Enterprise Edition 2.13.2 20250207_1708 `

Cluster page shows both servers. 👍 

I started a single stream (same details as before) on the "Cloud Instance" all good to start. 👍 

Then I move over the On-prem "edge" instance and I ask for the stream through LiveApp/play.html and the load numbers go through the roof on the edge server, cpu% max's out. 

I was looking through the logs on the "Edge" server and I did see something odd.  
Below we see that "Edge" server is trying to reach the other cluster member "Cloud" on port 80.  I'm confused why would that happen?  And am I reading this correctly, that following that failure the "edge" server thinks it needs to start the stream itself.

**PORT 80 is intentionally closed on the Cloud server**

```
2025-04-30 23:12:51,568 [https-jsse-nio2-0.0.0.0-5443-exec-6] INFO  i.a.e.s.WebSocketLocalHandler - Web Socket opened session:0 user-agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0]
2025-04-30 23:12:51,708 [https-jsse-nio2-0.0.0.0-5443-exec-10] INFO  i.a.e.w.WebSocketEnterpriseHandler - Start streaming for stream:REDACTED_CAMERA_NAME because auto start/stop is enabled
2025-04-30 23:12:53,773 [vert.x-worker-thread-7] ERROR i.a.AntMediaApplicationAdapter - org.apache.http.conn.ConnectTimeoutException: Connect to REDACTED_IP.78:80 [/REDACTED_IP.78] failed: Connect timed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at io.antmedia.AntMediaApplicationAdapter.callClusterRestMethod(AntMediaApplicationAdapter.java:1317)
        at io.antmedia.AntMediaApplicationAdapter.sendClusterPost(AntMediaApplicationAdapter.java:1297)
        at io.antmedia.AntMediaApplicationAdapter.lambda$trySendClusterPostWithDelay$10(AntMediaApplicationAdapter.java:1339)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 19 more

2025-04-30 23:12:54,839 [https-jsse-nio2-0.0.0.0-5443-exec-8] INFO  i.a.e.cluster.HttpLiveStreamValve - Broadcast is not streaming for stream: REDACTED_CAMERA_NAME and url:/LiveApp/streams/REDACTED_CAMERA_NAME_adaptive.m3u8
2025-04-30 23:12:54,840 [https-jsse-nio2-0.0.0.0-5443-exec-8] INFO  i.a.e.cluster.HttpLiveStreamValve - Broadcast has no origin address or it's not streaming for stream:REDACTED_CAMERA_NAME and url:/LiveApp/streams/REDACTED_CAMERA_NAME_adaptive.m3u8
2025-04-30 23:12:54,862 [https-jsse-nio2-0.0.0.0-5443-exec-8] INFO  i.antmedia.filter.StatisticsFilter - http play request(hls, dash) is received for stream id:REDACTED_CAMERA_NAME and it's not streaming, so it's trying to start the stream
2025-04-30 23:12:54,918 [https-jsse-nio2-0.0.0.0-5443-exec-9] INFO  i.a.e.cluster.HttpLiveStreamValve - Broadcast is not streaming for stream: REDACTED_CAMERA_NAME and url:/LiveApp/streams/REDACTED_CAMERA_NAME.m3u8
2025-04-30 23:12:54,918 [https-jsse-nio2-0.0.0.0-5443-exec-9] INFO  i.a.e.cluster.HttpLiveStreamValve - Broadcast has no origin address or it's not streaming for stream:REDACTED_CAMERA_NAME and url:/LiveApp/streams/REDACTED_CAMERA_NAME.m3u8
2025-04-30 23:12:54,948 [https-jsse-nio2-0.0.0.0-5443-exec-9] INFO  i.antmedia.filter.StatisticsFilter - http play request(hls, dash) is received for stream id:REDACTED_CAMERA_NAME and it's not streaming, so it's trying to start the stream
2025-04-30 23:12:55,780 [vert.x-worker-thread-8] ERROR i.a.AntMediaApplicationAdapter - org.apache.http.conn.ConnectTimeoutException: Connect to REDACTED_IP.78:80 [/REDACTED_IP.78] failed: Connect timed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at io.antmedia.AntMediaApplicationAdapter.callClusterRestMethod(AntMediaApplicationAdapter.java:1317)
        at io.antmedia.AntMediaApplicationAdapter.sendClusterPost(AntMediaApplicationAdapter.java:1297)
        at io.antmedia.AntMediaApplicationAdapter.lambda$trySendClusterPostWithDelay$10(AntMediaApplicationAdapter.java:1339)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 19 more
```

**Comment by muratugureminoglu** [comment]
<div>Agent Mohit Dubey linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/149903">149903</a> for this issue.</div><br/>

**Comment by alfred-stokespace** [comment]
I have an update on this issue. 

After looking through your code base a bit and thinking over how I configured the edge instance I discovered why there was a connection timeout on port 80 of the origin server (in the cloud).

As a matter of habit I want services in my network to be secure and encrypted so when I found out that the edge instance (running in side an on-prem network) had bare http exposed 
`http.port=5080` in `/usr/local/antmedia/conf/red5.properties`  
I balked at that and set that to zero on deployment
```
sed -i 's/^http\.port=5080/http.port=0/' /usr/local/antmedia/conf/red5.properties
```
It seems that zero'ing out led to the 80 port being selected, not sure why. 

So, I tried removing that zero-out and just leaving the default 5080. 

I can report that it's working better now (**not** great).  
Let me clarify what I mean.

Cloud server is the origin for the stream.
Edge server `REDACTED_EDGE_IP` is connecting over http(5080) now, to `REDACTED_SERVERIP`
```
2025-05-19 21:22:13,541 [https-jsse-nio2-0.0.0.0-5443-exec-8] INFO  i.a.e.cluster.HttpLiveStreamValve - url to download http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:22:13,602 [https-jsse-nio2-0.0.0.0-5443-exec-6] INFO  i.a.e.cluster.HttpLiveStreamValve - url to download http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar000000004.ts?hostAddress=REDACTED_EDGE_IP
```
and the load on the edge server is low while the stream is running
```
 top
top - 21:25:05 up 25 days,  1:14,  1 user,  load average: 0.01, 0.04, 0.06
Tasks: 135 total,   1 running, 134 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15543.1 total,   7869.6 free,   1731.5 used,   5942.0 buff/cache
MiB Swap:   4096.0 total,   4096.0 free,      0.0 used.  13474.2 avail Mem
```
**However**
I'm seeing the stream run for a bit, then die ("Your live stream will ....") then run for about 3-4 seconds, then die (same error) and that just repeats over and over again.

```
2025-05-19 21:27:02,870 [https-jsse-nio2-0.0.0.0-5443-exec-6] INFO  i.a.e.cluster.HttpLiveStreamValve - url to download http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:27:02,929 [https-jsse-nio2-0.0.0.0-5443-exec-10] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690022929
2025-05-19 21:27:02,961 [https-jsse-nio2-0.0.0.0-5443-exec-11] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690022961
2025-05-19 21:27:03,014 [https-jsse-nio2-0.0.0.0-5443-exec-1] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023014
2025-05-19 21:27:03,098 [https-jsse-nio2-0.0.0.0-5443-exec-9] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023098
2025-05-19 21:27:03,149 [https-jsse-nio2-0.0.0.0-5443-exec-7] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023149
2025-05-19 21:27:03,185 [https-jsse-nio2-0.0.0.0-5443-exec-5] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023185
2025-05-19 21:27:03,218 [https-jsse-nio2-0.0.0.0-5443-exec-10] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023218
2025-05-19 21:27:03,253 [https-jsse-nio2-0.0.0.0-5443-exec-4] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023253
2025-05-19 21:27:03,285 [https-jsse-nio2-0.0.0.0-5443-exec-1] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023285
2025-05-19 21:27:03,318 [https-jsse-nio2-0.0.0.0-5443-exec-9] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023318
2025-05-19 21:27:03,353 [https-jsse-nio2-0.0.0.0-5443-exec-7] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023353
2025-05-19 21:27:03,387 [https-jsse-nio2-0.0.0.0-5443-exec-5] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023387
2025-05-19 21:27:03,421 [https-jsse-nio2-0.0.0.0-5443-exec-10] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023421
2025-05-19 21:27:03,469 [https-jsse-nio2-0.0.0.0-5443-exec-4] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023469
2025-05-19 21:27:03,502 [https-jsse-nio2-0.0.0.0-5443-exec-1] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023502
2025-05-19 21:27:03,534 [https-jsse-nio2-0.0.0.0-5443-exec-9] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023534
2025-05-19 21:27:03,567 [https-jsse-nio2-0.0.0.0-5443-exec-7] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023567
2025-05-19 21:27:03,601 [https-jsse-nio2-0.0.0.0-5443-exec-5] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023601
2025-05-19 21:27:03,634 [https-jsse-nio2-0.0.0.0-5443-exec-10] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023634
2025-05-19 21:27:03,670 [https-jsse-nio2-0.0.0.0-5443-exec-4] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023670
2025-05-19 21:27:03,702 [https-jsse-nio2-0.0.0.0-5443-exec-1] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023702
2025-05-19 21:27:03,734 [https-jsse-nio2-0.0.0.0-5443-exec-9] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023734
2025-05-19 21:27:03,769 [https-jsse-nio2-0.0.0.0-5443-exec-7] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023769
2025-05-19 21:27:03,802 [https-jsse-nio2-0.0.0.0-5443-exec-5] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023802
2025-05-19 21:27:03,834 [https-jsse-nio2-0.0.0.0-5443-exec-10] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023834
2025-05-19 21:27:03,874 [https-jsse-nio2-0.0.0.0-5443-exec-4] INFO  i.a.e.cluster.HttpLiveStreamValve - File(/usr/local/antmedia/webapps/LiveApp/streams/foobar.m3u8) will not be downloaded because it's not expired last download time:1747690022894 current time: 1747690023874
2025-05-19 21:27:03,907 [https-jsse-nio2-0.0.0.0-5443-exec-1] INFO  i.a.e.cluster.HttpLiveStreamValve - url to download http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:27:03,970 [https-jsse-nio2-0.0.0.0-5443-exec-9] INFO  i.a.e.cluster.HttpLiveStreamValve - url to download http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar000000004.ts?hostAddress=REDACTED_EDGE_IP

```
Filtered out INFO below
```
2025-05-19 21:23:37,662 [https-jsse-nio2-0.0.0.0-5443-exec-3] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:23:37,832 [https-jsse-nio2-0.0.0.0-5443-exec-1] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:24:02,147 [https-jsse-nio2-0.0.0.0-5443-exec-6] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:24:02,458 [https-jsse-nio2-0.0.0.0-5443-exec-9] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:24:26,022 [https-jsse-nio2-0.0.0.0-5443-exec-2] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:24:26,170 [https-jsse-nio2-0.0.0.0-5443-exec-6] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:24:49,744 [https-jsse-nio2-0.0.0.0-5443-exec-8] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:24:49,892 [https-jsse-nio2-0.0.0.0-5443-exec-1] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:25:14,265 [https-jsse-nio2-0.0.0.0-5443-exec-2] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:25:14,424 [https-jsse-nio2-0.0.0.0-5443-exec-10] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:25:38,945 [https-jsse-nio2-0.0.0.0-5443-exec-4] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:25:39,104 [https-jsse-nio2-0.0.0.0-5443-exec-5] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:26:02,577 [https-jsse-nio2-0.0.0.0-5443-exec-7] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:26:02,737 [https-jsse-nio2-0.0.0.0-5443-exec-4] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:26:27,281 [https-jsse-nio2-0.0.0.0-5443-exec-4] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:26:27,472 [https-jsse-nio2-0.0.0.0-5443-exec-10] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:26:50,931 [https-jsse-nio2-0.0.0.0-5443-exec-2] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:26:51,081 [https-jsse-nio2-0.0.0.0-5443-exec-8] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:27:15,588 [https-jsse-nio2-0.0.0.0-5443-exec-4] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:27:15,732 [https-jsse-nio2-0.0.0.0-5443-exec-8] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:27:39,532 [https-jsse-nio2-0.0.0.0-5443-exec-7] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:27:39,718 [https-jsse-nio2-0.0.0.0-5443-exec-5] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:28:04,274 [https-jsse-nio2-0.0.0.0-5443-exec-2] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/streams/foobar_adaptive.m3u8?hostAddress=REDACTED_EDGE_IP
2025-05-19 21:28:04,433 [https-jsse-nio2-0.0.0.0-5443-exec-10] WARN  i.a.e.cluster.HttpLiveStreamValve - Response is 404 for downloading file: http://REDACTED_SERVERIP:5080/LiveApp/previews/foobar.png?hostAddress=REDACTED_EDGE_IP
```
when I look at the player console logs I see this alot

video.es-0951ae41-boIeAy0a.js:2728  VIDEOJS: WARN: Problem encountered with playlist 0-
https://REDACTED_DNS_OF_EDGE_SERVER:5443/LiveApp/streams/foobar.m3u8. Trying again since it is the only playlist.


I checked out the M3U8 and every time I see the TS segments never getting past foobar000000003.ts
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:1.066689,
#EXT-X-PROGRAM-DATE-TIME:2025-05-19T21:36:28.147+0000
foobar000000000.ts
#EXTINF:2.133311,
#EXT-X-PROGRAM-DATE-TIME:2025-05-19T21:36:29.213+0000
foobar000000001.ts
#EXTINF:2.133344,
#EXT-X-PROGRAM-DATE-TIME:2025-05-19T21:36:31.347+0000
foobar000000002.ts
#EXTINF:2.133333,
#EXT-X-PROGRAM-DATE-TIME:2025-05-19T21:36:33.480+0000
foobar000000003.ts
```
So It looks like the stream is starting over at segment zero and then gets to segment 3, fails and keeps repeating.
