### ISSUE TITLE
App creation returns unsuccessful sometimes in Circle tests

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#6755]
Update: In Circle tests, if don't delete conference app before installing webinar, there is no issue.

Here is the logs for an unsuccessful app creation:

2024-10-31 04:12:31,497 [http-nio2-0.0.0.0-5080-exec-4] INFO  o.r.s.a.MultiThreadedApplicationAdapter - War file uploaded for application, filesize = 5533643 path = /tmp/TestAPP138.war
2024-10-31 04:12:31,499 [http-nio2-0.0.0.0-5080-exec-4] INFO  o.r.s.a.MultiThreadedApplicationAdapter - Running create app script, war file name (null if default): /tmp/TestAPP138.war, app name: TestAPP138 
2024-10-31 04:12:31,499 [http-nio2-0.0.0.0-5080-exec-4] INFO  i.antmedia.console.AdminApplication - Creating application with command: /bin/bash create_app.sh -n TestAPP138 -w true -p /usr/local/antmedia -c true -m mongo -f /tmp/TestAPP138.war
2024-10-31 04:12:31,502 [Thread-48] INFO  i.antmedia.console.AdminApplication - Please use the POST REST method (/applications/{appName}) to create an application.

2024-10-31 04:12:31,502 [Thread-48] INFO  i.antmedia.console.AdminApplication - all parameters
TestAPP138 -w true -p /usr/local/antmedia -c true -m mongo -f /tmp/TestAPP138.war--> \n

2024-10-31 04:12:31,505 [Thread-48] INFO  i.antmedia.console.AdminApplication - /usr/local/antmedia

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication - Archive:  TestAPP138.war

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: META-INF/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: META-INF/MANIFEST.MF    
2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: static/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: static/css/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: static/media/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: static/js/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: WEB-INF/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: WEB-INF/classes/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: WEB-INF/classes/io/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: WEB-INF/classes/io/antmedia/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: WEB-INF/classes/io/antmedia/enterprise/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -    creating: WEB-INF/classes/io/antmedia/enterprise/streamapp/

2024-10-31 04:12:31,511 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: service-worker.js       
2024-10-31 04:12:31,512 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,512 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: virtual-background.png  
2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: robots.txt              
2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: .gitignore              
2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/css/main.b77d8507.css  
2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/css/main.b77d8507.css.map  
2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/media/leave-sound.28eb7bfe37c3c2707e28.mp3  
2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,523 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/media/OpenSans-Medium.65529e6c75fe516f596a.ttf  
2024-10-31 04:12:31,524 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,524 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/media/OpenSans-SemiBold.2b370b191e5562dadc78.ttf  
2024-10-31 04:12:31,526 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,526 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/media/join-sound.6044a21fc1c6bd252475.mp3  
2024-10-31 04:12:31,526 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,526 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/media/OpenSans-Bold.a0fe34bea92d4e1a84d6.ttf  
2024-10-31 04:12:31,527 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,527 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/media/OpenSans-Regular.57cd57a648021fa1c396.ttf  
2024-10-31 04:12:31,528 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,528 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/media/sprite.d105bc8d8ccd67f3bbba20c646c63270.svg  
2024-10-31 04:12:31,529 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,529 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/js/496.942abfec.chunk.js.map  
2024-10-31 04:12:31,530 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,530 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/js/845.96d4e0ae.chunk.js.LICENSE.txt  
2024-10-31 04:12:31,530 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,530 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/js/845.96d4e0ae.chunk.js.map  
2024-10-31 04:12:31,531 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,531 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/js/main.840b8b2d.js  
2024-10-31 04:12:31,539 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,539 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/js/845.96d4e0ae.chunk.js  
2024-10-31 04:12:31,539 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,539 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/js/496.942abfec.chunk.js  
2024-10-31 04:12:31,539 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,540 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/js/main.840b8b2d.js.LICENSE.txt  
2024-10-31 04:12:31,540 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,540 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: static/js/main.840b8b2d.js.map  
2024-10-31 04:12:31,570 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,570 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: META-INF/context.xml    

2024-10-31 04:12:31,570 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: speed-test-sample-video.mp4  
2024-10-31 04:12:31,575 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,575 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: spa.jsp                 
2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication - 
  inflating: logo512.png             
2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/red5-web.properties  
2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/web.xml         
2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/red5-web.xml    
2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/classes/io/antmedia/enterprise/streamapp/AMSBroadcastManager.class  
2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/classes/io/antmedia/enterprise/streamapp/AMSEndpointConfigurator.class  
2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/classes/io/antmedia/enterprise/streamapp/WebSocketLocalHandler.class  
2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/classes/io/antmedia/enterprise/streamapp/WebSocketApplicationConstants.class  
2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,576 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/classes/io/antmedia/enterprise/streamapp/WebSocketSignalingLocalHandler.class  
2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/classes/io/antmedia/enterprise/streamapp/ConferenceRoomSettings.class  
2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/classes/io/antmedia/enterprise/streamapp/WebSocketApplicationHandler.class  
2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: WEB-INF/classes/probe-template.xml  
2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: asset-manifest.json     
2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: index.html              
2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,577 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: service-worker.js.map   
2024-10-31 04:12:31,578 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,578 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: manifest.json           
2024-10-31 04:12:31,578 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,578 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: favicon.ico             
2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: logo192.png             
2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: favicon-32x32.png       
2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: service-worker.js.LICENSE.txt  
2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: META-INF/maven/io.antmedia.webrtc/ConferenceCall/pom.xml  
2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication -   inflating: META-INF/maven/io.antmedia.webrtc/ConferenceCall/pom.properties  
2024-10-31 04:12:31,579 [Thread-48] INFO  i.antmedia.console.AdminApplication - 

2024-10-31 04:12:31,593 [Thread-48] INFO  i.antmedia.console.AdminApplication - Cluster mode
Application will deployed as war

2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -   adding: META-INF/ (stored 0%)
  adding: META-INF/maven/
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: META-INF/maven/io.antmedia.webrtc/ (stored 0%)
  adding: META-INF/maven/io.antmedia.webrtc/ConferenceCall/ (stored 0%)
  adding: META-INF/maven/io.antmedia.webrtc/ConferenceCall/pom.properties
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: META-INF/maven/io.antmedia.webrtc/ConferenceCall/pom.xml
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 78%)
  adding: META-INF/MANIFEST.MF
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 1%)
  adding: META-INF/context.xml
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 10%)
  adding: WEB-INF/
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: WEB-INF/red5-web.properties
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 65%)
  adding: WEB-INF/web.xml
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 77%)
  adding: WEB-INF/classes/
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: WEB-INF/classes/io/ (stored 0%)
  adding: WEB-INF/classes/io/antmedia/
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: WEB-INF/classes/io/antmedia/enterprise/
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: WEB-INF/classes/io/antmedia/enterprise/streamapp/
2024-10-31 04:12:31,595 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: WEB-INF/classes/io/antmedia/enterprise/streamapp/WebSocketLocalHandler.class
2024-10-31 04:12:31,596 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 53%)
  adding: WEB-INF/classes/io/antmedia/enterprise/streamapp/WebSocketApplicationConstants.class
2024-10-31 04:12:31,596 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 49%)
  adding: WEB-INF/classes/io/antmedia/enterprise/streamapp/AMSEndpointConfigurator.class
2024-10-31 04:12:31,596 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 51%)
  adding: WEB-INF/classes/io/antmedia/enterprise/streamapp/AMSBroadcastManager.class
2024-10-31 04:12:31,596 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 58%)
  adding: WEB-INF/classes/io/antmedia/enterprise/streamapp/WebSocketApplicationHandler.class
2024-10-31 04:12:31,596 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 55%)
  adding: WEB-INF/classes/io/antmedia/enterprise/streamapp/WebSocketSignalingLocalHandler.class
2024-10-31 04:12:31,597 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 54%)
  adding: WEB-INF/classes/io/antmedia/enterprise/streamapp/ConferenceRoomSettings.class
2024-10-31 04:12:31,597 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 54%)
  adding: WEB-INF/classes/probe-template.xml
2024-10-31 04:12:31,597 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 50%)
  adding: WEB-INF/red5-web.xml
2024-10-31 04:12:31,597 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 73%)
  adding: asset-manifest.json
2024-10-31 04:12:31,597 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 70%)
  adding: favicon-32x32.png
2024-10-31 04:12:31,597 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: favicon.ico
2024-10-31 04:12:31,597 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 73%)
  adding: index.html
2024-10-31 04:12:31,597 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 45%)
  adding: logo192.png
2024-10-31 04:12:31,598 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: logo512.png
2024-10-31 04:12:31,599 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 1%)
  adding: manifest.json
2024-10-31 04:12:31,599 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 56%)
  adding: robots.txt
2024-10-31 04:12:31,599 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 10%)
  adding: service-worker.js
2024-10-31 04:12:31,600 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 68%)
  adding: service-worker.js.LICENSE.txt
2024-10-31 04:12:31,600 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 13%)
  adding: service-worker.js.map
2024-10-31 04:12:31,608 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 77%)
  adding: spa.jsp
2024-10-31 04:12:31,608 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 13%)
  adding: speed-test-sample-video.mp4
2024-10-31 04:12:31,635 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 0%)
  adding: static/ (stored 0%)
  adding: static/js/
2024-10-31 04:12:31,635 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (stored 0%)
  adding: static/js/845.96d4e0ae.chunk.js.LICENSE.txt
2024-10-31 04:12:31,635 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 54%)
  adding: static/js/main.840b8b2d.js
2024-10-31 04:12:31,675 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 72%)
  adding: static/js/845.96d4e0ae.chunk.js.map
2024-10-31 04:12:31,681 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 76%)
  adding: static/js/845.96d4e0ae.chunk.js
2024-10-31 04:12:31,682 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 73%)
  adding: static/js/main.840b8b2d.js.LICENSE.txt
2024-10-31 04:12:31,682 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 81%)
  adding: static/js/496.942abfec.chunk.js.map
2024-10-31 04:12:31,682 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 67%)
  adding: static/js/496.942abfec.chunk.js
2024-10-31 04:12:31,683 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 64%)
  adding: static/js/main.840b8b2d.js.map
2024-10-31 04:12:31,888 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 75%)
  adding: static/media/ (stored 0%)
  adding: static/media/OpenSans-SemiBold.2b370b191e5562dadc78.ttf
2024-10-31 04:12:31,894 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 40%)
  adding: static/media/sprite.d105bc8d8ccd67f3bbba20c646c63270.svg
2024-10-31 04:12:31,897 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 64%)
  adding: static/media/OpenSans-Regular.57cd57a648021fa1c396.ttf
2024-10-31 04:12:31,903 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 40%)
  adding: static/media/leave-sound.28eb7bfe37c3c2707e28.mp3
2024-10-31 04:12:31,903 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 12%)
  adding: static/media/OpenSans-Bold.a0fe34bea92d4e1a84d6.ttf
2024-10-31 04:12:31,909 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 41%)
  adding: static/media/join-sound.6044a21fc1c6bd252475.mp3
2024-10-31 04:12:31,910 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 2%)
  adding: static/media/OpenSans-Medium.65529e6c75fe516f596a.ttf
2024-10-31 04:12:31,915 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 39%)
  adding: static/css/ (stored 0%)
  adding: static/css/main.b77d8507.css
2024-10-31 04:12:31,916 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 62%)
  adding: static/css/main.b77d8507.css.map
2024-10-31 04:12:31,916 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 66%)
  adding: virtual-background.png
2024-10-31 04:12:31,973 [Thread-48] INFO  i.antmedia.console.AdminApplication -  (deflated 0%)

2024-10-31 04:12:31,976 [Thread-48] INFO  i.antmedia.console.AdminApplication - TestAPP138 is created.

2024-10-31 04:12:31,977 [vert.x-worker-thread-46] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
2024-10-31 04:12:32,084 [vert.x-worker-thread-46] INFO  o.red5.server.tomcat.TomcatLoader - Starting Tomcat - Web application
2024-10-31 04:12:32,084 [vert.x-worker-thread-46] INFO  o.red5.server.tomcat.TomcatLoader - Application root: /usr/local/antmedia/webapps
2024-10-31 04:12:32,157 [vert.x-worker-thread-46] INFO  org.red5.server.LoaderBase - Set application context - path: 0.0.0.0/TestAPP138 context: org.red5.server.tomcat.TomcatApplicationContext@cd5be7
2024-10-31 04:12:32,157 [vert.x-worker-thread-46] ERROR o.red5.server.tomcat.TomcatLoader - Error setting up context: TestAPP138 due to: The resources may not be accessed if they are not currently started
2024-10-31 04:12:32,161 [vert.x-worker-thread-46] ERROR o.red5.server.tomcat.TomcatLoader - java.lang.IllegalStateException: The resources may not be accessed if they are not currently started
	at org.apache.catalina.webresources.StandardRoot.validate(StandardRoot.java:240)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:207)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:202)
	at org.apache.catalina.core.StandardContext.getRealPath(StandardContext.java:3698)
	at org.apache.catalina.core.ApplicationContext.getRealPath(ApplicationContext.java:347)
	at org.apache.catalina.core.ApplicationContextFacade.getRealPath(ApplicationContextFacade.java:255)
	at org.red5.server.tomcat.TomcatLoader.startWebApplication(TomcatLoader.java:611)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:262)
	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at java.management/com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:814)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:802)
	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy$InvokeHandler.invoke(MXBeanProxy.java:150)
	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
	at java.management/javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
	at jdk.proxy2/jdk.proxy2.$Proxy123.startWebApplication(Unknown Source)
	at org.red5.server.tomcat.WarDeployer.deploy(WarDeployer.java:147)
	at io.antmedia.console.AdminApplication.lambda$createApplication$2(AdminApplication.java:369)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by burak-58** [comment]
I can not reproduce the issue anymore even if I run everything the same for several times.
Moreover, I created an automation which installs and deletes the applications several times with the same and different names.
