### ISSUE TITLE
Stuttering transcoded streams

### ISSUE THREAD

**Issue by SebastienGautier** [ant-media/Ant-Media-Server#6760]
### Short description
There is a lot of stuttering in some of the streams affecting both the audio and the video

### Environment

* Operating system and version: Ubuntu 22.04
* Java version: openjdk 17.0.12
* Ant Media Server version: 2.12.0
* Browser name and version: unrelated

### Steps to reproduce
1. Send 1080p rtmp stream with transcoding to 1080p 720p and 480p
2. There is a lot of stuttering in some of the streams with both the audio and the video affected

### Expected behavior
Not stuttering, smooth video and audio

### Actual behavior
There is a lot of stuttering, video is not watchable

Our auto scaling is working well with a setting on average CPU of 70% and actual CPU usage rarely exceeds 80% so that should not be the cause.

### Logs
We get a lot of this in the logs, not all streams are concerned and it looks like is mainly streams with transcoding
`INFO  i.a.e.adaptive.StreamAdaptor - Queue size(2001) is exceeding 2000 so dropping frame for stream: xx`

Possibly related logs:
```[AMS] 	at java.base@17.0.12/java.lang.Thread.run(Thread.java:840)
[AMS] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[AMS] 	at java.base@17.0.12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[AMS] 	at java.base@17.0.12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[AMS] 	at io.vertx.core.impl.ContextImpl$$Lambda$522/0x00000007f95a4ad0.run(Unknown Source)
[AMS] 	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
[AMS] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
[AMS] 	at io.vertx.core.impl.ContextImpl$$Lambda$520/0x00000007f95a4668.handle(Unknown Source)
[AMS] 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
[AMS] 	at io.antmedia.enterprise.adaptive.StreamAdaptor$$Lambda$918/0x00000007f98c9920.call(Unknown Source)
[AMS] 	at io.antmedia.enterprise.adaptive.StreamAdaptor.lambda$start$0(StreamAdaptor.java:200)
[AMS] 	at io.antmedia.enterprise.adaptive.StreamAdaptor.execute(StreamAdaptor.java:247)
[AMS] 	at io.antmedia.enterprise.adaptive.StreamAdaptor.write2VideoEncoders(StreamAdaptor.java:389)
[AMS] 	at io.antmedia.enterprise.adaptive.base.VideoEncoder.writeFrame(VideoEncoder.java:276)
[AMS] 	at io.antmedia.enterprise.adaptive.video.H264Encoder.writeFrameInternal(H264Encoder.java:198)
[AMS] 	at io.antmedia.enterprise.adaptive.video.H264Encoder.sendPacket2Encoder(H264Encoder.java:704)
[AMS] 	at io.antmedia.enterprise.adaptive.video.H264Encoder.avCodecSendFrame(H264Encoder.java:720)
[AMS] 	at org.bytedeco.ffmpeg.global.avcodec.avcodec_send_frame(Native Method)
[AMS] io.vertx.core.VertxException: Thread blocked
[AMS] 2024-11-04 15:49:30,957 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-worker-thread-62,5,main] has been blocked for 561152 ms, time limit is 10000 ms
```
```
[AMS] 2024-11-04 15:49:30,935 [NioProcessor-3] INFO  o.r.s.n.r.codec.RTMPProtocolDecoder - Extended timestamp exists because timevalue is 0xffffff chunkheader:ChunkHeader [type=0, channelId=4, size=1]
[AMS] 2024-11-04 15:49:30,933 [NioProcessor-7] INFO  o.r.s.n.r.codec.RTMPProtocolDecoder - Extended timestamp exists because timevalue is 0xffffff chunkheader:ChunkHeader [type=0, channelId=5, size=1]
[AMS] 2024-11-04 15:49:30,933 [NioProcessor-7] INFO  o.r.s.n.r.codec.RTMPProtocolDecoder - Extended timestamp exists because timevalue is 0xffffff chunkheader:ChunkHeader [type=0, channelId=5, size=1]
[AMS] 2024-11-04 15:49:30,933 [NioProcessor-7] INFO  o.r.s.n.r.codec.RTMPProtocolDecoder - Extended timestamp exists because timevalue is 0xffffff chunkheader:ChunkHeader [type=0, channelId=4, size=1]
```

**Comment by burak-58** [comment]
Hi @SebastienGautier,
The logs you provided shows us the server capacity is in sufficent to encode stream in time. So encode buffer size increases. Just for trial you can disable 2 ABR settings and observe if the issue still exists.

**Comment by ocatta** [comment]
@burak-58 "Server capacity is insufficient", are we talking CPU or Memory ? Should we aim to limit the incoming bitrate / fps from our customers ?

**Comment by SebastienGautier** [comment]
@burak-58 We can't disable ABR settings, we're live and customers are paying for them.
We're noticing this issue on a stream at this time, I'm also seeing this A LOT in the logs in addition to the _Queue size(2001) is exceeding 2000_ message:
`[AMS] 2024-11-14 09:47:12,388 [NioProcessor-12] INFO  o.r.s.n.r.codec.RTMPProtocolDecoder - Extended timestamp exists because timevalue is 0xffffff chunkheader:ChunkHeader [type=0, channelId=4, size=1]`

The current stats of the server handling this stream is 75% CPU usage and 58% memory usage, not overloaded at all so I doubt it's due to insufficient capacity ?
Please let us know if you need any access to investigate this, customers are complaining about this.

**Comment by burak-58** [comment]
Instead of getting access we can schedule a meeting and check it together. I will send an email.
