### ISSUE TITLE
PeerToPeer call stop issue on Android SDK

### ISSUE THREAD

**Issue by ivoperic** [ant-media/Ant-Media-Server#6790]
### Short description
Stop peer to peer call doesn't work on android.

After this method

    `webRTCClient.stop("room")`
call wont stop and call is active till user kills app.

### Environment

* Operating system and version: Android 14

### Steps to reproduce
1.  Make peer to peer call
2. call client.join("room") to start call
3. call client.stop("room") to stop/leave call

### Expected behavior
Call should stop

### Actual behavior
Call remains active.

 

### Logs
`Handler (de.tavendo.autobahn.WebSocketWriter$ThreadHandler) {3e90511} sending message to a Handler on a dead thread
                                                                                                    java.lang.IllegalStateException: Handler (de.tavendo.autobahn.WebSocketWriter$ThreadHandler) {3e90511} sending message to a Handler on a dead thread
                                                                                                    	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:603)
                                                                                                    	at android.os.Handler.enqueueMessage(Handler.java:787)
                                                                                                    	at android.os.Handler.sendMessageAtTime(Handler.java:736)
                                                                                                    	at android.os.Handler.sendMessageDelayed(Handler.java:706)
                                                                                                    	at android.os.Handler.sendMessage(Handler.java:644)
                                                                                                    	at de.tavendo.autobahn.WebSocketWriter.forward(WebSocketWriter.java:95)
                                                                                                    	at de.tavendo.autobahn.WebSocketConnection.failConnection(WebSocketConnection.java:109)
                                                                                                    	at de.tavendo.autobahn.WebSocketConnection.handleMessage(WebSocketConnection.java:410)
                                                                                                    	at de.tavendo.autobahn.WebSocketConnection.access$1(WebSocketConnection.java:344)
                                                                                                    	at de.tavendo.autobahn.WebSocketConnection$ThreadHandler.handleMessage(WebSocketConnection.java:536)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8592)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)`

**Comment by lastpeony** [comment]
What is your android sdk version?
In latest version this problem should not occur

https://github.com/ant-media/WebRTC-Android-SDK/releases/tag/v2.11.1

**Comment by ivoperic** [comment]
Latest SDK version. I pulled demo project from gitHUB from master branch (https://github.com/ant-media/WebRTC-Android-SDK)

`ext {
    PUBLISH_GROUP_ID = 'io.antmedia'
    PUBLISH_VERSION = '2.11.1'
    PUBLISH_ARTIFACT_ID = 'webrtc-android-framework'
}`

**Comment by lastpeony** [comment]
I actually reproduced this and there is a fix, but could not understand how this occured, feels like there is a behaviour change on server side / webrtc messages(?)

**Comment by ivoperic** [comment]
Do you know, when this will be merged into master/release?

**Comment by burak-58** [comment]
It is merged. I am closing the issue. Feel free to reopen unless it solves your issue.
