### ISSUE TITLE
cant start ant media server after installation on ubuntu 

### ISSUE THREAD

**Issue by koloraben** [ant-media/Ant-Media-Server#730]
# Issue

### Short description
cant start ant media server after installation on ubuntu 

### Environment

* Operating system and version:fresh ubuntu 16.04
* Java version: 1.8
* Ant Media Server version: Ant Media Server Community 1.6.0
* Browser name and version: chrome

### Expected behavior
access web interface at http://localhost:5080

### Actual behavior
server not started

### Logs

Bootstrap exception: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.red5.server.Bootstrap.bootStrap(Bootstrap.java:122)
	at org.red5.server.Bootstrap.main(Bootstrap.java:50)
Caused by: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:764)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:726)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.bytedeco.javacpp.avformat.<clinit>(avformat.java:14)
	at org.red5.server.Launcher.launch(Launcher.java:67)
	... 6 more
Caused by: java.lang.UnsatisfiedLinkError: no avutil in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:752)
	... 14 more
Bootstrap exit

**Comment by SelimEmre** [comment]
Hi @koloraben ,
Sorry for the delay. We are hard working at these times. I think you run in 32 bit Ubuntu 16.04 system. Ant Media Server only run in 64 bit Operation Systems for now.

**Comment by SelimEmre** [comment]
Hi @koloraben ,
Sorry for the delay. We are hard working at these times. We are recommending 64 bit in Operating System.

**Comment by koloraben** [comment]
Thank you. I think this is the problem i tried ubuntu 64 bit and it worked successfully 🙂

**Comment by SelimEmre** [comment]
If you have any problem, please reopen this issue. Thanks.

**Comment by thangamdus** [comment]
i have the same issue on windows MINGW64_NT-10 OS, Can you please post any solution

**Comment by BerOrson** [comment]
Have same issue on Ubuntu 16.04 - 32bit

**Comment by koloraben** [comment]
Install it on 64bit and it should work properly
